### ISSUE TITLE
 import seurat object error:cannot coerce class ‘structure("AnnotatedDataFrame", package = "Biobase")’ to a data.frame

### ISSUE THREAD

**Issue by Sophia409** [cole-trapnell-lab/monocle3#101]
@ctrapnell Hello, recently monocle 3 has upgraded.And after I modify the code that is used to import seurat  object according to new new_cell_data_set function,it gave errors. Can you give me some help?Thank you very much.
>
> #262 how to import seurat object
> data <- Merge.integrated@assays$RNA@data
> cell_metadata <- new('AnnotatedDataFrame', data = Merge.integrated@meta.data)
> fData <- data.frame(gene_short_name = row.names(data), row.names = row.names(data))
> gene_metadata <- new('AnnotatedDataFrame', data = fData)
> #Construct monocle cds
> tdcds <-  new_cell_data_set(data,
> cell_metadata = cell_metadata,
> gene_metadata = gene_metadata
> )`

`Error in as.data.frame.default(from) : 
  cannot coerce class ‘structure("AnnotatedDataFrame", package = "Biobase")’ to a data.frame`

**Comment by hpliner** [comment]
Hello,

new_cell_data_set takes data.frames as input for gene_metadata and cell_metadata. You should no longer convert to an AnnotatedDataFrame.
