### ISSUE TITLE
LSI not included as an option in cluster_cells

### ISSUE THREAD

**Issue by andrewhill157** [cole-trapnell-lab/monocle3#103]
LSI is not currently an option (only PCA, tSNE, and UMAP are allowed) for `cluster_cells`. Two options I can think of:
1. Include LSI
2. Allow arbitrary inputs and then check that it is a reduction stored in the object. This could also apply to other functions that take a reduced dim name as a parameter and might provide more flexibility if adding your own reduced dim spaces (say one that is a corrected space using a batch correction tool, etc.)

**Comment by hpliner** [comment]
Went with option 1 for the moment, but will think about how best to do something like option 2 in future. Just pushed to develop, will get merged to master at the end of the week

**Comment by hpliner** [comment]
Fixed in 0.1.1
