### ISSUE TITLE
resolution in cluster_cells function doesn't work

### ISSUE THREAD

**Issue by Sophia409** [cole-trapnell-lab/monocle3#107]
Hi,
when I gave code cluster_cells without resolution, it worked.But with resolutionadded,it gave error.Can you verify this function?Thanks!
```
> ppincds <- cluster_cells(ppincds,reduction_method = "tSNE")
> ppincds <- cluster_cells(ppincds,reduction_method = "tSNE",resolution=c(10^seq(-6,-1)))
Error in system("which python", intern = TRUE) : 'which' not found
````

**Comment by hpliner** [comment]
Thank you for submitting a bug report. Your report has insufficient information for us to address it. Please respond with the information requested in the bug report issue template. At minimum, please include: 

1. The code you ran that generated the error
2. The output of the call - and what was expected
3. The output of traceback()
4. The output of sessionInfo()

We will close this issue - when you answer with this further information, please reopen the issue.

- Monocle3 Dev Team

**Comment by zacharylau10** [comment]
windows has no `which python`, so produce the error.
