### ISSUE TITLE
estimate_size_factors doesn't check for "0 expression" cells 

### ISSUE THREAD

**Issue by sanjayrsrivatsan** [cole-trapnell-lab/monocle3#112]
** If this is a question and not a bug report or enhancement request, please post to our google group at https://groups.google.com/forum/#!forum/monocle-3-users**

**Describe the bug**

**To Reproduce**
The code that produced the bug:

**traceback()**
After the error, run traceback() in R and post the output:

**Expected behavior**

**Screenshots**

**sessionInfo():**
Run sessionInfo() in R and post the output

**Additional context**

**Comment by sanjayrsrivatsan** [comment]
estimates a size factor of infinity for all cells in a cds if there are cells with 0 molecules.
Maybe need to add a check and a warning that there are X number of cells with 0 molecules?

**Comment by hpliner** [comment]
Fixed in 0.1.1
