### ISSUE TITLE
model_formula_str doesn't work in  fit_models

### ISSUE THREAD

**Issue by Sophia409** [cole-trapnell-lab/monocle3#113]
Hi,
time is a column name in my phenodata,and in the meantime,it can bring batch effect.So i need to use ~time+time.But it doesn't work after my attempt.
```
> gene_fits = fit_models(cds_subset, model_formula_str = "~time+time")
> gene_fits = fit_models(cds_subset, model_formula_str = "~time + batch")
> gene_fits = fit_models(cds_subset, model_formula_str = "~time + btch")
> gene_fits = fit_models(cds_subset, model_formula_str = "~tim")
> fit_coefs = coefficient_table(gene_fits)
> gene_fits = fit_models(cds_subset, model_formula_str = "~")
Error in parse(text = x, keep.source = FALSE) : 
  <text>:2:0: unexpected end of input
1: ~
   ^
> gene_fits = fit_models(cds_subset, model_formula_str = "~d")
```

**Comment by ctrapnell** [comment]
Thank you for submitting a bug report. Your report has insufficient information for us to address it. Please respond with the information requested in the bug report issue template. At minimum, please include:

1. The code you ran that generated the error
2. The output of the call - and what was expected
3. The output of traceback()
4. The output of sessionInfo()

In this case, we'd also need to see what your colData() looks like.

We will close this issue - when you answer with this further information, please reopen the issue.

- Monocle3 Dev Team
