### ISSUE TITLE
plot_cells - Using alpha for a discrete variable is not advised

### ISSUE THREAD

**Issue by dwucsf** [cole-trapnell-lab/monocle3#117]
I'm plotting gene expression using:

plot_cells(cds, genes = "NEUROG3")

I'm getting the following warning message: "Using alpha for a discrete variable is not advised."

What does this mean?

**Comment by hpliner** [comment]
This is an internal ggplot warning that you can ignore. We will suppress the message in the next release.

**Comment by dwucsf** [comment]
Thank you, @hpliner!
