### ISSUE TITLE
Cant get Monocle3 installed

### ISSUE THREAD

**Issue by cswoboda** [cole-trapnell-lab/monocle3#118]
Hey all, 
I'm trying to work with Monocle3 and for some reason I can't get it loaded from GitHub. I have the correct and most updated versions of R(3.6.0) and Bioconductor(version 3.9 (BiocManager 1.30.4)), but when I run the devtools::install_github('cole-trapnell-lab/monocle3')  command, I get this error:

Downloading GitHub repo cole-trapnell-lab/monocle3@master
Skipping 8 packages not available: Biobase, BiocGenerics, DelayedArray, DelayedMatrixStats, limma, S4Vectors, SingleCellExperiment, SummarizedExperiment
Installing 30 packages: classInt, coda, DBI, DelayedArray, DelayedMatrixStats, deldir, dqrng, e1071, expm, gmodels, grr, LearnBayes, Matrix.utils, pbmcapply, pryr, pscl, RcppAnnoy, RcppParallel, RhpcBLASctl, S4Vectors, sf, SingleCellExperiment, sitmo, sp, spData, spdep, speedglm, SummarizedExperiment, units, uwot
Error: (converted from warning) packages ‘DelayedArray’, ‘DelayedMatrixStats’, ‘S4Vectors’, ‘SingleCellExperiment’, ‘SummarizedExperiment’ are not available (for R version 3.6.0)
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

and when I library(monocle3)  after a new session, it says the package doesn't exist. 

Hopefully someone can help! Sorry about the post formatting, very new to coding and GitHub.

**Comment by MLKaufman** [comment]
I was unable to use R 3.6 to get all the modules to install. I had to revert back to R 3.5.1.

Here was the workflow using conda I was able to get to install Monocle3 Beta. Some packages had to be installed using Bioconda, but may not be the case for everyone and every environment.

conda install python
conda install louvain
conda install numpy
conda install r=3.5.1
conda install bioconductor-rhdf5
conda install r-udunits2
conda install r-sf
conda install r-biocmanager

# in r:
BiocManager::install(c(“Biobase”, “BiocGenerics”,“DelayedArray”,“DelayedMatrixStats”,“limma”,“S4Vectors”,“SingleCellExperiment”,“SummarizedExperiment”))

install.packages(“devtools”)

devtools::install_github(‘cole-trapnell-lab/monocle3’)

**Comment by cswoboda** [comment]
This worked for me! Thanks so much!

**Comment by johnmous** [comment]
@MLKaufman Thanks a lot for the suggestion, it also worked for me on our cluster

**Comment by xqiu625** [comment]
But the dependent package 'batchelor' cannot installed on R 3.5.1, it needs R 3.6.

**Comment by MLKaufman** [comment]
You can install batchelor on an older version of R by installing it from source. Download the source file from BioConductor:

http://bioconductor.org/packages/release/bioc/html/batchelor.html
http://bioconductor.org/packages/release/bioc/src/contrib/batchelor_1.2.2.tar.gz

in R:
install.packages('batchelor_1.2.2.tar.gz', repos = NULL, type="source")

**Comment by deb0612** [comment]
When use devtools::install_github("cole-trapnell-lab/monocle3")
I got a error :  
Error: Failed to install 'monocle3' from GitHub:
  (converted from warning) packages ‘batchelor’, ‘Matrix.utils’ are not available (for R version 3.6.1)

I downloaded the source file of batchelor and Matrix.utils. The batchelor file is fine but the Matrix.utils file was removed from the CRAN repository(https://cran.rstudio.com/web/packages/Matrix.utils/index.html). I installed old version of Matrix.utils and got message below:
------------------------------------------------
install.packages("~/cicero/Matrix.utils_0.9.7.tar.gz", repos = NULL, type = "source")
Installing package into ‘/home/rstudio-user/cicero/packrat/lib/x86_64-pc-linux-gnu/3.6.1’
(as ‘lib’ is unspecified)
ERROR: dependency ‘grr’ is not available for package ‘Matrix.utils’
* removing ‘/home/rstudio-user/cicero/packrat/lib/x86_64-pc-linux-gnu/3.6.1/Matrix.utils’
Warning in install.packages :
  installation of package ‘/home/rstudio-user/cicero/Matrix.utils_0.9.7.tar.gz’ had non-zero exit status
--------------------------------------------------------------------

**Comment by AgnesSteixner** [comment]
I observed the same problem with 'Matrix.utils' as @deb0612 on Windows, when trying to install Monocle3 with R v3.6.2:

> ERROR: dependency 'Matrix.utils' is not available for package 'monocle3'
> * removing 'D:/Users/Documents/R/R-3.6.2/library/monocle3'
> Error: Failed to install 'monocle3' from GitHub:
>   (converted from warning) installation of package ‘D:/Users/AppData/Local/Temp/Rtmp2VpwDB/file28d43a4c12a3/monocle3_0.2.0.tar.gz’ had non-zero exit status 

Any suggestions on how to solve this would be appreciated =)

**Comment by MubasherMohammed** [comment]
when I tried to use devtools::install_github("cole-trapnell-lab/monocle3")
it gives me the error:
Error: (converted from warning) Setting LC_CTYPE failed, using "C"
Execution halted
Error: Failed to install 'monocle3' from GitHub:
  Failed to install 'leidenbase' from GitHub:
  (converted from warning) installation of package '/var/folders/tb/6x_281qd6mb3f5jg6ms50scm0000gn/T//RtmpZHMbut/filee3441ccb5dd0/leidenbase_0.1.0.tar.gz' had non-zero exit status
any suggestions? very much appreciated!!
