### ISSUE TITLE
Subsetting CDS and performing graph_test()

### ISSUE THREAD

**Issue by dwucsf** [cole-trapnell-lab/monocle3#123]
In your tutorial page, you recommend that we specify "principal_graph" for the "neighbor_graph" option in graph_test() of an entire cds. 

ciliated_cds_pr_test_res = graph_test(cds, neighbor_graph="principal_graph", cores=4)

However, when we subset our cds, you don't state that we should also specify  "principal_graph" for the "neighbor_graph" option. The default is "knn."

subset_pr_test_res = graph_test(cds_subset, cores=4)

Is there a reason why you recommend "principal_graph" for running graph_test() with an entire CDS but not for a subsetted CDS?

Thank you! This is a great resource!

**Comment by ctrapnell** [comment]
Thanks for your patience on this. You should really be able to do either whether or not you're subsetting. We didn't mean to imply that subsetting had bearing on which one you choose.
