### ISSUE TITLE
Colors denoting gene expression intensity

### ISSUE THREAD

**Issue by dwucsf** [cole-trapnell-lab/monocle3#128]
A small issue: is there a way for users to change the coloring scheme for plots that show gene expression intensity? The default coloring scheme (teal to green) is a little hard to work with in terms of distinguishing what is lowly and highly expressed. Seurat's default gray to red color scheme is a little more easily readable.

**Comment by hpliner** [comment]
plot_cells returns a ggplot object, so you can use ggplot's functions to alter color schemes by just adding them on as below:

library(ggplot2)
plot_cells(cds, genes = c("NDRG4")) + scale_color_gradient(low = "grey", high = "red")

**Comment by dwucsf** [comment]
Thank you for the kind explanation, @hpliner!
