### ISSUE TITLE
Issues with order_cells function in Monocle 3 when using use_partition = F

### ISSUE THREAD

**Issue by DmitryVel** [cole-trapnell-lab/monocle3#130]
Hi,

I have observed two issues with order_cells function in Monocle 3.
I run the default Monocle 3 pipeline up until "cluster_cells". 
I then import my UMAP coordinates and clustering results into the Monocle 3 from Seurat by using this workaround:
```
#Import UMAP coordinates from Seurat
s.umap <- GE.CTX@"reductions"$umap[[]]
s.umap = s.umap[rownames(cds@reducedDims$"UMAP"),]
cds@reducedDims$"UMAP" <- s.umap

#Import clusters from Seurat
s.clusters = cbind(rownames(GE.CTX@"meta.data"),GE.CTX@"meta.data"$RNA_snn_res.1)
rownames(s.clusters) <- s.clusters[,1]
s.clusters <- as.data.frame(s.clusters)
s.clusters[,1] <- NULL
s.clusters = s.clusters[names(cds@clusters$"UMAP"$"clusters"),1]
cds@clusters$"UMAP"$"clusters" <- s.clusters
```
Where cds is my Monocle 3 object and GE.CTX is my Seurat 3 object.

Then I run Moncole 3 with default parameters except using use_partition = F in learn_graph.
Firstly, when some nodes are chosen from the trajectory, I get this error:
```
Error in as.igraph.vs(graph, v) : Invalid vertex names
```
In addition, I consistently have a problem with a large proportion of my cells having infinite pseudotime:

![clust_pt](https://user-images.githubusercontent.com/6181537/59956760-18224a00-9447-11e9-847f-73728ad56a17.png)

When I use use_partition = T, I can pick any node but still have the issue of most cells having infinite pseudotime.

Importantly, when I import the graph, umap coordinates and clustering results from Monocle 3 to Monocle 3 alpha and run orderCells function, I get pseudotime values for all the cells in the trajectory that also make sense biologically:

![traj_1](https://user-images.githubusercontent.com/6181537/59957529-15772300-944e-11e9-9185-7fe4fce7afa7.png)

Also, Monocle 3 alpha allows selecting any nodes (not only root nodes). Here, I used Monocle 3 alpha to calculate pseudotime starting in the middle of the trajectory:

![traj_2](https://user-images.githubusercontent.com/6181537/59957551-35a6e200-944e-11e9-9248-80299331cfcf.png)

Other users (https://github.com/cole-trapnell-lab/monocle-release/issues/280) reported similar problems they encountered in analyzing their datasets so I don't think this issue is specific to my data. As in the referenced post, I suspect the problem is in the way partitionCells function works; in Monocle 3 alpha after importing UMAP coordinates and clusters from Seurat and running partitionCells, I get one partition, and everything works. If I have two partitions in Monocle 3 alpha, then there is the same problem with infinite pseudotime as in Monocle 3.

Any ideas on how to solve these problems would be appreciated.

Thanks,
Dmitry

**Comment by DmitryVel** [comment]
UPDATE: I used the workaround described in https://github.com/cole-trapnell-lab/monocle-release/issues/280 in Monocle 3 by reducing the number of partitions to 1. After that, I can get pseudotime for all cells in Monocle 3:

```
cds@clusters$UMAP$partitions[cds@clusters$UMAP$partitions == "2"] <- "1"
cds <- learn_graph(cds, use_partition = F)
cds <- order_cells(cds, root_pr_nodes = c("Y_166"))
plot_cells(cds, color_cells_by = "pseudotime", label_cell_groups=FALSE, label_leaves=FALSE, label_branch_points=FALSE, graph_label_size=1.5)
```

![clust_pt](https://user-images.githubusercontent.com/6181537/59959448-39496180-946c-11e9-95f1-e9b525932720.png)

Can also get pseudotime starting from a mid-point after using the workaround:

![clust_pt_1](https://user-images.githubusercontent.com/6181537/59959488-0f446f00-946d-11e9-9163-1c93c6baf74d.png)

Interestingly, it only works if reducing partitions to a single partition before running learn_graph. If done before order_cells but after learn_graph, infinite pseudotime values are produced:

```
cds <- learn_graph(cds, use_partition = F)
cds@clusters$UMAP$partitions[cds@clusters$UMAP$partitions == "2"] <- "1"
cds <- order_cells(cds, root_pr_nodes = c("Y_166"))
plot_cells(cds, color_cells_by = "pseudotime", label_cell_groups=FALSE, label_leaves=FALSE, label_branch_points=FALSE, graph_label_size=1.5)
```

![clust_pt_trunc](https://user-images.githubusercontent.com/6181537/59959459-8299b100-946c-11e9-9634-c45db2629af3.png)

Since I guess the idea behind use_partition = F is to remove the effect of partitions from psuedotime analysis, partitions having an affect on pseudotime calculations based on a graph constructed with use_partition = F seems like a bug?

**Comment by alexander-7** [comment]
Hi, this answer is probably a bit too late, but I had the same issue with the order_cell function as @lb15 in Monocle after manually replacing the UMAP embeddings (see comment above). When you replace the UMAP embeddings, you also replace the rownames and colnames of the respective objects. However, in a unmodified cds object these colnames and rownames are NULL and get replaced with 'V1' within the order_cell function. If they are not NULL, this replacement does not happen and this is why shiny complains that object V1 is missing.

Here are the two lines of code that fix the problem (run them before you run order_cells():
rownames(cds@principal_graph_aux[['UMAP']]$dp_mst) <- NULL
colnames(cds@reducedDims$UMAP) <- NULL

This error is caused by a function that order_cells() is calling only if you don't provide root_cells. This is why you did not get the error when you provide root_cells. As far as I can tell, the rest of the cds object is intact.

**Comment by panxiaoguang** [comment]
> cds@clusters$UMAP$partitions

Hello,my cds have two partitions ,so I always get half gray cells in my cell plot.but in the official tutorial，it said 
> Note that we we could easily do this on a per-partition basis by first grouping the cells by partition using the partitions() function. This would result in all cells being assigned a finite pseudotime.

but how can we do this?

**Comment by alexander-7** [comment]
> > cds@clusters$UMAP$partitions
> 
> Hello,my cds have two partitions ,so I always get half gray cells in my cell plot.but in the official tutorial，it said
> 
> > Note that we we could easily do this on a per-partition basis by first grouping the cells by partition using the partitions() function. This would result in all cells being assigned a finite pseudotime.
> 
> but how can we do this?

I am not a monocle-expert, but here is my understanding of this issue: When you run order_cells() you need to choose one root for each partition. Otherwise, the partition you did not choose is not assigned any pseudotime value and will stay gray. If you want to assign pseudotime to all cells based on a single root, you need to run learn_graph with use_partition = F.

**Comment by brgew** [comment]
Hi,

We made some changes to Monocle3 to try to fix the problems related to running learn_graph(use_partition=FALSE) and my tests suggest that the changes are working. I pushed the changes to the Monocle3 develop repository branch on GitHub: it looks like you can install that branch using the command

devtools::install_github("cole-trapnell-lab/monocle3", ref="develop")

I am eager to hear whether or not this works for others.

**Comment by hpliner** [comment]
Believe this is fixed, if not, please reopen

**Comment by liuyifang** [comment]
based on previous comments, the two lines of code work for me if I manually replaced UMAP

```R
rownames(cds@principal_graph_aux[["UMAP"]]$dp_mst) <- NULL
# colnames(cds@reducedDims$UMAP) <- NULL
colnames(cds@int_colData@listData$reducedDims@listData$UMAP) <- NULL
```

**Comment by nebulia37** [comment]
Here is my code: expre_matrix=seuratObj[["RNA"]]$counts
cell_metadata=seuratObj@meta.data
gene_annotation=data.frame(gene_short_name=rownames(seuratObj[["RNA"]]$counts))
rownames(gene_annotation)=rownames(seuratObj[["RNA"]]$counts)

cds <- new_cell_data_set(expre_matrix,
                         cell_metadata = cell_metadata,
                         gene_metadata = gene_annotation)

# Provide the path to the Cell Ranger output.
cds <- preprocess_cds(cds, num_dim = 30)

# tsne
cds <- reduce_dimension(cds, preprocess_method = 'PCA', reduction_method="tSNE")
# umap
cds <- reduce_dimension(cds, preprocess_method = 'PCA', reduction_method="UMAP")
# cluster
cds <- cluster_cells(cds, resolution=1e-5)
# partition

cds <- learn_graph(cds, use_partition = F)

# 5. Order cells (compute pseudotime)
cds <- order_cells(cds, reduction_method = "UMAP")

# 6. Inspect results
summary(colData(cds)$pseudotime)               

But there is no pseudotime generated.

**Comment by nebulia37** [comment]
Anyone could help me with this? 
Here is the cds information:
cds
class: cell_data_set 
dim: 18654 68450 
metadata(2): cds_version citations
assays(1): counts
rownames(18654): Xkr4 Rp1 ... Dnaaf6b Samt4
rowData names(1): gene_short_name
colnames(68450): AAACAAGCAAAGAACAAACGGGAA-1_1 AAACAAGCAAAGAACAACTTTAGG-1_1 ... TTTGTGAGTTAATCCAAGTAGGCT-1_3
  TTTGTGAGTTGTCCAGACTTTAGG-1_3
colData names(14): orig.ident nCount_RNA ... cell_type Size_Factor
reducedDimNames(3): PCA tSNE UMAP
mainExpName: NULL
altExpNames(0):
