### ISSUE TITLE
Plot_pseudotime_heatmap() in monocle3

### ISSUE THREAD

**Issue by dwucsf** [cole-trapnell-lab/monocle3#133]
Are there plans to include the function plot_pseudotime_heatmap() in monocle3? I know version 2.99.3 has it, but I was wondering if you were planning to incorporate this capability into your newest version? Thanks!

**Comment by ctrapnell** [comment]
There are no plans to add plot_pseudotime_heatmap in the current roadmap. These functions don't accomodate trajectories with many branches well and we are still kicking around ideas for better ways to handle them in heatmap style plots.

**Comment by ashuchawla** [comment]
I am a bioinformatician and work with some experimentalists to help analyze their data. Some of my team members are really interested in **plot_pseudotime_heatmap** generated heatmaps and are asking me to downgrade from Monocle3 to Monocle2 to be able to generate these heatmaps. Would you recommend that move or is there any way I could do those with Monocle3?

Thanks,
Ashu

**Comment by RajneeshSrivastava** [comment]
Hi Dr. Trapnell, 
I am wondering if there is any update/alternative for the heatmap function in monocle3.
Many thanks,
Rajneesh

**Comment by Sophia409** [comment]
I am also wondering if there is any update for the heatmap. @ctrapnell
