### ISSUE TITLE
Should I choose monocle 2 or 3 alpha or 3 (the latest Beta release)?

### ISSUE THREAD

**Issue by Sophia409** [cole-trapnell-lab/monocle3#135]
Hello, @ctrapnell 
I just want to start a monocle analysis on a five time-course mouse single-cell RNA-seq data set. Wondering at the current stage, should I use monocle 2 or 3 alpha or 3 (the latest Beta release)?Which is more recommended?
 I expected 3 should be better than 2.But monocle 3 Beta version is still in development,and it has many bugs remained to be improve.And in my result,the disjoint trajectory seems unsharp and not as clear as monocle2.It's hard to see the obvious path as monocle2.So I'm really confused if I should choose monole3.Many thanks for any suggestions.
![图片](https://user-images.githubusercontent.com/30619010/60037603-90f20200-96e4-11e9-812c-7dbb6894e0a6.png)
![图片](https://user-images.githubusercontent.com/30619010/60037644-aebf6700-96e4-11e9-9a1c-395d39471d49.png)

**Comment by hpliner** [comment]
Thank you for using Monocle 3. 

This report appears to be a question rather than a bug or feature request. Please post your question to the Monocle 3 user group here: https://groups.google.com/forum/#!forum/monocle-3-users so that we and the community can address it! If you believe this is a bug/feature request and was closed in error, please reopen.

- Monocle 3 developers

**Comment by Sophia409** [comment]
@hpliner Hello,the forum you shared is not availabe.Does it is open to users now?

**Comment by hpliner** [comment]
The forum should be open, and as far as I can tell, people are able to access it

**Comment by BrianLohman** [comment]
This is a fair question which has not been resolved. Would you consider expanding the "Major updates in Monocle 3" section of the documentation? Monocle 2 and 3 are much more different than the limited bullet points let on.

**Comment by ashuchawla** [comment]
@Sophia409 , were you able to get an answer? I have the same issue.
