### ISSUE TITLE
How to obtain a permission to post a Monocle3 google User Group ? 

### ISSUE THREAD

**Issue by akhst7** [cole-trapnell-lab/monocle3#141]
Trying to post some question but I apparently  need a permission to post questions.  How can obtain it or can this be open ?

**Comment by hpliner** [comment]
I believe it's open and looks like you found a way - I think maybe this is a better link to get there:
https://groups.google.com/d/forum/monocle-3-users

**Comment by dwucsf** [comment]
Can you explain how you joined @akhst7? I'm having the same problem. When I click on the link that @hpliner provided, I get a box that says: "This group either doesn't exist, or you don't have permission to access it. If you're sure this group exists, contact the Owner of the group and ask them to give you access." 

I can't find a way to request permission to join the group.

**Comment by akhst7** [comment]
@hpliner 

To follow up on my previous question,  has any question being asked in the google group ? I clicked on the link you gave me and It appears to be active but I have not seen any sort of correspondence at all.

**Comment by hpliner** [comment]
Hi, can you try again? I'm not sure why some people can post and others can't, but i'm playing with the settings. There are about 10 initial posts with a few responses each on average, so you should see stuff.

**Comment by akhst7** [comment]
@hpliner 

Now I see all the postings.   Thanks.

**Comment by dwucsf** [comment]
Same. Thank you!
