### ISSUE TITLE
What parameters can I use to make the points closer to the main skeleton? 

### ISSUE THREAD

**Issue by mzhoufulai** [cole-trapnell-lab/monocle3#143]
Hi, in monocle2 we can set param.gamma bigger to make the points closer to the main skeleton, but I don't know what parameters in monocle3 can do the same thing?

Thanks

**Comment by ctrapnell** [comment]
There isn't a direct analog of param.gamma in monocle3, but you may have some luck by modifying the `umap.min_dist` parameter in `reduce_dimension()`.

Also please remember to post questions on the google group, not here.
