### ISSUE TITLE
Error in replacing the exprs cds matrix value

### ISSUE THREAD

**Issue by Sophia409** [cole-trapnell-lab/monocle3#148]
@ctrapnell 
Hi, thank you for your team's wonderful work.
I imported Seurat3 integrated data to monocle to do pseudotime analysis.But the integrated normalized data can only be used to do pseudotime analysis ,not available for any comparison in different conditons.(https://github.com/satijalab/seurat/issues/1674#issuecomment-502133415). Besides,the normalized data cause some errors in some function(such as plot_pseudotime_heatmap),because it onle accept the raw counts.
**In fact,two assay (just like seurat3)can solve this problem,but monocle2 has no this function**.
So I want to replace exprs(cds) with raw counts after ordercells.Then I can plot genes pseudotime dynamics among different branches and states without altering these branches and states information built on the integrated data.
I got raw counts from seurat object and tried to replace exprs(monocle cds),but it failed.Below is my error and sesssioninfo.**Could you show me the right code or function to replace the exprs value?Thanks a lot.**

```
exprs(cds) <- opcpath@assays$RNA@data[opcpath@assays$integrated@var.features,]
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘exprs<-’ for signature ‘"CellDataSet", "dgCMatrix"
> dim(opcpath@assays$RNA@data[opcpath@assays$integrated@var.features,])
[1]  2000 10731
> dim(exprs(opc.tdcds))
[1]  2000 10731
> class(opcpath@assays$RNA@data[opcpath@assays$integrated@var.features,])
[1] "dgCMatrix"
attr(,"package")
[1] "Matrix"
> class(exprs(opc.tdcds))
[1] "dgCMatrix"
attr(,"package")
[1] "Matrix"
```
> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936  LC_CTYPE=Chinese (Simplified)_China.936    LC_MONETARY=Chinese (Simplified)_China.936
[4] LC_NUMERIC=C                               LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
 [1] splines   stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] plyr_1.8.4          dplyr_0.8.1         cowplot_0.9.4       monocle_2.12.0      DDRTree_0.1.5       irlba_2.3.3         VGAM_1.1-1         
 [8] ggplot2_3.2.0       Biobase_2.44.0      BiocGenerics_0.30.0 Matrix_1.2-17       Seurat_3.0.2        umap_0.2.2.0       

loaded via a namespace (and not attached):
 [1] tsne_0.1-3           nlme_3.1-139         bitops_1.0-6         matrixStats_0.54.0   httr_1.4.0           RColorBrewer_1.1-2  
 [7] docopt_0.6.1         sctransform_0.2.0    tools_3.6.0          R6_2.4.0             KernSmooth_2.23-15   lazyeval_0.2.2      
[13] colorspace_1.4-1     withr_2.1.2          npsurv_0.4-0         tidyselect_0.2.5     gridExtra_2.3        compiler_3.6.0      
[19] plotly_4.9.0         labeling_0.3         slam_0.1-45          caTools_1.17.1.2     scales_1.0.0         lmtest_0.9-37       
[25] proxy_0.4-23         pbapply_1.4-0        ggridges_0.5.1       stringr_1.4.0        digest_0.6.19        sparsesvd_0.1-4     
[31] R.utils_2.9.0        htmltools_0.3.6      pkgconfig_2.0.2      bibtex_0.4.2         limma_3.40.2         htmlwidgets_1.3     
[37] rlang_0.3.4          rstudioapi_0.10      FNN_1.1.3            zoo_1.8-6            combinat_0.0-8       jsonlite_1.6        
[43] ica_1.0-2            gtools_3.8.1         R.oo_1.22.0          magrittr_1.5         Rcpp_1.0.1           munsell_0.5.0       
[49] ape_5.3              reticulate_1.12      viridis_0.5.1        R.methodsS3_1.7.1    stringi_1.4.3        yaml_2.2.0          
[55] gbRd_0.4-11          MASS_7.3-51.4        gplots_3.0.1.1       Rtsne_0.15           grid_3.6.0           gdata_2.18.0        
[61] listenv_0.7.0        ggrepel_0.8.1        crayon_1.3.4         lattice_0.20-38      SDMTools_1.1-221.1   pillar_1.4.1        
[67] igraph_1.2.4.1       future.apply_1.3.0   reshape2_1.4.3       codetools_0.2-16     glue_1.3.1           lsei_1.2-0          
[73] metap_1.1            data.table_1.12.2    png_0.1-7            Rdpack_0.11-0        tidyr_0.8.3          gtable_0.3.0        
[79] RANN_2.6.1           purrr_0.3.2          future_1.13.0        assertthat_0.2.1     rsvd_1.0.1           survival_2.44-1.1   
[85] qlcMatrix_0.9.7      HSMMSingleCell_1.4.0 viridisLite_0.3.0    tibble_2.1.3         pheatmap_1.0.12      cluster_2.0.8       
[91] fastICA_1.2-1        densityClust_0.3     globals_0.12.4       fitdistrplus_1.0-14  ROCR_1.0-7

**Comment by Sophia409** [comment]
@hpliner  Hello,is there any solution to replace the exprs cds matrix value with orignal RNA counts after ordercells based on integrated matrix?It's really important and tricky to me.Hope to your help！

**Comment by ctrapnell** [comment]
By design (of the SingleCellExperiment container from Bioconductor), this is not possible. Expression data is meant to be immutable. Once you create a cell_data_set, the SingleCellExperiment base class from which it derives won't let you change the expression data. This is to prevent functions from accidentally and silently modifying the data. 

If you want to update expression data (e.g.) , you will need to create a new matrix, and then create a new cell_data_set object from it.

**Comment by Sophia409** [comment]
@ctrapnell Hello,thank you for your reply.Though we can't change the expression data,I have another idea.
First ,I have to say tha I have compared the both methods to do pseodotime analysis.One is by importing Seurat batch corrected integrated data to monocle,the other is to use orinal expression data to monocle and do batch corrected through the fuction  fullModelFormulaStr. But it's obvious that the result that ordered by Seurat corrected  data（the first picture） is better and conform to reality.The trajectory orderred by  fullModelFormulaStr corrected data is non-ideal(the second picture). 
 But it's really a shame that if I use Seurat batch corrected data to ordercells,I can't get gene expression dynamic picture,including genes_branched_pseudotime and genes_branched_heatmap.So I'm wondering if I can extract pseudotime coordinates from pData(or named metadata,and export it to other package to do these plots.I can add the pseudotime metadata information to Seurat object which has tha original expression data),but this package can't be used to do pseudotime plot.
I'm really confused and troubled.Hope your help.
![图片](https://user-images.githubusercontent.com/30619010/61730592-49769880-adac-11e9-83a9-d45b12bba2c0.png)
![图片](https://user-images.githubusercontent.com/30619010/61730663-6ca14800-adac-11e9-95da-bdeedf07685a.png)

**Comment by veravevo** [comment]
Hi @ctrapnell, thank you for your amazing work! I really like using the Monocle2-package, and it gives great results, reflecting experimentally confirmed trajectories very well.

I am having the same issue as @Sophia409. I have an integrated Seurat-object, in which integration for batch correction is crucial  and could not be sufficiently be performed by Monocle2. By importing the "integrated"-slot into the CellDataSet to perform trajectory analysis, I got a very reasonable trajectory result. However, I cannot perform analysis of pseudotime-dependent genes or branch analysis, and plotting single genes onto the trajectory also gives unsatisfying results. 

As @Sophia409 said, the solutions that came to my mind would either be to either put RNA-count values into the CDS after trajectory construction (which seems to be impossible), to store two assays in the CDS like in the Seurat-object, or to be able to export the trajectory dimensional reduction values back into the original Seurat object.

Is there any solution to this yet?
Thank you very much, cheers, Vera

**Comment by paulang96** [comment]
Hi @Sophia409 
I am having similar issues as everyone here. Could you share how you imported Seurat integrated data to monocle? (how did you create the cds object). I can't sem to get Monocle to use the integrated assay, so my trajectories are not correct. 
Thanks!

**Comment by steachhr** [comment]
@Sophia409 @veravevo I've been having similar issues with the plot_pseudotime_heatmap. 
Have you guys had any luck with this strategy? If you have tips on how to create a new CDS and add in the pseudotime data that would be really helpful!! Thanks

**Comment by cstill1992** [comment]
Hey guys,

So I had a similar problem where I wanted to use my integrated assay for the initial dimensional reduction and creating the trajectory/pseudotime map but then use my normalized RNA assay for assessing gene expression stuff. What seemed to work for me was:

1) Make the cds object and create the trajectory using the integrated assay
2) Create a second cds object but this time for the RNA assay in the expression_data slot
3) Copy over certain parts of the cds object created from the RNA assay into the cds object created from the integrated assay

See example code below:

`#Load in the library
library(monocle3)

#I also loaded in the relevant cell_metadata and gene_metadata but 
#don't show that here

#Here I use my integrated assay as the expression_matrix
expression_matrix <- X.combined@assays$integrated@data

cds_from_seurat <- new_cell_data_set(expression_matrix,
                                     cell_metadata = cell_metadata,
                                     gene_metadata = gene_annotation)


#Now processing
cds_from_seurat = preprocess_cds(cds_from_seurat, num_dim = 100,
                                 norm_method = 'none')
cds_from_seurat <- reduce_dimension(cds_from_seurat)
cds_from_seurat = cluster_cells(cds_from_seurat)
cds_from_seurat <- learn_graph(cds_from_seurat, use_partition = FALSE)
cds_from_seurat <- order_cells(cds_from_seurat)

#Now I have my pseudotime/trajectory done using the integrated assay

#Below I mae another cell_data_set object but this time using the RNA assay for the 
#expression matrix. I also have to adjust the gene_metadata.
gene_annotation <- as.data.frame(rownames(X.combined@assays$RNA))
colnames(gene_annotation) <- "gene_short_name"
rownames(gene_annotation) <- gene_annotation$gene_short_name

RNA_from_seurat <- new_cell_data_set(X.combined@assays$RNA@data,
                                     cell_metadata = cell_metadata,
                                     gene_metadata = gene_annotation)

cds_test <- cds_from_seurat

cds_test@assays <- RNA_from_seurat@assays
cds_test@elementMetadata <- RNA_from_seurat@elementMetadata
cds_test@int_elementMetadata <- RNA_from_seurat@int_elementMetadata
cds_test@rowRanges <- RNA_from_seurat@rowRanges

#cds_test now maintains the trajectory constructed using the integrated assay
#but contains expression data from the RNA assay.`

Please note I've only really tested this works with the plot_cells function by using a gene I know is present in my RNA assay dataframe but not the integrated assay dataframe. Let me know how it works for you guys.
