### ISSUE TITLE
Single-cell cyTOF data loading error

### ISSUE THREAD

**Issue by wy-18** [cole-trapnell-lab/monocle3#151]
Dear monocle-3 Team,

Thank you for this package, we would like to run monocle3 by using cyTOF data. The error occurred as we tried to load our data in the form of csv,  which is an expression matrix.

The code that produced the bug:
cds = read.csv("T003PI0_allcell_processed.csv", header = TRUE)
cds <- preprocess_cds(cds, num_dim =30 , residual_model_formula_str = "~ batch")

The screenshots of the error:

![Screen Shot 2019-07-12 at 5 00 02 PM](https://user-images.githubusercontent.com/52818723/61116180-84342300-a4c6-11e9-8e07-031630bdbfb5.png)

Could you please help us to figure out how we could use monocle 3 to deal with CyTOF single cell data. 

As a second idea: if we only want to load the expression matrix without metadata, how can we load and process it?

Thank you very much!
Cathy

**Comment by hpliner** [comment]
Hi Cathy,

In order to create a cds, you need to use the new_cell_data_set function. Please read the docs here: https://cole-trapnell-lab.github.io/monocle3/monocle3_docs/#the-cell-data-set-class for more information
