### ISSUE TITLE
having difficulty choosing root nodes in order_cells with the root_pr_nodes 

### ISSUE THREAD

**Issue by sanjayrsrivatsan** [cole-trapnell-lab/monocle3#154]
**Describe the bug**
passing a set of root nodes to order_cells does not seem to work.

I get the following error -

> igraph::V(principal_graph(cds)[["UMAP"]])$name %>% class()
[1] "character"
> cds <- order_cells(cds, root_pr_nodes=root_nodes)
Error: All provided root_pr_nodes must be present in the principal graph.
> root_nodes %>% class()
[1] "numeric"
> root_nodes = paste0("Y_",root_nodes, sep = "")
>
> root_nodes %>% class()
[1] "character"
> pData(cds)$root_node = pData(cds)$closest_vertex %in% root_nodes
> cds <- order_cells(cds, root_pr_nodes=root_nodes)
Error in as.igraph.vs(graph, v) : Invalid vertex names

**Comment by hpliner** [comment]
@ctrapnell Is this good now?

**Comment by ctrapnell** [comment]
Yeah I would have thought my commit message would have auto closed it sorry

**Comment by stephanyfoster** [comment]
Hello!
I also receive this error (Error: All provided root_pr_nodes must be present in the principal graph.) 
when I run root <-c('35')
cds <- order_cells(cds,root_pr_nodes = root)

Apologies if this is a basic question--new here haha, thanks!
