### ISSUE TITLE
Issue in Monocle3 tutorial (Graph-autocorrelation analysis for comparing clusters)

### ISSUE THREAD

**Issue by lampoona** [cole-trapnell-lab/monocle3#155]
Hi, 
I'm going through the differential expression analysis. 
To run this line: neurons_cds = cds[,colData(cds)$assigned_cell_type == "Neurons"], 
you get an error because the cds for the worm dataset does not have assigned_cell_type. So you get no cells, so NA. Can you add that to the cds or to the tutorial? It's there for Jun's data, but not Jonathan's (worm). 

Thanks!
Sayeh

**Comment by ctrapnell** [comment]
Will do. Thanks!
