### ISSUE TITLE
Issue with importCDS function

### ISSUE THREAD

**Issue by vitamindlab** [cole-trapnell-lab/monocle3#159]
I am attempting to import a Seurat object(Seurat v3) using Monocle 3. The "importCDS(data_to_be_imported)" function is giving an error "could not find function "importCDS"". Is this function not compatible with Monocle3? If not what is the new command for importing Seurat v3 objects?

**Comment by JosephEDuke-Cohan** [comment]
1) I think importCDS() is a monocle2 function and isn't found within monocle3 yet. I haven't found an alternative for importCDS().
2) Importing a Seurat object to monocle only works if the Seurat object was built under Seurat V2; you may find it tricky to do with Seurat V3.

**Comment by JosephEDuke-Cohan** [comment]
You can also extract the individual elements of the Seurat object manually if you'd like:

#Extract count data, phenotype data, and feature data from the Seurat Object.
counts.data <- as(as.matrix(Seurat.object@assays$RNA@data), 'sparseMatrix')
pheno.data <- new('AnnotatedDataFrame', data = Seurat.object@meta.data)
feature.data <- data.frame(gene_short_name = row.names(counts.data), row.names = row.names(counts.data))
feature.data <- new('AnnotatedDataFrame', data = feature.data)

#Construct a CellDataSet.
cds <- newCellDataSet(counts.data, phenoData = pheno.data, featureData = feature.data, lowerDetectionLimit = 0.5, expressionFamily = negbinomial.size())

**Comment by hpliner** [comment]
You are correct @JosephEDuke-Cohan that importCDS is not implemented in monocle3. We are still considering how best to allow interoperability between monocle3 and seurat. In the meantime, I recommend using the method posted above (though using new_cell_data_set instead of newCellDataSet which is monocle2)
