### ISSUE TITLE
Strange behavior in graph_test when neighbor_graph = 'principal graph'

### ISSUE THREAD

**Issue by Connorr0** [cole-trapnell-lab/monocle3#164]
** If this is a question and not a bug report or enhancement request, please post to our google group at https://groups.google.com/forum/#!forum/monocle-3-users**

**Describe the bug**

Currently my graph_test output is acting strange I am getting the following printed to console (lowest code chunk.) I suspect that at the least there is an issue with the script for writing the progress bar; however I am also not sure about the origin of the "the condition has length > 1 and only the first element will be usedNegative variance," message. As far as I can tell everything seems imported properly and I get a populated dataframe (containing a lot of FAILED, NAs, and NANs), but I am working with a small subset of cells. The excessive printing does not appear to be a problem when I run this in the console, only when run in a markdown cell. 

frame head:
![image](https://user-images.githubusercontent.com/29585780/61752288-0262b600-ad60-11e9-9360-f35e39f0a168.png)

console output:
*ETA is not accurate possibly due to printing lines
`  |                                                                                                                                         |   0%, ETA NAthe condition has length > 1 and only the first element will be usedNegative variance,
  |                                                                                                                                      |   0%, ETA 04:40the condition has length > 1 and only the first element will be usedNegative variance,
  |                                                                                                                                      |   0%, ETA 05:54the condition has length > 1 and only the first element will be usedNegative variance,
  |                                                                                                                                      |   0%, ETA 05:24the condition has length > 1 and only the first element will be usedNegative variance,
  |                                                                                                                                      |   0%, ETA 05:23the condition has length > 1 and only the first element will be usedNegative variance,
  |                                                                                                                                      |   0%, ETA 05:19the condition has length > 1 and only the first element will be usedNegative variance,
  |                                                                                                                                      |   0%, ETA 05:15the condition has length > 1 and only the first element will be usedNegative variance,
  |                                                                                                                                      |   0%, ETA 05:16the condition has length > 1 and only the first element will be usedNegative variance,`

**To Reproduce**
The code that produced the bug:

PSTim_graph_test_res = graph_test(cds_subset, neighbor_graph="principal_graph")

**traceback()**
After the error, run traceback() in R and post the output:

> > PSTim_graph_test_res = graph_test(cds_subset, neighbor_graph="principal_graph")
>   |===========================================================================================================================================| 100%, Elapsed 05:33There were 50 or more warnings (use warnings() to see the first 50)
> > traceback()
> 8: eval(quote(list(...)), env)
> 7: eval(quote(list(...)), env)
> 6: eval(quote(list(...)), env)
> 5: standardGeneric("order")
> 4: order(q_value)
> 3: `[.data.frame`(pr_graph_test_res, order(q_value), )
> 2: pr_graph_test_res[order(q_value), ]
> 1: subset(pr_graph_test_res[order(q_value), ], q_value < 0.05)

**Expected behavior**

no warnings, single line progress bar

**Screenshots**

**sessionInfo():**
Run sessionInfo() in R and post the output

 

> Packages ----------------------------------------------------------------------------------------------------------------------------------------------
>  package              * version   date       lib source                                     
>  assertthat             0.2.1     2019-03-21 [1] CRAN (R 3.6.1)                             
>  backports              1.1.4     2019-04-10 [1] CRAN (R 3.6.0)                             
>  Biobase              * 2.44.0    2019-05-02 [1] Bioconductor                               
>  BiocGenerics         * 0.30.0    2019-05-02 [1] Bioconductor                               
>  BiocParallel         * 1.17.18   2019-03-24 [1] Bioconductor                               
>  bitops                 1.0-6     2013-08-17 [1] CRAN (R 3.6.0)                             
>  callr                  3.3.1     2019-07-18 [1] CRAN (R 3.6.1)                             
>  cli                    1.1.0     2019-03-19 [1] CRAN (R 3.6.1)                             
>  colorspace             1.4-1     2019-03-18 [1] CRAN (R 3.6.1)                             
>  crayon                 1.3.4     2017-09-16 [1] CRAN (R 3.6.1)                             
>  DelayedArray         * 0.10.0    2019-05-02 [1] Bioconductor                               
>  desc                   1.2.0     2018-05-01 [1] CRAN (R 3.6.1)                             
>  devtools             * 2.1.0     2019-07-06 [1] CRAN (R 3.6.1)                             
>  digest                 0.6.20    2019-07-04 [1] CRAN (R 3.6.1)                             
>  dplyr                * 0.8.3     2019-07-04 [1] CRAN (R 3.6.1)                             
>  fs                     1.3.1     2019-05-06 [1] CRAN (R 3.6.1)                             
>  garnett              * 0.2.2     2019-07-19 [1] Github (cole-trapnell-lab/garnett@0bd9550) 
>  GenomeInfoDb         * 1.20.0    2019-05-02 [1] Bioconductor                               
>  GenomeInfoDbData       1.2.1     2019-07-18 [1] Bioconductor                               
>  GenomicRanges        * 1.36.0    2019-05-02 [1] Bioconductor                               
>  ggplot2              * 3.2.0     2019-06-16 [1] CRAN (R 3.6.0)                             
>  glue                   1.3.1     2019-03-12 [1] CRAN (R 3.6.1)                             
>  gridExtra              2.3       2017-09-09 [1] CRAN (R 3.6.1)                             
>  gtable                 0.3.0     2019-03-25 [1] CRAN (R 3.6.1)                             
>  igraph                 1.2.4.1   2019-04-22 [1] CRAN (R 3.6.1)                             
>  IRanges              * 2.18.1    2019-05-31 [1] Bioconductor                               
>  knitr                  1.23      2019-05-18 [1] CRAN (R 3.6.1)                             
>  lattice                0.20-38   2018-11-04 [2] CRAN (R 3.6.1)                             
>  lazyeval               0.2.2     2019-03-15 [1] CRAN (R 3.6.1)                             
>  magrittr               1.5       2014-11-22 [1] CRAN (R 3.6.1)                             
>  Matrix                 1.2-17    2019-03-22 [2] CRAN (R 3.6.1)                             
>  matrixStats          * 0.54.0    2018-07-23 [1] CRAN (R 3.6.1)                             
>  memoise                1.1.0     2017-04-21 [1] CRAN (R 3.6.1)                             
>  monocle3             * 0.1.2     2019-07-18 [1] Github (cole-trapnell-lab/monocle3@e212173)
>  munsell                0.5.0     2018-06-12 [1] CRAN (R 3.6.1)                             
>  pillar                 1.4.2     2019-06-29 [1] CRAN (R 3.6.1)                             
>  pkgbuild               1.0.3     2019-03-20 [1] CRAN (R 3.6.1)                             
>  pkgconfig              2.0.2     2018-08-16 [1] CRAN (R 3.6.1)                             
>  pkgload                1.0.2     2018-10-29 [1] CRAN (R 3.6.1)                             
>  plyr                   1.8.4     2016-06-08 [1] CRAN (R 3.6.1)                             
>  prettyunits            1.0.2     2015-07-13 [1] CRAN (R 3.6.1)                             
>  processx               3.4.0     2019-07-03 [1] CRAN (R 3.6.1)                             
>  ps                     1.3.0     2018-12-21 [1] CRAN (R 3.6.1)                             
>  purrr                  0.3.2     2019-03-15 [1] CRAN (R 3.6.1)                             
>  R6                     2.4.0     2019-02-14 [1] CRAN (R 3.6.1)                             
>  Rcpp                   1.0.1     2019-03-17 [1] CRAN (R 3.6.0)                             
>  RCurl                  1.95-4.12 2019-03-04 [1] CRAN (R 3.6.0)                             
>  remotes                2.1.0     2019-06-24 [1] CRAN (R 3.6.1)                             
>  reshape2               1.4.3     2017-12-11 [1] CRAN (R 3.6.1)                             
>  rlang                  0.4.0     2019-06-25 [1] CRAN (R 3.6.1)                             
>  rprojroot              1.3-2     2018-01-03 [1] CRAN (R 3.6.1)                             
>  rstudioapi             0.10      2019-03-19 [1] CRAN (R 3.6.1)                             
>  S4Vectors            * 0.22.0    2019-05-02 [1] Bioconductor                               
>  scales                 1.0.0     2018-08-09 [1] CRAN (R 3.6.1)                             
>  sessioninfo            1.1.1     2018-11-05 [1] CRAN (R 3.6.1)                             
>  SingleCellExperiment * 1.6.0     2019-05-02 [1] Bioconductor                               
>  stringi                1.4.3     2019-03-12 [1] CRAN (R 3.6.0)                             
>  stringr                1.4.0     2019-02-10 [1] CRAN (R 3.6.1)                             
>  SummarizedExperiment * 1.14.0    2019-05-02 [1] Bioconductor                               
>  testthat               2.1.1     2019-04-23 [1] CRAN (R 3.6.1)                             
>  tibble                 2.1.3     2019-06-06 [1] CRAN (R 3.6.1)                             
>  tidyselect             0.2.5     2018-10-11 [1] CRAN (R 3.6.1)                             
>  usethis              * 1.5.1     2019-07-04 [1] CRAN (R 3.6.1)                             
>  viridis                0.5.1     2018-03-29 [1] CRAN (R 3.6.1)                             
>  viridisLite            0.3.0     2018-02-01 [1] CRAN (R 3.6.1)                             
>  withr                  2.1.2     2018-03-15 [1] CRAN (R 3.6.1)                             
>  xfun                   0.8       2019-06-25 [1] CRAN (R 3.6.1)                             
>  XVector                0.24.0    2019-05-02 [1] Bioconductor                               
>  zlibbioc               1.30.0    2019-05-02 [1] Bioconductor

**Additional context**

**Comment by brgew** [comment]
Hi,
You see warnings produced by the Moran's I code interspersed with the progress bar because both the progress bar text and the warnings are displayed in the same window/widget. I don't know why you do not see similar interspersions when you run in the console...are you running on the same data set in both cases?
The cause of the warnings is a separate issue and may be a result of having 'a lot of FAILED, NAs, and NANs'. R interprets NA as a missing value and NaN as an impossible value but I don't know what it does with FAILED. You may try converting FAILED values to NA.
Best Wishes,
Brent
