### ISSUE TITLE
AFD_lineage_cds does not appear to be called before use in getting started page

### ISSUE THREAD

**Issue by Connorr0** [cole-trapnell-lab/monocle3#165]
** If this is a question and not a bug report or enhancement request, please post to our google group at https://groups.google.com/forum/#!forum/monocle-3-users**

Not sure if this is the correct place to post this

**Describe the bug**

Possible mistake on monocle 3 getting started page:
`object AFD_lineage_cds not found`

**To Reproduce**
The code that produced the bug:
```
AFD_genes = c("gcy-8", "dac-1", "oig-8")
AFD_lineage_cds = cds[rowData(AFD_lineage_cds)$gene_short_name %in% AFD_genes,
                      clusters(cds) %in% c(22, 28, 35)]
```

**traceback()**
After the error, run traceback() in R and post the output:

**Expected behavior**
Object does not appear predefined

**Screenshots**

**sessionInfo():**
Run sessionInfo() in R and post the output

**Additional context**

I suspect the fix is:
`AFD_genes = c("gcy-8", "dac-1", "oig-8")
AFD_lineage_cds = cds[rowData(cds)$gene_short_name %in% AFD_genes,
                      clusters(cds) %in% c(22, 28, 35)]`

much like:
`cds_subset = cds[rowData(cds)$gene_short_name %in% ciliated_genes,]`

**Comment by hpliner** [comment]
This was a typo in the website and has been fixed. Thanks for the report!
