### ISSUE TITLE
Inconsistent distribution of UMAP maps！

### ISSUE THREAD

**Issue by pengpengyang94** [cole-trapnell-lab/monocle3#169]
The `RunUMAP` function in `Seurat` has the `set.seed` parameter to set the random seed of UMAP.
In the `reduce_dimension` function in `monocle3`, I didn't find the parameters to set the random seed, which would lead me to get a variety of UMAP graphical results. I want to get a repeatable result, how can I set it up?

**Comment by hpliner** [comment]
In order to get consistent results, you need to set umap.fast_sgd = FALSE. This causes the algorithm to run slower on large datasets, but will make the results consistent across runs.

**Comment by hpliner** [comment]
(And thanks for transferring to the monocle3 repo, helps future users not get confused by the different packages!)

**Comment by pengpengyang94** [comment]
Thank you very much for your reply, this is what I should do.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Hannah A Pliner <notifications@github.com>
发送时间: Tuesday, July 30, 2019 12:49:11 PM
收件人: cole-trapnell-lab/monocle3 <monocle3@noreply.github.com>
抄送: pengpeng yang <yangpengpeng.1993@live.com>; Author <author@noreply.github.com>
主题: Re: [cole-trapnell-lab/monocle3] Inconsistent distribution of UMAP maps！ (#169)


(And thanks for transferring to the monocle3 repo, helps future users not get confused by the different packages!)

―
