### ISSUE TITLE
 Could not find tools necessary to compile a package

### ISSUE THREAD

**Issue by brianpenghe** [cole-trapnell-lab/monocle3#172]
I was trying to install the package by running:
`devtools::install_github('cole-trapnell-lab/monocle3')`

But I got this error:

```
Downloading GitHub repo cole-trapnell-lab/monocle3@master
Error: Failed to install 'monocle3' from GitHub:
  Could not find tools necessary to compile a package
```

Any ideas?

**Comment by hpliner** [comment]
This is probably an issue with the available compilers. If you're running on a windows machine, it looks like you can fix this by installing rtools: https://cran.r-project.org/bin/windows/Rtools/

There's a post about this here: https://stackoverflow.com/questions/37776377/error-when-installing-an-r-package-from-github-could-not-find-build-tools-neces
