### ISSUE TITLE
After installation monocle3 use, an error

### ISSUE THREAD

**Issue by Giampiero-ctrl** [cole-trapnell-lab/monocle3#173]
library(monocle3)
expression_matrix <-readRDS(url("http://staff.washington.edu/hpliner/data/cao_l2_expression.rds"))
cell_metadata <- readRDS(url("http://staff.washington.edu/hpliner/data/cao_l2_colData.rds"))
gene_annotation <- readRDS(url("http://staff.washington.edu/hpliner/data/cao_l2_rowData.rds"))
cds<- new_cell_data_set(expression_data = expression_matrix,
                         cell_metadata = cell_metadata,
                         gene_metadata = gene_annotation)

Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object 'normalize_names_replacement_value' not found

**Comment by hpliner** [comment]
Thank you for submitting a bug report. Your report has insufficient information for us to address it. Please respond with the information requested in the bug report issue template. At minimum, please include: 

1. The code you ran that generated the error - OK
2. The output of the call - and what was expected - OK
3. The output of traceback()
4. The output of sessionInfo()

We will close this issue - when you answer with this further information, please reopen the issue.

- Monocle3 Dev Team
