### ISSUE TITLE
Why rge_method  parameter of learnGraph function is not found in monocle3 Beta

### ISSUE THREAD

**Issue by Sophia409** [cole-trapnell-lab/monocle3#174]
@ctrapnell @Loyale @hpliner Hello,
When I use monocle3 default parameters to plot_cell_trajectory , I got a not fully connected and ugly graph, as picture 1. The disjoint trajectory seems unsharp and not as clear as monocle2.It's hard to see the obvious path as monocle2.In[ this post](https://github.com/cole-trapnell-lab/monocle-release/issues/272#issuecomment-470254026),someone has issued the same question.And the solution is to **set partitionCells=F and rge_method = 'DDRTree'** : learnGraph(cds, RGE_method = 'DDRTree', do_partition=FALSE).In this way, we can still get a 'fully connected' graph similar to monocle2.

But **rge_method  parameter of learnGraph function is only in monocle3 Alpha ,not monocle3 Beta**. So in monocle3 beta,I got the joint trajectory like picture2.  **How can I got a simple trajectory with no too many branchs, just similar to monocle2 (picture3)?** I can use monocle2 to do it,but because of large number of cells,the speed is very slow.So wondering how I can still choose the DDRTree method in monocle3 beta?

   By the way, I just want to do a simple not very precise analysis on a five time points mouse single-cell RNA-seq data set. Wondering at the current stage, should I use monocle2,monocle 3 alpha or the latest Beta release? I'm really confused.Many thanks for any suggestions.
picture1
![图片](https://user-images.githubusercontent.com/30619010/60037603-90f20200-96e4-11e9-812c-7dbb6894e0a6.png)
picture2
![图片](https://user-images.githubusercontent.com/30619010/62460036-75821880-b7b3-11e9-89d5-acb4331f42b1.png)
picture3
![图片](https://user-images.githubusercontent.com/30619010/62461221-c2b3b980-b7b6-11e9-9619-38255eb7e33c.png)

**Comment by elfore** [comment]
Since Monocle 2 and Monocle 3 alpha are deprecated, I will just wait for what is available now.

**Comment by ctrapnell** [comment]
To reduce the "branchyness" of your trajectories, you can adjust the ncenter parameter, like this:

`cds <- learn_graph(cds, learn_graph_control=list(ncenter=1000))`

This controls the number of graph nodes, which in turn controls how complex the tree can be.

The other thing I see going on in your plots is that you appear to be disabling the partitioning of your trajectories by passing `use_partition=FALSE`. This is not recommended in general. In our view, large gaps between partitions suggest that those cells should be part of distinct trajectories. Forcing them into one trajectory can lead to the misleading impression that there is a smooth transition (with no gaps in the data) between those cells. One of the things that makes Monocle2 better than Monocle3 is that it can detect such gaps, and split up the data appropriately. Monocle2 forces everything onto one tree, which sometimes can lead you to think your data is more continuous than it really is.

**Comment by ctrapnell** [comment]
Just to clarify, reducing ncenter typically makes the tree more smooth, but you can lose some details like small branches.

**Comment by Sayyam-Shah** [comment]
Hello @ctrapnell,

I want to increase sensitivity since I noticed monocle3 didn't draw branches between expected cell types. Would manipulating n_center be the best parameter for that? What is the default n_center value, and how much should I increase it?
