### ISSUE TITLE
Batch corrected result by  fullModelFormulaStr parameter is terrible

### ISSUE THREAD

**Issue by Sophia409** [cole-trapnell-lab/monocle3#175]
Hello,
    Thank you for your work in monocle.I imported the Seurat v3 integrated and batch corrected data to monocle and made a perfect trajectory.
    I have to say that I have compared the both methods to do pseodotime analysis.One is by importing Seurat batch corrected integrated data to monocle,the other is to use original expression data to monocle and do batch corrected through the fuction fullModelFormulaStr. But it's obvious that **the result that ordered by Seurat corrected  data（picture1,2）is much better and conform to reality**. **The trajectory orderred by  fullModelFormulaStr corrected data is terrible(picture3,4).**  
Wondering which bath corrected method is used in fullModelFormulaStr?When will you add mnnCorrect method or other better ones to preprocess_cds() to allow users to align cells from different batches? 
I'm really  troubled and look forward to your guidance. 
picture 1,2
![图片](https://user-images.githubusercontent.com/30619010/62465674-0cee6800-b7c2-11e9-85e5-5db41ba19a81.png)
![图片](https://user-images.githubusercontent.com/30619010/62465768-445d1480-b7c2-11e9-9f97-59a7a5822fb2.png)
picture 3,4
![图片](https://user-images.githubusercontent.com/30619010/62465677-1081ef00-b7c2-11e9-8a02-c87d576b0218.png)
![图片](https://user-images.githubusercontent.com/30619010/62465783-4cb54f80-b7c2-11e9-836f-577ae558d3ff.png)

**Comment by Connorr0** [comment]
I have run into the same issue.  I also wanted to say that I think that this can be especially problematic as preprocess_cds() preforms several steps at once (scaling, normalization, and PCA). So when loading in batch corrected data there does not appear to be any way to avoid normalizing and scaling twice (once before and once after batch correction) and I am not sure if this is conceptually problematic. I am currently looking into loading the PCA data directly into Monocle 3 after loading up the expression matrix but I am not sure if preprocess_cds() is changing anything else that is important to the pipeline.

**Comment by Sophia409** [comment]
Hello,
    I try both monocle3 and monocle2. And fullModelFormulaStr corrected effects is bad in either case.I guess this function did't change  in step with monocle.


On 8/13/2019 01:17，Connor Finkbeiner<notifications@github.com> wrote：

I have run into the same issue. I also wanted to say that I think that this can be especially problematic as preprocess_cds() preforms several steps at once (scaling, normalization, and PCA). So when loading in batch corrected data there does not appear to be any way to avoid normalizing and scaling twice (once before and once after batch correction) and I am not sure if this is conceptually problematic. I am currently looking into loading the PCA data directly into Monocle 3 after loading up the expression matrix but I am not sure if preprocess_cds() is changing anything else that is important to the pipeline.

**Comment by ctrapnell** [comment]
The batch correct in version 0.1.3 is linear, which doesn't always work well. If you have strong or nonlinear batch effects in your data, the linear method won't suffice and can do more harm than good. We are working on getting nonlinear correction (via the Marioni lab's batchelor package) into Monocle. It's scheduled for the 0.2.0 release, but you can try it now by checking out the "align-preprocess" branch.

**Comment by Connorr0** [comment]
Awesome thanks!

**Comment by saeedfc** [comment]
@Sophia409 If it's of any help__ I tried monocle3 and monocle2 with integrated matrices. The results were not good. my trajectory though is well known biologically. I am doing it more to get to know the genes that change along the trajectory.
What worked best for me was to merge using seurat. Normalize in suerat and then use monocle2. I avoided using any further normalization in monocle2 as adviced in this link (https://github.com/cole-trapnell-lab/monocle-release/issues/162).

Monocle 3 is not working fine for me by any means. I think I have already exhausted all possible ways to use monocle3.

I was lucky that the datasets I merged had no much batch effect between them though and had similar sequencing depths.

**Comment by sciotlos** [comment]
Hi Sophia,

I've been messing around for a bit trying to get Seurat (3) and Monocle (3) to understand each other. I'm able to load the seurat object into monocle like this:
`
expression_matrix <- merge_all_imr90@assays$RNA@counts

cells <- merge_all_imr90@meta.data[,1:5]
genes <- merge_all_imr90@assays$RNA@counts@Dimnames[[1]]
gene_df <- data.frame(ids = genes, row.names = genes)
colnames(gene_df) <- "gene_short_name"
all_imr90 <- new_cell_data_set(expression_matrix, cell_metadata = cells, gene_metadata = gene_df)
`

However I'd really like to load a fully processed/integrated/corrected Seurat object into Monocle, like you did, and I can't seem to figure out how. 

Would you mind sharing how you did this? I do not want to use data corrected through Monocle for my trajectory and DGE analyses.. thank you!

**Comment by qoiopipq** [comment]
Hi @Sophia409 @Connorr0 ,

I can import Seurat V3 object to Monocle3. However, I'm trying to import MNN corrected Seurat object to Monocle3 (v 0.1.3). As Aaron Lun suggested FastMNN() output can be directly used for any clustering/trajectory analysis.  It seems very hard to skip preprocess_cds() step and run trajectory analysis on MNN corrected, dimensional reduced matrix directly. It keeps asking to run preprocess_cds() before running any subsequent commands. Just asking would you mind showing how did you do it? 

Thanks!

**Comment by sciotlos** [comment]
> Hi @Sophia409 @Connorr0 ,
> 
> I can import Seurat V3 object to Monocle3. However, I'm trying to import MNN corrected Seurat object to Monocle3 (v 0.1.3). As Aaron Lun suggested FastMNN() output can be directly used for any clustering/trajectory analysis. It seems very hard to skip preprocess_cds() step and run trajectory analysis on MNN corrected, dimensional reduced matrix directly. It keeps asking to run preprocess_cds() before running any subsequent commands. Just asking would you mind showing how did you do it?
> 
> Thanks!

Hi @qoiopipq - 
Do you mind sharing how you imported your Seurat V3 object to Monocle3? 
Did you successfully load data that you integrated/corrected in Seurat, and were you able to build trajectories/do pseudotime analysis using that?

thank you!

**Comment by Sophia409** [comment]
hi,i imported my Seurat V3 object to Monocle2 not 3. yuhongruoyi 邮箱：yuhongruoyi@gmail.com 签名由 网易邮箱大师 定制 在2019年10月05日 05:11，sciotlos 写道： Hi @Sophia409 @Connorr0 , I can import Seurat V3 object to Monocle3. However, I'm trying to import MNN corrected Seurat object to Monocle3 (v 0.1.3). As Aaron Lun suggested FastMNN() output can be directly used for any clustering/trajectory analysis. It seems very hard to skip preprocess_cds() step and run trajectory analysis on MNN corrected, dimensional reduced matrix directly. It keeps asking to run preprocess_cds() before running any subsequent commands. Just asking would you mind showing how did you do it? Thanks! Hi @qoiopipq - Do you mind sharing how you imported your Seurat V3 object to Monocle3? Did you successfully load data that you integrated/corrected in Seurat, and were you able to build trajectories/do pseudotime analysis using that? thank you! — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by qoiopipq** [comment]
Thanks @Sophia409 

Hi @sciotlos 
The code I wrote is similar to this post #159, which is to build a new_cell_data_set() by specifying each element manually. 
I couldn't load integrated (batch corrected) data from MNN to Monocle3, since I couldn't skip preprocess_cds() dimension reduction step. However, I tired to use Slingshot to do it, which can take a matrix of cell embeddings in reduced dimension as input. My trajectory plot doesn't look quite right, I don't know if I did something incorrectly.

**Comment by ctrapnell** [comment]
@qoiopipq have you tried the new align_cds() function? It performs MNN correction on the celldataset using batchelor. 

I am closing this issue, as incorporating data that's been processed in Seurat for downstream analysis with Monocle isn't officially supported. If you'd like to hack Monocle and/or Seurat to do so, please submit questions about how to do so on the google group (https://groups.google.com/d/forum/monocle-3-users) rather than opening issues here about how to do this.
