### ISSUE TITLE
plot_pc_variance_explained does work

### ISSUE THREAD

**Issue by brianpenghe** [cole-trapnell-lab/monocle3#176]
Error: methods::is(object = cds, class2 = "cell_data_set") is not TRUE
Traceback:

1. plot_pc_variance_explained(updated_MouseLimb10X_Monocle)
2. assertthat::assert_that(methods::is(cds, "cell_data_set"))

**Comment by hpliner** [comment]
This error indicates that the class of updated_MouseLimb10X_Monocle is not a cell_data_set. Please check that you loaded your data into a cell_data_set as described in the web tutorial. You can check the class of your object using:
class(updated_MouseLimb10X_Monocle)

**Comment by brianpenghe** [comment]
Yes because it was generated by Monocle3alpha.
I'm trying to migrate to Monocle3beta. Is there a way to import my Seurat object into Monocle3beta? or convert Monocle3alpha object to Monocle3beta object?

**Comment by hpliner** [comment]
You can convert to Monocle3 beta by saving your fData, pData and exprs files and then generating a new object in monocle3, e.g.:

```
fd <- fData(cds)
pd <- pData(cds)
exp <- exprs(cds)
save(fd, file="fd")
save(pd, file="pd")
save(exp, file="exp")

# Reload R
library(monocle3)
load("fd")
load("pd")
load("exp")

new_cds <- new_cell_data_set(exp, gene_metadata = fd, cell_metadata = pd)

```

**Comment by brianpenghe** [comment]
> new_cell_data_set(exp, gene_metadata = fd, cell_metadata = pd)

Thanks but it seems that expr() isn't working. It clashes the expr from rlang package. Do you know how to solve this?

**Comment by brianpenghe** [comment]
Thanks but it gave me another error:
Error in plot_pc_variance_explained(updated_MouseLimb10X_Monocle): no slot of name "auxClusteringData" for this object of class "cell_data_set"
Traceback:

1. plot_pc_variance_explained(updated_MouseLimb10X_Monocle)
