### ISSUE TITLE
Conflicts of command when both monocle2 and monocle3 are installed

### ISSUE THREAD

**Issue by MazzzzzeLuo** [cole-trapnell-lab/monocle3#178]
** If this is a question and not a bug report or enhancement request, please post to our google group at https://groups.google.com/forum/#!forum/monocle-3-users**

**Describe the bug**
After I installed monocle 3, when I try to use monocle 2 again. An error would appear with I use command fData or pData:
unable to find an inherited method for function ‘fData’ for signature ‘"CellDataSet"’

After doing some research I realized that it is a conflict error. I solve this error by using an additional package "conflicted"  and declare to prefer "Biobase" instead of "monocle3"

**To Reproduce**
The code that produced the bug:

**traceback()**
After the error, run traceback() in R and post the output:

**Expected behavior**

**Screenshots**

**sessionInfo():**
Run sessionInfo() in R and post the output

**Additional context**

**Comment by hpliner** [comment]
Thank you for the question. Monocle3 is not intended to be loaded at the same time as monocle2. Monocle3 is meant to replace monocle2 and running them both will certainly cause namespace conflicts.
