### ISSUE TITLE
interactive mode didn't work

### ISSUE THREAD

**Issue by brianpenghe** [cole-trapnell-lab/monocle3#179]
Why didn't the interactive mode work? I'm running it on Jupyter notebook. But RStudio also couldn't make it work.

`cds=order_cells(cds)`

Error: When not in interactive mode, either root_pr_nodes or root_cells must be provided.
Traceback:

1. order_cells(cds)
2. assertthat::assert_that(interactive(), msg = paste("When not in interactive mode, either", 
 .     "root_pr_nodes or root_cells must be", "provided."))

**Comment by hpliner** [comment]
Unfortunately shiny interactive is not currently supported by IRKernel (see https://github.com/IRkernel/IRkernel/issues/236). For RStudio, are you running RStudio on a server? If so, that has the same issue as Jupyter when it comes to interactive. I recommend passing a cell using root_cells to choose your root.

**Comment by insilicolife** [comment]
> Unfortunately shiny interactive is not currently supported by IRKernel (see [IRkernel/IRkernel#236](https://github.com/IRkernel/IRkernel/issues/236)). For RStudio, are you running RStudio on a server? If so, that has the same issue as Jupyter when it comes to interactive. I recommend passing a cell using root_cells to choose your root.

I'm also facing same problem here. How do we know which of the cells are the root_cell?

**Comment by githubber58** [comment]
> Why didn't the interactive mode work? I'm running it on Jupyter notebook. But RStudio also couldn't make it work.
> 
> `cds=order_cells(cds)`
> 
> Error: When not in interactive mode, either root_pr_nodes or root_cells must be provided.
> Traceback:
> 
> 1. order_cells(cds)
> 2. assertthat::assert_that(interactive(), msg = paste("When not in interactive mode, either",
>    .     "root_pr_nodes or root_cells must be", "provided."))



Hi, would you mind sharing about the method that you use to open the interactive mode and run the code in Jupyter notebook? cuz when I wanna run the code: 

cds_subset <- choose_cells(cds)

I got:

Error: choose_cells only works in interactive mode.
Traceback:

1. choose_cells(cds)
2. assertthat::assert_that(interactive(), msg = paste("choose_cells only works in", 
 .     "interactive mode."))   # at line 15-17 of file <text>

**Comment by SilenWang** [comment]
This issue now has an solution, a new kernel [xeus-r](https://github.com/jupyter-xeus/xeus-r) support the interactive mode of R.
To start the server, you may first need to set `options(browser="firefox")`, as mentioned in issue #179. After that, you can obtain a URL, open it, and select the node.

Although this is a response five years later... Considering that the ir-kernel still does not support interactive mode to this day... and monocle3 remains one of the most commonly used single-cell tools, this response should still hold value.

**Comment by cmubioinformatics** [comment]
> This issue now has an solution, a new kernel [xeus-r](https://github.com/jupyter-xeus/xeus-r) support the interactive mode of R. To start the server, you may first need to set `options(browser="firefox")`, as mentioned in issue [#179](https://github.com/cole-trapnell-lab/monocle3/issues/179). After that, you can obtain a URL, open it, and select the node.
> 
> Although this is a response five years later... Considering that the ir-kernel still does not support interactive mode to this day... and monocle3 remains one of the most commonly used single-cell tools, this response should still hold value.

thanks very much, could you briefly introduce how to use [xeus-r](https://github.com/jupyter-xeus/xeus-r)? or we just need to install it? then use IRkernel add the R kernel to jupyter? thanks a lot!

**Comment by ShuaishuaiTai** [comment]
I have also encountered this issue. Is there a solution available as of now?

**Comment by SilenWang** [comment]
> I have also encountered this issue. Is there a solution available as of now?

I think you can use xeus-r in alternative to irkernel in jupyter, I wrote a [blog](https://silenwang.github.io/en/2024/06/23/%E4%BD%BF%E7%94%A8%E6%96%B0%E7%9A%84R%E8%AF%AD%E8%A8%80jupyter%E5%86%85%E6%A0%B8%E8%A7%A3%E5%86%B3monocle3%E6%97%A0%E6%B3%95%E5%9C%A8notebook%E4%B8%8A%E9%80%89%E5%8F%91%E8%82%B2%E8%B5%B7%E5%A7%8B%E7%82%B9%E7%9A%84%E9%97%AE%E9%A2%98/) about it.

**Comment by ShuaishuaiTai** [comment]
Thank you very much. I will follow your blog to solve this difficult problem.

> > I have also encountered this issue. Is there a solution available as of now?
> 
> I think you can use xeus-r in alternative to irkernel in jupyter, I wrote a [blog](https://silenwang.github.io/en/2024/06/23/%E4%BD%BF%E7%94%A8%E6%96%B0%E7%9A%84R%E8%AF%AD%E8%A8%80jupyter%E5%86%85%E6%A0%B8%E8%A7%A3%E5%86%B3monocle3%E6%97%A0%E6%B3%95%E5%9C%A8notebook%E4%B8%8A%E9%80%89%E5%8F%91%E8%82%B2%E8%B5%B7%E5%A7%8B%E7%82%B9%E7%9A%84%E9%97%AE%E9%A2%98/) about it.

Thank you very much. I will follow your blog to solve this difficult problem.

**Comment by ShuaishuaiTai** [comment]
> > I have also encountered this issue. Is there a solution available as of now?
> 
> I think you can use xeus-r in alternative to irkernel in jupyter, I wrote a [blog](https://silenwang.github.io/en/2024/06/23/%E4%BD%BF%E7%94%A8%E6%96%B0%E7%9A%84R%E8%AF%AD%E8%A8%80jupyter%E5%86%85%E6%A0%B8%E8%A7%A3%E5%86%B3monocle3%E6%97%A0%E6%B3%95%E5%9C%A8notebook%E4%B8%8A%E9%80%89%E5%8F%91%E8%82%B2%E8%B5%B7%E5%A7%8B%E7%82%B9%E7%9A%84%E9%97%AE%E9%A2%98/) about it.

When I followed the installation steps for Xeus-r and used conda to install it, I encountered an error when executing cmake .. -D CMAKE_PREFIX_PATH=$CONDA_PREFIX -D CMAKE_INSTALL_PREFIX=$CONDA_PREFIX -D CMAKE_INSTALL_LIBDIR=lib. The error message reads: "CMake Error: The source directory ".../anaconda3/envs/xeus-r" does not appear to contain CMakeLists.txt." Is there a solution to this problem? Thank you.

**Comment by SilenWang** [comment]
> > > I have also encountered this issue. Is there a solution available as of now?
> > 
> > 
> > I think you can use xeus-r in alternative to irkernel in jupyter, I wrote a [blog](https://silenwang.github.io/en/2024/06/23/%E4%BD%BF%E7%94%A8%E6%96%B0%E7%9A%84R%E8%AF%AD%E8%A8%80jupyter%E5%86%85%E6%A0%B8%E8%A7%A3%E5%86%B3monocle3%E6%97%A0%E6%B3%95%E5%9C%A8notebook%E4%B8%8A%E9%80%89%E5%8F%91%E8%82%B2%E8%B5%B7%E5%A7%8B%E7%82%B9%E7%9A%84%E9%97%AE%E9%A2%98/) about it.
> 
> When I followed the installation steps for Xeus-r and used conda to install it, I encountered an error when executing cmake .. -D CMAKE_PREFIX_PATH=$CONDA_PREFIX -D CMAKE_INSTALL_PREFIX=$CONDA_PREFIX -D CMAKE_INSTALL_LIBDIR=lib. The error message reads: "CMake Error: The source directory ".../anaconda3/envs/xeus-r" does not appear to contain CMakeLists.txt." Is there a solution to this problem? Thank you.

Installing the binary version of xeus-r from conda/mamba should not involve cmake. Are you installing from source?

Would directly running `conda install xeus-r -c conda-forge` cause this issue?

**Comment by ShuaishuaiTai** [comment]
> > > > I have also encountered this issue. Is there a solution available as of now?
> > > 
> > > 
> > > I think you can use xeus-r in alternative to irkernel in jupyter, I wrote a [blog](https://silenwang.github.io/en/2024/06/23/%E4%BD%BF%E7%94%A8%E6%96%B0%E7%9A%84R%E8%AF%AD%E8%A8%80jupyter%E5%86%85%E6%A0%B8%E8%A7%A3%E5%86%B3monocle3%E6%97%A0%E6%B3%95%E5%9C%A8notebook%E4%B8%8A%E9%80%89%E5%8F%91%E8%82%B2%E8%B5%B7%E5%A7%8B%E7%82%B9%E7%9A%84%E9%97%AE%E9%A2%98/) about it.
> > 
> > 
> > When I followed the installation steps for Xeus-r and used conda to install it, I encountered an error when executing cmake .. -D CMAKE_PREFIX_PATH=$CONDA_PREFIX -D CMAKE_INSTALL_PREFIX=$CONDA_PREFIX -D CMAKE_INSTALL_LIBDIR=lib. The error message reads: "CMake Error: The source directory ".../anaconda3/envs/xeus-r" does not appear to contain CMakeLists.txt." Is there a solution to this problem? Thank you.
> 
> Installing the binary version of xeus-r from conda/mamba should not involve cmake. Are you installing from source?
> 
> Would directly running `conda install xeus-r -c conda-forge` cause this issue?

Thank you very much for your quick reply. I accidentally mixed up the two installation methods. Using `conda install xeus-r -c conda-forge` can successfully install it, but after installation, I used the online JupyterLab in the lab and couldn't find the xr kernel.

**Comment by SilenWang** [comment]
> > > > > I have also encountered this issue. Is there a solution available as of now?
> > > > 
> > > > 
> > > > I think you can use xeus-r in alternative to irkernel in jupyter, I wrote a [blog](https://silenwang.github.io/en/2024/06/23/%E4%BD%BF%E7%94%A8%E6%96%B0%E7%9A%84R%E8%AF%AD%E8%A8%80jupyter%E5%86%85%E6%A0%B8%E8%A7%A3%E5%86%B3monocle3%E6%97%A0%E6%B3%95%E5%9C%A8notebook%E4%B8%8A%E9%80%89%E5%8F%91%E8%82%B2%E8%B5%B7%E5%A7%8B%E7%82%B9%E7%9A%84%E9%97%AE%E9%A2%98/) about it.
> > > 
> > > 
> > > When I followed the installation steps for Xeus-r and used conda to install it, I encountered an error when executing cmake .. -D CMAKE_PREFIX_PATH=$CONDA_PREFIX -D CMAKE_INSTALL_PREFIX=$CONDA_PREFIX -D CMAKE_INSTALL_LIBDIR=lib. The error message reads: "CMake Error: The source directory ".../anaconda3/envs/xeus-r" does not appear to contain CMakeLists.txt." Is there a solution to this problem? Thank you.
> > 
> > 
> > Installing the binary version of xeus-r from conda/mamba should not involve cmake. Are you installing from source?
> > Would directly running `conda install xeus-r -c conda-forge` cause this issue?
> 
> Thank you very much for your quick reply. I accidentally mixed up the two installation methods. Using `conda install xeus-r -c conda-forge` can successfully install it, but after installation, I used the online JupyterLab in the lab and couldn't find the xr kernel.

Do you mean you install xeus-r on your local computer and then use JupyterLab on your lab’s server? If you want to use xeus-r as the kernel, JupyterLab and xeus-r need to be in the same virtual environment. So, to use it on your lab’s server, you would need permission to install it there.

**Comment by ShuaishuaiTai** [comment]
> > > > > > I have also encountered this issue. Is there a solution available as of now?
> > > > > 
> > > > > 
> > > > > I think you can use xeus-r in alternative to irkernel in jupyter, I wrote a [blog](https://silenwang.github.io/en/2024/06/23/%E4%BD%BF%E7%94%A8%E6%96%B0%E7%9A%84R%E8%AF%AD%E8%A8%80jupyter%E5%86%85%E6%A0%B8%E8%A7%A3%E5%86%B3monocle3%E6%97%A0%E6%B3%95%E5%9C%A8notebook%E4%B8%8A%E9%80%89%E5%8F%91%E8%82%B2%E8%B5%B7%E5%A7%8B%E7%82%B9%E7%9A%84%E9%97%AE%E9%A2%98/) about it.
> > > > 
> > > > 
> > > > When I followed the installation steps for Xeus-r and used conda to install it, I encountered an error when executing cmake .. -D CMAKE_PREFIX_PATH=$CONDA_PREFIX -D CMAKE_INSTALL_PREFIX=$CONDA_PREFIX -D CMAKE_INSTALL_LIBDIR=lib. The error message reads: "CMake Error: The source directory ".../anaconda3/envs/xeus-r" does not appear to contain CMakeLists.txt." Is there a solution to this problem? Thank you.
> > > 
> > > 
> > > Installing the binary version of xeus-r from conda/mamba should not involve cmake. Are you installing from source?
> > > Would directly running `conda install xeus-r -c conda-forge` cause this issue?
> > 
> > 
> > Thank you very much for your quick reply. I accidentally mixed up the two installation methods. Using `conda install xeus-r -c conda-forge` can successfully install it, but after installation, I used the online JupyterLab in the lab and couldn't find the xr kernel.
> 
> Do you mean you install xeus-r on your local computer and then use JupyterLab on your lab’s server? If you want to use xeus-r as the kernel, JupyterLab and xeus-r need to be in the same virtual environment. So, to use it on your lab’s server, you would need permission to install it there.

Thank you very much. I will follow your instructions to solve this problem.
