### ISSUE TITLE
plot_cells() zero background color

### ISSUE THREAD

**Issue by brianpenghe** [cole-trapnell-lab/monocle3#180]
When I wanted to use a color palette to represent gene expression levels, I realized that plot_cells() use grey color to represent zeros. Can I abolish that grey background?

**Comment by hpliner** [comment]
Hello,

This issue appears to be an issue about our new package, Monocle 3. Please post any issues for Monocle 3 to the monocle3 repository at https://github.com/cole-trapnell-lab/monocle3.

- Monocle 3 Development team

In plot_cells, zeroes are converted to NA for plotting, so you can recolor using something like the below:
 plot_cells(cds, genes="gene1") + viridis::scale_color_viridis(na.value = "white")

**Comment by megclark3** [comment]
Hi, the above code [ plot_cells(cds, genes="gene1") + viridis::scale_color_viridis(na.value = "white") ] does not recolor the NA values to white, they remain grey (at least in the current version of monocle3). Is there a workaround where you can actually assign the grey background/non-expressing cells to be white? 

This is separate, but a related aesthetic issue. When plotting a cds, if you choose to use color_cells_by = "cluster", a black outline appears behind the cells. This is not an option when you plot gene expression, regardless of what you set the stroke size to (the stroke is the same color as the gene expression). Are there fixes/ways to adjust visualizations for either of these? Thanks!

**Comment by lileijie1992** [comment]
The plot_cells function generates a ggplot object. Therefore, you can remove the 'black spots layer' as shown below:
p<- plot_cells(cds, color_cells_by = "cluster")
p$layers <- p$layers[-1]

**Comment by Tongbcc** [comment]
> The plot_cells function generates a ggplot object. Therefore, you can remove the 'black spots layer' as shown below: p<- plot_cells(cds, color_cells_by = "cluster") p$layers <- p$layers[-1]

That's COOL！ Your reply resolved my questions! Thank you!
