### ISSUE TITLE
Using Monocle 3 with multiple datasets

### ISSUE THREAD

**Issue by Caryn-Willis** [cole-trapnell-lab/monocle3#183]
I would like to run Monocle 3 on a group of 3 10X datasets. I would like to combine the 3 datasets but be able to identify which cells came from which dataset. Is there any way of doing this with Monocle 3? I tried using cbind but was getting errors once I tried clustering the cells or coloring by dataset.

**Comment by hpliner** [comment]
Hello, we have implemented a function called combine_cds in the last update (0.1.3). This function takes a list of cds' and combines them. See the manual information using ?combine_cds . This will be documented on the website sometime soon
