### ISSUE TITLE
Loading PCs into monocle 3

### ISSUE THREAD

**Issue by Connorr0** [cole-trapnell-lab/monocle3#185]
Hello, I have found I have been getting "better" looking batch correction in Seurat so I would like to load the Seurat batch corrected data and use it for Monocle 3 trajectory analyses (because I think it is super interesting!) Unfortunately there does not seem to be a way to stop Monocle 3's preprocess_cds function from preforming normalization on loaded data (like there is for scaling), which is problematic if the data was normalized previously using other software.

Currently I was considering re-writing the preprocess_cds function to accept a NULL argument, or directly load PCs (which does not seem possible)?

Do you have any recommendations for a best approach?

Also I think the option for a NULL, FALSE, "-1", ect  input for norm_method could prove advantageous as it would allow users the ability to do their own preprocessing and then load their data for trajectory and regulatory analysis (especially because the field of batch correction seems to still be developing and success is somewhat ambiguous.)

Thanks so much for this awesome package, there are some things I am excited to try!

**Comment by hpliner** [comment]
'none' argument added in 0.2.0!
