### ISSUE TITLE
How to choose the DDRTree method in monocle3 beta?

### ISSUE THREAD

**Issue by Sophia409** [cole-trapnell-lab/monocle3#187]
@ctrapnell Hello,
When I use monocle3 default parameters to plot_cell_trajectory , I got a not fully connected and ugly graph, as picture 1. The disjoint trajectory seems unsharp and not as clear as monocle2.It's hard to see the obvious path as monocle2.In[ this post](https://github.com/cole-trapnell-lab/monocle-release/issues/272#issuecomment-470254026),someone has issued the same question.And the solution is to **set partitionCells=F and rge_method = 'DDRTree'** : learnGraph(cds, RGE_method = 'DDRTree', do_partition=FALSE).In this way, we can still get a 'fully connected' graph similar to monocle2.

But **rge_method  parameter of learnGraph function is only in monocle3 Alpha ,not monocle3 Beta**. So in monocle3 beta,I got the joint trajectory like picture2.  **How can I got a simple trajectory with no too many branchs, just similar to monocle2 (picture3)?** I can use monocle2 to do it,but because of large number of cells,the speed is very slow.So wondering how I can still choose the DDRTree method in monocle3 beta?

   By the way, I just want to do a simple not very precise analysis on a five time points mouse single-cell RNA-seq data set. Wondering at the current stage, should I use monocle2,monocle 3 alpha or the latest Beta release? I'm really confused.Many thanks for any suggestions.
picture1
![图片](https://user-images.githubusercontent.com/30619010/60037603-90f20200-96e4-11e9-812c-7dbb6894e0a6.png)
picture2
![图片](https://user-images.githubusercontent.com/30619010/62460036-75821880-b7b3-11e9-89d5-acb4331f42b1.png)
picture3
![图片](https://user-images.githubusercontent.com/30619010/62461221-c2b3b980-b7b6-11e9-9619-38255eb7e33c.png)

**Comment by elfore** [comment]
Same here

**Comment by Sophia409** [comment]
Why no one respond here for many times? It's really disappointing and frustrating.On Seurat github issue, you can receive the reply from people in the lab quickly. I think that will help us make progress together.

**Comment by ctrapnell** [comment]
DDRTree is not likely to be included in Monocle 3 going forward, because it doesn't scale well to the kind of datasets Monocle 3 is designed to process. Beyond a 100,000 cells DDRTree is impractically slow. However, SimplePPT and DDRTree are closely related techniques, and in our experience, UMAP + SimplePPT is faster, more robust, and gives easier to interpret trajectories than UMAP or PCA + DDRTree.
