### ISSUE TITLE
question about "preprocess_cds"

### ISSUE THREAD

**Issue by xiexiaowei** [cole-trapnell-lab/monocle3#189]
Hi, monocle3

"preprocess_cds" would normalize the data by "log" and "size_only".
However, my data has deen normlized well and corrected using other softwares. I want to use this data to acheieve trajectory inference by monocle3.

So, what should I do?
Thanks very much and looking forward to your reply!

**Comment by hpliner** [comment]
Hi, thanks for the report/Q. I've added the "none" option to preprocess_cds as requested - I'd just caution that you're sure depth is accounted for previously when you're using it! 

Change will be released in 0.2.0!
