### ISSUE TITLE
learn_graph() nothing error to show ,but can't  get trajectory picture

### ISSUE THREAD

**Issue by aina91** [cole-trapnell-lab/monocle3#190]
** If this is a question and not a bug report or enhancement request, please post to our google group at https://groups.google.com/forum/#!forum/monocle-3-users**
hello,when i want to learn_graph() ,it can't work ,it didn't show the dash line which may be processing and i didn't receive any error report,but the trajectory picture can't show. I don't konw what happened ,could you help me resolve this problem,Thanks~
**Describe the bug**

**To Reproduce**
The code that produced the bug:
cds<-learn_graph(cds)
**traceback()**
After the error, run traceback() in R and post the output:

**Expected behavior**

**Screenshots**

**sessionInfo():**
Run sessionInfo() in R and post the output
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

**Additional context**

**Comment by hpliner** [comment]
Can you please post an example of your plot and the code you used to generate it?

**Comment by aina91** [comment]
#reconstruct new_cell_data_set
new_cds<-new_cell_data_set(as(exp,"sparseMatrix"),gene_metadata=fd,cell_metadata=pd)
#standardised process
new_cds <- preprocess_cds(new_cds, num_dim = 100,method="LSI")
new_cds <- reduce_dimension(new_cds)
new_cds <- cluster_cells(new_cds,reduction_method= "UMAP")
#Learn graph
pdf("myogenesis.pdf")
new_cds <- learn_graph(new_cds)
dev.off()
here is snippet of code that i can't get any response,I will greatly appreciate any thoughts you can offer : )

**Comment by hpliner** [comment]
Hello,

The learn_graph function generates the graph and saves it to the cds object, but does not plot anything. To see the plot, you'll need to run learn_graph as you do above, and then use plot_cells to generate the plot, i.e.:

`
#reconstruct new_cell_data_set
new_cds<-new_cell_data_set(as(exp,"sparseMatrix"),gene_metadata=fd,cell_metadata=pd)
#standardised process
new_cds <- preprocess_cds(new_cds, num_dim = 100,method="LSI")
new_cds <- reduce_dimension(new_cds)
new_cds <- cluster_cells(new_cds,reduction_method= "UMAP")
#Learn graph
new_cds <- learn_graph(new_cds)
pdf("myogenesis.pdf")
plot_cells(new_cds)
dev.off()`

Hope this helps!

**Comment by aina91** [comment]
Thanks ：）




| |
艾娜
邮箱：aina9666@163.com
|

签名由 网易邮箱大师 定制

On 09/09/2019 21:49, Hannah A Pliner wrote:

Closed #190.
