### ISSUE TITLE
find_gene_modules does not run on all genes

### ISSUE THREAD

**Issue by Connorr0** [cole-trapnell-lab/monocle3#191]
** If this is a question and not a bug report or enhancement request, please post to our google group at https://groups.google.com/forum/#!forum/monocle-3-users**

**Describe the bug**

If you do not subset the data find_gene_modules returns a subscript out of bounds error on large datasets.

**To Reproduce**
The code that produced the bug:
gene_module_df = find_gene_modules(cds)

**traceback()**
After the error, run traceback() in R and post the output:
1: find_gene_modules(cds)

**Expected behavior**
Gene modules found from looking at all genes

**Screenshots**

**sessionInfo():**
Run sessionInfo() in R and post the output

**Additional context**
I really like this function because it seems to be good at identifying new markers and pathways, but I wished it worked without subsetting

**Comment by Connorr0** [comment]
Thanks for the info! I have a couple weekend problems in the pipeline and I might end up adding this to the list. I'll post something here if I get a fix but it might be a while.

**Comment by j-andrews7** [comment]
Yeah, if anyone is trying to use `Seurat` dimensionality reductions and running into the same issue, the way around it is to set `return.only.var.genes=FALSE` in your `ScaleData` or `SCTransform` call, though it will take much longer.

**Comment by ctrapnell** [comment]
@j-andrews7 is correct - find_gene_modules works by clustering the genes based on their loadings in the initial preprocess_cds, so if they're excluded from that on the basis being too lowly expressed (or explicitly by the use via the use_genes argument), they won't show up here. This is by design.
