### ISSUE TITLE
Error in eval(predvars, data, env) : object 'bg.300.loading' not found

### ISSUE THREAD

**Issue by DirtyHarry80** [cole-trapnell-lab/monocle3#192]
Hi,
I tried to reconstruct the trajectory on a normal liver data set that was recently published (https://www.nature.com/articles/s41467-018-06318-7) using Monocle 3. After importing the Seurat object I did normal pre-processing and clustering, all works - fine. However when I tried to reconstruct the trajectory, I used as - as advised in the tutorial - residual_model_formula_str parameters (I guess) that are: "~ bg.300.loading + bg.400.loading + bg.500.1.loading + bg.500.2.loading + bg.r17.loading + bg.b01.loading + bg.b02.loading"

This gave the error : Error in eval(predvars, data, env) : object 'bg.300.loading' not found

**The code that produced the bug:**
library(HumanLiver)
viewHumanLiver()
data <- HumanLiverSeurat@assays$RNA@data
cell_metadata <- new('AnnotatedDataFrame', data = HumanLiverSeurat@meta.data)
fData <- data.frame(gene_short_name = row.names(data), row.names = row.names(data))
gene_metadata <- new('AnnotatedDataFrame', data = fData)
gene_metadata <- as(gene_metadata, "data.frame")
cell_metadata <- as(cell_metadata, "data.frame")
HLcds <- new_cell_data_set(data,
                           cell_metadata = cell_metadata,
                           gene_metadata = gene_metadata
HLcds.traj <- preprocess_cds(HLcds, num_dim = 100, residual_model_formula_str = "~ bg.300.loading + bg.400.loading + bg.500.1.loading + bg.500.2.loading + bg.r17.loading + bg.b01.loading + bg.b02.loading")

**traceback()**
6: eval(predvars, data, env)
5: eval(predvars, data, env)
4: model.frame.default(object, data, xlev = xlev)
3: model.frame(object, data, xlev = xlev)
2: Matrix::sparse.model.matrix(stats::as.formula(residual_model_formula_str), 
       data = colData(cds), drop.unused.levels = TRUE)
1: preprocess_cds(HLcds, num_dim = 100, residual_model_formula_str = "~ bg.300.loading + bg.400.loading + bg.500.1.loading + bg.500.2.loading + bg.r17.loading + bg.b01.loading + bg.b02.loading")

**Comment by hpliner** [comment]
Hello,

The bg.loadings are specific experimental metadata for the example dataset used as an example of batch correction. You won't have that metadata for you data. You can use metadata you do have to batch correction, or you can skip batch correction by not including residual_model_formula_str.
