### ISSUE TITLE
Error in X[, partition_list == cur_comp] 

### ISSUE THREAD

**Issue by DirtyHarry80** [cole-trapnell-lab/monocle3#195]
This is an issue with the learn_graph function, where once a subset of cells has been defined, one gets an error such as:

Error in X[, partition_list == cur_comp] : 
  (subscript) logical subscript too long

**Comment by hpliner** [comment]
Thank you for submitting a bug report. Your report has insufficient information for us to address it. Please respond with the information requested in the bug report issue template. At minimum, please include: 

1. The code you ran that generated the error
2. The output of the call - and what was expected
3. The output of traceback()
4. The output of sessionInfo()

We will close this issue - when you answer with this further information, please reopen the issue.

- Monocle3 Dev Team

**Comment by yangrc3** [comment]
<img width="644" alt="image" src="https://user-images.githubusercontent.com/56957915/68453984-2aecbe00-0232-11ea-8e57-0cb7dbf8f526.png">
Hi,I also have the same problem with learn_graph function. And my code is like that.

**Comment by yangrc3** [comment]
<img width="650" alt="image" src="https://user-images.githubusercontent.com/56957915/68454261-0b09ca00-0233-11ea-9d89-8cf0e3442e13.png">
However, if I learn_graph(cds),it will be all right.

**Comment by yangrc3** [comment]
Sorry, I have figured out my issue. My initial problem with learn_graph(cds_subset) was my bad, I had forgotted to cluster_cells(cds_subset) before that.  
I think maybe you can try it.@DirtyHarry80

**Comment by brgew** [comment]
monocle3 has now an error message when learn_graph(cds) is called before cluster_cells(cds).

**Comment by wfma** [comment]
got here for the same error message, subsetting needs to be clustered again apparently. Thanks!
