### ISSUE TITLE
plot_markers_cluster not available for Monocle 3

### ISSUE THREAD

**Issue by Caryn-Willis** [cole-trapnell-lab/monocle3#199]
I see in Monocle 3 alpha, plot_markers_cluster was available to do a heat map of the gene expression by cluster. This function is not available in Monocle 3. Can this be added? I would like to use this feature.

**Comment by ctrapnell** [comment]
`plot_markers_cluster() `has been replaced by `plot_genes_by_group()`:  

https://cole-trapnell-lab.github.io/monocle3/docs/clustering/#find-markers

But if you like the heatmap style of things, you might find this section of the manual helpful: 
https://cole-trapnell-lab.github.io/monocle3/docs/differential/#gene-modules
