### ISSUE TITLE
question for installation..

### ISSUE THREAD

**Issue by MQMQ2018** [cole-trapnell-lab/monocle3#200]
Dear Authors: 
My process of installation of Monocle3 was stuck at the error below:
#===#
installing to /home/mq2019/miniconda2/lib/R/library/00LOCK-classInt/00new/classInt/libs
** R
** inst
** byte-compile and prepare package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/mq2019/miniconda2/lib/R/library/KernSmooth/libs/KernSmooth.so':
  libopenblas.so.0: cannot open shared object file: No such file or directory
Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted
ERROR: lazy loading failed for package ‘classInt’
* removing ‘/home/mq2019/miniconda2/lib/R/library/classInt’
Error: Failed to install 'monocle3' from GitHub:
  (converted from warning) installation of package ‘classInt’ had non-zero exit status
#===#

Could you give me some tips on solving this question? 
Thank you so much!

Best,
Qi

**Comment by hpliner** [comment]
This looks like it's an issue installing the package 'classInt'. Can you try installing that on its own using BiocManager::install('classInt') and see if you get the same error? In addition, did you indicate you wanted to update your packages when installing Monocle? Try reinstalling but choosing "None" when it asks if you want to update.

**Comment by hpliner** [comment]
Closing from lack of response
