### ISSUE TITLE
Conda envoronment Monocle3

### ISSUE THREAD

**Issue by johnmous** [cole-trapnell-lab/monocle3#201]
Installing monocle v3 can be a real challenge, as seen by the number of relevant issues/questions. 

Are the developers planning to create a conda environment for v3 soon?

**Comment by mjsteinbaugh** [comment]
@hpliner We added the `r-monocle3` recipe to bioconda today:
https://github.com/bioconda/bioconda-recipes/tree/master/recipes/r-monocle3

**Comment by hpliner** [comment]
@mjsteinbaugh  thanks for adding! Can you checkout the error reported here: https://github.com/cole-trapnell-lab/monocle3/issues/218 or let me know where bioconda specific issues should be reported?

**Comment by mjsteinbaugh** [comment]
Sure thing @hpliner, and I'll take a look at that issue and see if I can fix the recipe today. If users hit any conda problems, they should file an issue in the bioconda-recipes repo here: https://github.com/bioconda/bioconda-recipes/issues

This link in particular is a useful reference for updating recipes:
https://bioconda.github.io/contributor/index.html

Best,
Mike

**Comment by ctrapnell** [comment]
@hpliner can we close this?
