### ISSUE TITLE
load Seurat coembed object into monocle3 for trajectory analysis

### ISSUE THREAD

**Issue by s18692001** [cole-trapnell-lab/monocle3#209]
Hi there,

I have a coembed Seurat object that already done CCA for scATAC and scRNA-seq. Is there any way that I can import this CCA reduction coembed object to monocle3 for trajectory analysis? Thanks!

**Comment by ctrapnell** [comment]
We don't officially support this right now, but you can find some examples of doing this on the google group: https://groups.google.com/forum/#!forum/monocle-3-users.

Use at your own risk!
