### ISSUE TITLE
Error in Monocle 3 Developer installation 

### ISSUE THREAD

**Issue by Seandelao** [cole-trapnell-lab/monocle3#210]
Hello, 

I am trying to install the developer version of Monocle 3 so that I can use mmn batch correction as in the c. elegans example on Github. However, my installation is failing: 

ERROR: compilation failed for package ‘leidenbase’

I am trying to find this package in R, but am having a hard time. How can I solve this? 

Thanks for the awesome package! 

**Code:** 
devtools::install_github("cole-trapnell-lab/monocle3", ref="develop")

**Traceback:** 
> traceback()
8: stop(remote_install_error(remotes[[i]], e))
7: value[[3L]](cond)
6: tryCatchOne(expr, names, parentenv, handlers[[1L]])
5: tryCatchList(expr, classes, parentenv, handlers)
4: tryCatch(res[[i]] <- install_remote(remotes[[i]], ...), error = function(e) {
       stop(remote_install_error(remotes[[i]], e))
   })
3: install_remotes(remotes, auth_token = auth_token, host = host, 
       dependencies = dependencies, upgrade = upgrade, force = force, 
       quiet = quiet, build = build, build_opts = build_opts, build_manual = build_manual, 
       build_vignettes = build_vignettes, repos = repos, type = type, 
       ...)
2: pkgbuild::with_build_tools({
       ellipsis::check_dots_used()
       remotes <- lapply(repo, github_remote, ref = ref, subdir = subdir, 
           auth_token = auth_token, host = host)
       install_remotes(remotes, auth_token = auth_token, host = host, 
           dependencies = dependencies, upgrade = upgrade, force = force, 
           quiet = quiet, build = build, build_opts = build_opts, 
           build_manual = build_manual, build_vignettes = build_vignettes, 
           repos = repos, type = type, ...)
   }, required = FALSE)

**Comment by brgew** [comment]
Hi,

Thank you for trying the Monocle3 developer version.

I will need additional information about your computer system, the R
sessionInfo, and output from the leidenbase install command.

Can you tell me please the type of computer system on which you want to
install Monocle3? Is it a Mac running MacOS, a Linux system, or a Windows
system? If you know the operating system name and version, that might help
too.

Have you installed C, C++, and FORTRAN compilers? Can you try checking
for these compilers using a terminal window? Can you tell me the names
and versions of the compilers that you find?

language       some compiler commands
--------       ----------------------
C              cc, gcc, clang
C++            c++, g++, clang++
FORTRAN        f77, f95, gfortran, flang

You can find the names of compilers that R tries to use when it builds
packages in the file R_HOME/etc/Makeconf. You can find R_HOME using the
R command R.home() and look at the file contents using the 'less' command, 
if you are using MacOS or Linux. The more interesting lines in this file 
start with the strings

CC =
CFLAGS =
CPICFLAGS =
CPPFLAGS =
CXX =
CXXCPP =
CXXFLAGS =
CXXPICFLAGS =
CXX98 =
CXX98FLAGS =
CXX98PICFLAGS =
CXX98STD =
CXX11 =
CXX11FLAGS =
CXX11PICFLAGS =
CXX11STD =
CXX14 =
CXX14FLAGS =
CXX14PICFLAGS =
CXX14STD =
CXX17 =
CXX17FLAGS =
CXX17PICFLAGS =
CXX17STD =
CXX_VISIBILITY =
DYLIB_EXT =
DYLIB_LD =
DYLIB_LDFLAGS =
DYLIB_LINK =
FC =
FCFLAGS =
FCLIBS_XTRA =
FFLAGS =
FLIBS =

It may help to send to me these lines that you find in the Makeconf file.

Can you run the sessionInfo() command in R and send the output to me?

Can you try to install leidenbase in R using the command

  devtools::install_github('cole-trapnell-lab/leidenbase')

and send the output too?

I appreciate your patience and feedback.

Thank you.

**Comment by mjsteinbaugh** [comment]
@Seandelao, alternatively you can try installing monocle3 with [bioconda](https://bioconda.github.io/), which helps avoid compilation issues:

```
conda install -c bioconda r-monocle3
```

See also #201

**Comment by Seandelao** [comment]
> @Seandelao, alternatively you can try installing monocle3 with [bioconda](https://bioconda.github.io/), which helps avoid compilation issues:
> 
> ```
> conda install -c bioconda r-monocle3
> ```
> 
> See also #201

Hi, 

Is this also applicable for the developer version?

**Comment by Seandelao** [comment]
@brgew, 

Apologies, I am not the most computer savy but I'll try to see if I can find what you asked. 

I am trying to install on a Macbook Pro with MacOS Sierra, version 10.12.6. As far as the compilers, I believe that I have those installed. I can't quite find the folder/path you were mentioning. 

My R Session info is: 
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] monocle3_0.1.3              SingleCellExperiment_1.6.0  SummarizedExperiment_1.14.1
 [4] DelayedArray_0.10.0         BiocParallel_1.18.1         matrixStats_0.55.0         
 [7] GenomicRanges_1.36.1        GenomeInfoDb_1.20.0         IRanges_2.18.2             
[10] S4Vectors_0.22.1            Biobase_2.44.0              BiocGenerics_0.30.0        

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2             lattice_0.20-38        prettyunits_1.0.2      ps_1.3.0              
 [5] assertthat_0.2.1       rprojroot_1.3-2        digest_0.6.20          R6_2.4.0              
 [9] plyr_1.8.4             backports_1.1.4        ggplot2_3.2.1          pillar_1.4.2          
[13] zlibbioc_1.30.0        rlang_0.4.0            curl_4.0               lazyeval_0.2.2        
[17] rstudioapi_0.10        callr_3.3.1            Matrix_1.2-17          DT_0.8                
[21] desc_1.2.0             devtools_2.2.0         stringr_1.4.0          htmlwidgets_1.3       
[25] RCurl_1.95-4.12        munsell_0.5.0          compiler_3.6.1         pkgconfig_2.0.2       
[29] pkgbuild_1.0.5         htmltools_0.3.6        tidyselect_0.2.5       tibble_2.1.3          
[33] gridExtra_2.3          GenomeInfoDbData_1.2.1 viridisLite_0.3.0      crayon_1.3.4          
[37] dplyr_0.8.3            withr_2.1.2            bitops_1.0-6           grid_3.6.1            
[41] gtable_0.3.0           magrittr_1.5           scales_1.0.0           cli_1.1.0             
[45] stringi_1.4.3          XVector_0.24.0         reshape2_1.4.3         fs_1.3.1  
[49] remotes_2.1.0          viridis_0.5.1          testthat_2.2.1         ellipsis_0.2.0.1      
[53] tools_3.6.1            glue_1.3.1             purrr_0.3.2            processx_3.4.1        
[57] pkgload_1.0.2          yaml_2.2.0             colorspace_1.4-1       BiocManager_1.30.4    
[61] sessioninfo_1.1.1      memoise_1.1.0          usethis_1.5.1         

Trying to install Leidenbase itself also has an error, with the error as: 
make: gfortran: No such file or directory
make: *** [cigraph/src/AMD/Source/amd.o] Error 1
ERROR: compilation failed for package ‘leidenbase’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/leidenbase’
Error: Failed to install 'leidenbase' from GitHub:
  (converted from warning) installation of package ‘/var/folders/12/g7syt4090_j_3066v68pj5rw0000gn/T//Rtmp6uB2yV/filebfaa3a19185d/leidenbase_0.1.0.tar.gz’ had non-zero exit status

**Comment by mjsteinbaugh** [comment]
@Seandelao the bioconda recipe will install monocle 0.1.3 from the release tag (https://github.com/cole-trapnell-lab/monocle3/releases/tag/0.1.3), but you can load the conda environment up and install from the develop branch inside an R session.

**Comment by Seandelao** [comment]
@mjsteinbaugh I ran **conda install -c bioconda r-monocle3**  in terminal and it installed fine, but when running **devtools::install_github("cole-trapnell-lab/monocle3", ref="develop")** it is still giving me the same error that I detailed above.

**Comment by brgew** [comment]
@Seandelao Hi, Thank you for sending the information. It appears that gfortran is not installed your system, based on the line 'make: gfortran: No such file or directory'. The R Project makes available compilers for MacOS on their web site https://cran.r-project.org/bin/macosx/tools/. I hope that installing gfortran will solve this problem.

**Comment by Seandelao** [comment]
@brgew wow I have no idea how I missed that, nor how it wasn't installed. I have definitely installed gcc before... 

Anyway, I ran 'brew install gcc' and then devtools::install_github("cole-trapnell-lab/monocle3", ref="develop") and it installed properly. Thanks!
