### ISSUE TITLE
Can't find monocle3.dylib 

### ISSUE THREAD

**Issue by weichen123hahah** [cole-trapnell-lab/monocle3#218]
I use the command conda -c bioconda r-monocle3 to install monocle3 but I can't library

 package or namespace load failed for ‘monocle3’ in library.dynam(lib, package, package.lib):
 shared object ‘monocle3.dylib’ have non-exist

**Comment by weichen123hahah** [comment]
macOS 10.14.5

**Comment by zhangguy** [comment]
same issue here in Mac
```conda create -n r-monocle3 -c bioconda r-monocle3```

**Comment by hpliner** [comment]
Believe this should be solved
