### ISSUE TITLE
Single iteration louvain for find_gene_modules()

### ISSUE THREAD

**Issue by Connorr0** [cole-trapnell-lab/monocle3#222]
Hello, I was noticing that my output from find_gene_modules() was unstable, then when I was looking closer I noticed that the default behavior for the function was to run a single iteration. Why is this the default behavior? My understanding may be wrong but it seems like the output of louvain can be dependent on the start node, as such one would expect that multiple iterations of the clustering would be run with random initializations rather than a single iteration.

**Comment by Connorr0** [comment]
Even at high numbers of iterations ~100 I still am seeing reasonably different modules between runs.

**Comment by ctrapnell** [comment]
Is this with v0.2.0 or earlier?

**Comment by ctrapnell** [comment]
Closing, as this is no longer relevant for v0.2.0 and later, which uses Leiden.
