### ISSUE TITLE
combine_cds question

### ISSUE THREAD

**Issue by tmccra2** [cole-trapnell-lab/monocle3#228]
Hello!

This is similar to this question: https://github.com/cole-trapnell-lab/monocle3/issues/183

How does monocle3 save information about which sample the cell came from after combining? 
Where is the cell meta_data, and what is the default format? 

Example, in your tutorial you have: 
`big_cds <- combine_cds(list(cds, cds2))`

How would you see "cds" and "cds2" and what would the meta_data column be called?

Thanks!

**Comment by tmccra2** [comment]
I combined my samples:    `cds2 <- combine_cds(list(cds, cds1))`

If I try to look at the columns available for color_cells_by: `colData(cds)`

> DataFrame with 11216 rows and 3 columns
>                                 barcode       Size_Factor    sample
>                                <factor>         <numeric> <integer>
> AAACCCAAGGCCGCTT-1_1 AAACCCAAGGCCGCTT-1  1.64390717977309         1
> AAACCCAAGTTGCTGT-1_1 AAACCCAAGTTGCTGT-1  1.50923580243787         1
> AAACCCACAATTCTTC-1_1 AAACCCACAATTCTTC-1   1.3344505025008         1
> AAACCCACATGGCCAC-1_1 AAACCCACATGGCCAC-1  1.51938781420497         1
> AAACGAAAGGCATCAG-1_1 AAACGAAAGGCATCAG-1 0.338969384046556         1
> ...                                 ...               ...       ...
> TTTGTTGGTAATCAAG-1_2 TTTGTTGGTAATCAAG-1 0.931110176585875         2
> TTTGTTGGTATCTCTT-1_2 TTTGTTGGTATCTCTT-1  2.33442366155996         2
> TTTGTTGGTATGTCCA-1_2 TTTGTTGGTATGTCCA-1  1.51893861014448         2
> TTTGTTGTCATGTCTT-1_2 TTTGTTGTCATGTCTT-1  1.55438081051723         2
> TTTGTTGTCGTAATGC-1_2 TTTGTTGTCGTAATGC-1 0.829051014042306         2

So "sample" seems to be an option, it has 2 integers and I had 2 samples
`plot_cells(cds, color_cells_by="sample")`

It looks like I get two colors, but the graph generates multiple integer options in the legend
![UMAP_sample](https://user-images.githubusercontent.com/46829204/65923041-fbce6b80-e3ac-11e9-98d4-d0c291c20b59.jpeg)

**Comment by ctrapnell** [comment]
Per-cell metadata is stored in the colData table upon creation with new_cell_data_set().

Please send questions to the google group rather than submitting them as issues. You can post to the group here: 

https://groups.google.com/forum/#!forum/monocle-3-users
