### ISSUE TITLE
Pseudotime error when i import Seurat UMAP result to monocle3.

### ISSUE THREAD

**Issue by XY-HUHU** [cole-trapnell-lab/monocle3#229]
Hello,

I want to use the Seurat UMAP result to do pseudotime analysis, so i use the code

`cds@reducedDims@ListDAta[["UMAP']] <- Data.integrated@reductions[["umap"]]@cell.embeddings`

Then to run
`cds <- cluster_cell(cds)`
`cds <- learn_graph(cds)`
![微信图片_20191003150621](https://user-images.githubusercontent.com/53069088/66105991-68d14380-e5ef-11e9-9f08-2abc9d7ef485.png)

Then i run 
`cds <- order_cells(cds)`
![微信图片_20191003151540](https://user-images.githubusercontent.com/53069088/66106535-b601e500-e5f0-11e9-97c0-163469744707.jpg)
![微信图片_20191003151619](https://user-images.githubusercontent.com/53069088/66106569-c7e38800-e5f0-11e9-92c8-5c15571da280.jpg)

I want to know how can i use the Seurat UMAP result to construct pseudutiome analysis, or how to define the reduce_dimension 's umap method. I hope to use "uwot" method.

Hope your reply, thank u.

**Comment by ctrapnell** [comment]
I would recommend something like:

cds@reducedDims[["UMAP"]] = as.matrix(Data.integrated@reductions[["umap"]]@cell.embeddings)

However, please understand that we do not officially support this type of thing, and you do it at your own risk.
