### ISSUE TITLE
Issue loading in 10x matrix files using load_cellranger_data using Monocle3

### ISSUE THREAD

**Issue by scideas** [cole-trapnell-lab/monocle3#230]
Hi,

I have all 3 files that are required for building the single-cell matrix successfully in Seurat3, including barcodes.tsv, features.tsv, & matrix.mtx. I'm using the raw_feature_bc_matrix folder.

For reference, my directories are arranged as they'd appear as raw cell ranger output folders with the hope it could read in these files (and I used many other types of arrangements I found online), but no dice... I also examined the raw code for this function in monocle3 and I didn't see anything that made it appear my filenames are incorrect.

As of now, these are the folder layouts I've tried:
pipestance_path >outs > raw_feature_bc_matrix > files are located here
pipestance_path >outs > raw_feature_bc_matrix > mm10 > files are located here

However, I always get an error relating to the files not being found every time I try to read in the files. Any glaring errors here?

Also, I'm not sure why it's necessary to point to the "pipestance_path" folder, rather than simply pointing to the matrices, themselves. This seems a lot less prone to error, but I"m sure there's a good reason on your end...

Thanks,
Aaron

**Comment by Seandelao** [comment]
Hey Aaron, 

Was also having this problem. My code to get it to run was:

cds <- load_cellranger_data("/Users/myname/Desktop/myfolder")

And within myfolder, I had folders/files arranged as: myfolder > outs > filtered_gene_bc_matrices > GRCm38 > barcodes.tsv, matrix.mtx, and genes.tsv. 

For some reason I had to change the name of my features.tsv file to genes.tsv; not sure why. 

Hope this helps!

**Comment by scideas** [comment]
Thanks, @Seandelao ! Will have to give this a try tomorrow.

**Comment by scideas** [comment]
@Seandelao, that worked!!!! Wow, what a convoluted method for loading a 10x matrix....

Thanks so much for your help!
