### ISSUE TITLE
Can't install Monocle 3 without upgrading to R 3.6 due to "batchelor" package

### ISSUE THREAD

**Issue by julienvibert** [cole-trapnell-lab/monocle3#234]
Hi,

I tried installing today Monocle 3 (I had already installed Monocle 3 alpha), however I can't make it work because when I run the command: 
devtools::install_github('cole-trapnell-lab/monocle3'
It says:
ERROR: dependency ‘batchelor’ is not available for package ‘monocle3’
* removing ‘/home/julien/R/x86_64-pc-linux-gnu-library/3.5/monocle3’
Erreur : Failed to install 'monocle3' from GitHub:

And when I try to install "batchelor" from Bioconductor:
BiocManager::install("batchelor")
It says:
package ‘batchelor’ is not available (for R version 3.5.1)
(which is true indeed, it is available only for R 3.6)

Therefore it seems that I have to upgrade to R 3.6 to be able to use Monocle 3..
It bothers me for other reasons to have to upgrade my R version, and it seems that Monocle 3 is supposed to work on R 3.5. Is there a way to circumvent this problem without upgrading to R 3.6 (maybe installing Monocle 3 without requiring "batchelor")?

Thanks a lot!

Julien

**Comment by smanne07** [comment]
Hi,

Got the same error on R-3.5.1

Error: Failed to install 'monocle3' from GitHub:
  (converted from warning) package ‘batchelor’ is not available (for R version 3.5.1)

I cannot upgrade to R > 3.5.1 right now,is there a version of monocle3 which doesnt depend on batchelor which we can install for R 3.5.1

Thanks a lot.

Sasi

**Comment by Loyale** [comment]
FYI...batchelor can be installed from source on 3.5.1 with no adverse affects to monocle3's workflows in my experience. Once batchelor is installed, the suggested installation of leidenbase and monocle3 on the vignette can proceed w/o error.

**Comment by brgew** [comment]
Hi @Loyale,

Thank you for posting your solution! Inspired by your comment, I checked the 'DESCRIPTION' file in the batchelor package for a 'Requires: R (>=3.6)' line: it is absent. So the requirement for R version >= 3.6 must be imposed by the BiocManager::install() function in the Bioconductor version 3.9 release. Thank you again!

**Comment by julienvibert** [comment]
Hi,
Thanks for the answers!
However I still didn't manage to install the latest version of Monocle 3 because when I try to install "batchelor" from source, it tells me that I need "BiocSingular", which when I try to install says that it requires R 3.6..
Anyway I found a temporary solution that works fine for me: I installed Monocle 3 v0.1.3 directly from source code. 
Best,
Julien

**Comment by JihedC** [comment]
Hello,
I have the same issue here, I would like to keep my R at 3.5.1 and not build another environment. I tried to follow the suggestion of @Loyale, but I can't find where to install the release corresponding to the Bioconductor 3.8 version.
Can you help me?

**Comment by julienvibert** [comment]
Hi @JihedC ,
What worked for me was to install version 0.1.3 from source code available here:
https://github.com/cole-trapnell-lab/monocle3/releases
Hope it helps!
Best,
Julien

**Comment by JihedC** [comment]
Hi @julienvibert 
Thanks it worked!

**Comment by julienvibert** [comment]
Nice!
You're welcome @JihedC !

**Comment by brgew** [comment]
Hi,
It sounds like you have found ways to solve these issues. May I close this issue?
Thank you.
Brent

**Comment by alex-wenzel** [comment]
Hi @brgew, I am currently having this issue with v0.2.0 of Monocle3. I haven't tried @julienvibert's solution above because I am interested in the batch correction features in v0.2.0, but I haven't yet found a way to get v0.2.0 installed in my R 3.5.1 environment. I have tried installing v0.2.0 from source but encounter the same errors concerning batchelor and BiocSingular.

**Comment by brianpenghe** [comment]
This may not be a problem of R versions. 
https://github.com/LTLA/BiocSingular/issues/4

**Comment by brgew** [comment]
Hi @alex-wenzel,
Can you try upgrading R to 4.0.2?

**Comment by brgew** [comment]
Hi,
I am closing this in the absence of additional information.
