### ISSUE TITLE
Separate pseudotimes for different lineages

### ISSUE THREAD

**Issue by lambdamoses** [cole-trapnell-lab/monocle3#238]
I'm analyzing a dataset in which I expect one initial cell population to differentiate into several different cell populations. There's supposed to be only 1 partition. Here's the pseudotime plot: 

![image](https://user-images.githubusercontent.com/32186361/67060444-ab2b7200-f111-11e9-8bf4-a1b83e54aa60.png)

When I checked `pseudotime(cds)`, I only got a vector. I want to infer pseudotime separately for each lineage, just like in `slingshot`, and do DE along each lineage. Is there any way to do that? I know, there's the `choose_cells` function, but here for my data, I can't fit lineages into a box in that shiny app. It would be nice to have polygon selection.

**Comment by hpliner** [comment]
This should be doable with choose_graph_segments. See here for how to use: https://cole-trapnell-lab.github.io/monocle3/docs/trajectories/#subset-branch
