### ISSUE TITLE
Cant get Monocle3 installed

### ISSUE THREAD

**Issue by crushseven-7** [cole-trapnell-lab/monocle3#239]
Hi all,
Currently I am working on installing Monocle3. I installed it according to the instructions on the official website. Bioconductor dependencies installing seems fine.  When I running the command:
devtools::install_github('cole-trapnell-lab/leidenbase')
R throws me this error:
sh: 1: /bin/gtar: not found
sh: 1: /bin/gtar: not found
Error: Failed to install 'leidenbase' from GitHub:
  error in running command
In addition: Warning messages:
1: In system(cmd) : error in running command
2: In utils::untar(tarfile, ...) :
  ‘/bin/gtar -xf '/tmp/RtmpvYjC20/file1d1bd552b252c.tar.gz' -C '/tmp/RtmpvYjC20/remotes1d1bd12d68bd7'’ returned error code 127
I wonder what caused this problem, many thanks.

**Comment by rpeys** [comment]
In case it helps others in the future - running `export TAR="/bin/tar"` from my shell fixed the issue when this happened for me
