### ISSUE TITLE
no slot of name "reducedDims" for this object of class "SingleCellExperiment"

### ISSUE THREAD

**Issue by yejg2017** [cole-trapnell-lab/monocle3#249]
When I create a new_cell_data_set ,I got the error:no slot of name "reducedDims" for this object of class "SingleCellExperiment"
And I can not fixed,Could you help me ?Thanks !

**Comment by hpliner** [comment]
Can you please post your sessionInfo() and the code that generated the error?

**Comment by mjsteinbaugh** [comment]
This is a duplicate of issue #246

**Comment by hpliner** [comment]
Hello, 
This is an issue that appears after updating to Bioconductor 3.10 - reinstalling monocle3 appears to solve the problem!
