### ISSUE TITLE
combine_cds column naming issue

### ISSUE THREAD

**Issue by hoeflerb** [cole-trapnell-lab/monocle3#250]
I've been testing monocle3 a bit and I discovered an issue with the combine_cds function. As part of the cds merging, it keeps a counter in a column named 'sample' when cell_names_unique is False:

```
if (!cell_names_unique) {
      if(list_named) {
        row.names(pd) <- paste(row.names(pd), names(cds_list)[[i]], sep="_")
        pd$sample <- names(cds_list)[[i]]
      } else {
        row.names(pd) <- paste(row.names(pd), i, sep="_")
        pd$sample <- i
}
```

I happened to have a column in my CDS cell metadata named 'sample'. It took a while to figure out why my Factor column was being converted to an Integer. Renaming my 'sample' column to 'sample_id' fixed the issue, but it would be helpful if there was a warning when combine_cds encounters a column named 'sample' in the cds_list. Thanks!

**Comment by hpliner** [comment]
Thanks for the report, I have added a warning as you suggested that's now pushed to the develop branch and will be released in the next release.
