### ISSUE TITLE
S4Vectors error when installing Monocle3

### ISSUE THREAD

**Issue by pcantalupo** [cole-trapnell-lab/monocle3#251]
Hello, 
I'm trying to install Monocle3 on Win 10 under R 3.6.0. I followed the [install instructions](https://cole-trapnell-lab.github.io/monocle3/docs/installation/) but when I executed `devtools::install_github('cole-trapnell-lab/monocle3')`, I eventually got the following error:

```
Error: (converted from warning) package 'S4Vectors' was built under R version 3.6.1
Execution halted
ERROR: lazy loading failed for package 'monocle3'
* removing 'C:/Program Files/R/R-3.6.0/library/monocle3'
Error: Failed to install 'monocle3' from GitHub:
  (converted from warning) installation of package ‘C:/Users/pc/AppData/Local/Temp/Rtmp23HpaE/file26d426611629/monocle3_0.2.0.tar.gz’ had non-zero exit status
```

What should I try to install Monocle3. Thank you

**Comment by julicudini** [comment]
I had the same error but with SummarizedExperiment, I solved it by just installing Monocle 3 0.1.3 from source (https://github.com/cole-trapnell-lab/monocle3/releases/tag/0.1.3)

**Comment by pcantalupo** [comment]
Hi @julicudini ...thanks for the tip but I encountered other errors when trying to install from source: https://github.com/cole-trapnell-lab/monocle3/issues/256

**Comment by Astha08** [comment]
> Hello,
> I'm trying to install Monocle3 on Win 10 under R 3.6.0. I followed the [install instructions](https://cole-trapnell-lab.github.io/monocle3/docs/installation/) but when I executed `devtools::install_github('cole-trapnell-lab/monocle3')`, I eventually got the following error:
> 
> ```
> Error: (converted from warning) package 'S4Vectors' was built under R version 3.6.1
> Execution halted
> ERROR: lazy loading failed for package 'monocle3'
> * removing 'C:/Program Files/R/R-3.6.0/library/monocle3'
> Error: Failed to install 'monocle3' from GitHub:
>   (converted from warning) installation of package ‘C:/Users/pc/AppData/Local/Temp/Rtmp23HpaE/file26d426611629/monocle3_0.2.0.tar.gz’ had non-zero exit status
> ```
> 
> What should I try to install Monocle3. Thank you

Hello @pcantalupo Were you able to install Monocle3. I am facing the same problem. Thank you.

**Comment by alxsully** [comment]
I had a similar error when trying to install monocle 3 on OSX. 

'Error: (converted from warning) package 'S4Vectors' was built under R version 3.6.3
Execution halted
ERROR: lazy loading failed for package 'monocle3'
* removing 'C:/Program Files/R/R-3.6.0/library/monocle3'
Error: Failed to install 'monocle3' from GitHub:
  (converted from warning) installation of package ‘C:/Users/pc/AppData/Local/Temp/Rtmp23HpaE/file26d426611629/monocle3_0.2.0.tar.gz’ had non-zero exit status'

It was solved by updating to the most recent version of R, version 3.6.3

**Comment by pcantalupo** [comment]
@Astha08 No, I haven't tried to install M3 since opening the issue.

**Comment by hpliner** [comment]
Is this still an issue? Does reinstalling S4Vectors and then reinstalling monocle3 (order important) solve this?

**Comment by hpliner** [comment]
This looks like mismatch between your Bioconductor version and your R version. You can get around it by either aligning the two versions (by downgrading/upgrading), or easier, you can ignore the warning by setting the environmental variable with `Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")`

Reopen if this doesn't solve the issue
