### ISSUE TITLE
Monocle3 load_cellranger_data name attribute error

### ISSUE THREAD

**Issue by Saranya-Balachandran** [cole-trapnell-lab/monocle3#253]
Hi,
I am trying to read 10X data into Monocle3 using the load_cellranger_data. 
I am getting the below error:
Error in names(x) <- value : 
  'names' attribute [2] must be the same length as the vector [1]

I was able to successfully run the Seurat package with the files. 

Regards,
Saranya

**Comment by hpliner** [comment]
Thank you for submitting a bug report. Your report has insufficient information for us to address it. Please respond with the information requested in the bug report issue template. At minimum, please include: 

1. The code you ran that generated the error
2. The output of the call - and what was expected
3. The output of traceback()
4. The output of sessionInfo()

We will close this issue - when you answer with this further information, please reopen the issue.

- Monocle3 Dev Team
