### ISSUE TITLE
RDS import of monocle3 objects causes downstream issues

### ISSUE THREAD

**Issue by RoganGrant** [cole-trapnell-lab/monocle3#257]
I'm currently trying to explore the Cao organogenesis dataset using monocle3 0.2.0. After import, running any monocle3 function leads to the error:

> methods::is(cds, "cell_data_set") is not TRUE

Indeed, when I run `class(dataset)`, the output suggests that the class name is just written differently in the current version:

```
class(dataset)
[1] "CellDataSet"
attr(,"package")
[1] "monocle"
```
I can't say for sure if this is an issue with the RDS files themselves, or just a lack of backwards compatibility, but any help you may have is greatly appreciated. Oddly, although these files are marked as monocle3, they require monocle2 to be installed to import. This may be part of the issue.

**Comment by RoganGrant** [comment]
Update: this may be related to #176. For now, this hacky solution appears to do the trick:

```
caoAlphaVersion = readRDS("cds_cleaned.RDS")
exp = caoAlphaVersion@assayData$exprs
gmd = caoAlphaVersion@featureData@data
cmd = caoAlphaVersion@phenoData@data
cao = new_cell_data_set(exp,
                       gene_metadata = gmd, 
                       cell_metadata = cmd)
```
Still, making these interconvertible would be a great help

**Comment by hpliner** [comment]
Looks like you found the solution - Monocle3 was a complete redesign, so unfortunately the old CellDataSets are not compatible
