### ISSUE TITLE
Object 'model' not found error

### ISSUE THREAD

**Issue by RoganGrant** [cole-trapnell-lab/monocle3#261]
After trajectory analysis, I have found that both `fit_models` and `plot_genes_in_pseudotime` return an identical error:

> Error in purrr::map(.f = purrr::possibly(extract_model_status_helper,  : 
  object 'model' not found

The issue appears to be somewhere in `expr_models.R`, and is independent of the model I supply to `fit_models`. Downgrading to purrr 0.3.3 did not fix the error.

Session:

> R version 3.6.0 (2019-04-26)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Red Hat Enterprise Linux Server 7.5 (Maipo)
> 
> Matrix products: default
> BLAS:   /hpc/software/R/3.6.0/lib64/R/lib/libRblas.so
> LAPACK: /hpc/software/R/3.6.0/lib64/R/lib/libRlapack.so
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] monocle3_0.2.0              SingleCellExperiment_1.8.0  SummarizedExperiment_1.16.0 DelayedArray_0.12.0        
>  [5] BiocParallel_1.20.0         matrixStats_0.55.0          GenomicRanges_1.38.0        GenomeInfoDb_1.22.0        
>  [9] IRanges_2.20.0              S4Vectors_0.24.0            Biobase_2.46.0              BiocGenerics_0.32.0        
> 
> loaded via a namespace (and not attached):
>  [1] viridis_0.5.1          viridisLite_0.3.0      splines_3.6.0          gtools_3.8.1          
>  [5] assertthat_0.2.1       expm_0.999-4           sp_1.3-2               GenomeInfoDbData_1.2.2
>  [9] yaml_2.2.0             LearnBayes_2.15.1      slam_0.1-46            pillar_1.4.2          
> [13] lattice_0.20-38        glue_1.3.1             XVector_0.26.0         colorspace_1.4-1      
> [17] Matrix_1.2-17          plyr_1.8.4             pkgconfig_2.0.3        gmodels_2.18.1        
> [21] zlibbioc_1.32.0        purrr_0.3.3            scales_1.1.0           RANN_2.6.1            
> [25] gdata_2.18.0           tibble_2.1.3           ggplot2_3.2.1          lazyeval_0.2.2        
> [29] magrittr_1.5           crayon_1.3.4           deldir_0.1-23          nlme_3.1-139          
> [33] MASS_7.3-51.4          class_7.3-15           tools_3.6.0            lifecycle_0.1.0       
> [37] stringr_1.4.0          munsell_0.5.0          compiler_3.6.0         e1071_1.7-2           
> [41] pbmcapply_1.5.0        rlang_0.4.2            classInt_0.4-2         units_0.6-5           
> [45] grid_3.6.0             RCurl_1.95-4.12        rstudioapi_0.10        igraph_1.2.4.1        
> [49] bitops_1.0-6           boot_1.3-22            gtable_0.3.0           DBI_1.0.0             
> [53] reshape2_1.4.3         R6_2.4.1               gridExtra_2.3          knitr_1.26            
> [57] dplyr_0.8.3            spdep_1.1-3            KernSmooth_2.23-15     stringi_1.4.3         
> [61] Rcpp_1.0.3             sf_0.8-1               spData_0.3.2           tidyselect_0.2.5      
> [65] xfun_0.11              coda_0.19-3

**Comment by RoganGrant** [comment]
Update: it appears this was due to strange formatting of the `cell_metadata` by the original authors. Please disregard.

**Comment by JPingLin** [comment]
> Update: it appears this was due to strange formatting of the `cell_metadata` by the original authors. Please disregard.

Hi @RoganGrant I got the same error when running fit_models and plot_genes_in_pseudotime following the tutorial to construct the cds or download the tutorial dataset, not sure what cell_metadata I should check. Would you mind share the how did you fix the problem? Thanks!

**Comment by france-hub** [comment]
Hi @JPingLin I got the same error when running fit_models. Did you fix it?

**Comment by BrianLohman** [comment]
Hello @RoganGrant, @JPingLin, @france-hub

I'm having the same problem with fit_models(). What kind of "strange formatting" did you find in your cell__metadata? 

It looks like my data frames are formatted the same as the example data:
```
> head(pd)
                                     orig.ident nCount_RNA nFeature_RNA percent.mt treatment  cell_type         combined
donor1_fibroblast_AAACCCACAAACTAAG-1    16249X1      10254         3022         NA     donor fibroblast fibroblast_donor
donor1_fibroblast_AAACCCACACCGTGAC-1    16249X1      60732         7542         NA     donor fibroblast fibroblast_donor
donor1_fibroblast_AAACGAATCTAATTCC-1    16249X1      13884         3400         NA     donor fibroblast fibroblast_donor
donor1_fibroblast_AAAGGGCGTCAACGCC-1    16249X1       4124         1446         NA     donor fibroblast fibroblast_donor
donor1_fibroblast_AAAGGGCTCCATAGGT-1    16249X1       8598         2843         NA     donor fibroblast fibroblast_donor
donor1_fibroblast_AAAGTCCGTTCAACGT-1    16249X1       9855         2492         NA     donor fibroblast fibroblast_donor
> head(fd)
            gene_short_name
MIR1302-2HG     MIR1302-2HG
FAM138A             FAM138A
OR4F5                 OR4F5
AL627309.1       AL627309.1
AL627309.3       AL627309.3
AL627309.2       AL627309.2
> 
> 
> cell_metadata <- readRDS(url("http://staff.washington.edu/hpliner/data/cao_l2_colData.rds"))
> head(cell_metadata)
                        plate cao_cluster            cao_cell_type               cao_tissue
cele-001-001.CATGACTCAA   001          20     Unclassified neurons                  Neurons
cele-001-001.AAGACGGCCA   001           6                 Germline                    Gonad
cele-001-001.GCCAACGCCA   001          13 Intestinal/rectal muscle Intestinal/rectal muscle
cele-001-001.ATAGGAGTAC   001          27        Vulval precursors                     <NA>
cele-001-001.CTCGTCTAGG   001           2             Coelomocytes             Coelomocytes
cele-001-001.AAGTTGCCAT   001           6                 Germline                    Gonad
> 
> gene_annotation <- readRDS(url("http://staff.washington.edu/hpliner/data/cao_l2_rowData.rds"))
> head(gene_annotation)
               gene_short_name
WBGene00000001           aap-1
WBGene00000002           aat-1
WBGene00000003           aat-2
WBGene00000004           aat-3
WBGene00000005           aat-4
WBGene00000006           aat-5
```

and 
```
cds_subset = cds[rowData(cds)$cell_type == "fibroblast" ,]
gene_fits <- fit_models(cds_subset, model_formula_str = "~treatment")
```
returns:
```
Error in purrr::map(.f = purrr::possibly(extract_model_status_helper, : object 'model' not found
```
