### ISSUE TITLE
heuristic logic not executed for determining k for knn in multi_component_RGE 

### ISSUE THREAD

**Issue by manzt** [cole-trapnell-lab/monocle3#263]
There is some heuristic logic for determining `k` for kNN in the`multi_component_RGE` which is never executed. `k` is hard-coded to 25 which means that `RANN::nn2` is likely called with 25 always, rather than some value for k which depends on the number of cells in a given partition.

https://github.com/cole-trapnell-lab/monocle3/blob/9becd94f60930c2a9b51770e3818c194dd8201eb/R/learn_graph.R#L259-L269

**Comment by brgew** [comment]
Hi,
I believe that this is fixed in the Monocle3 develop branch on Github. You can install this using the command

devtools::install_github('https://github.com/cole-trapnell-lab/monocle3',ref='develop')

Please let me know if this does not address your request.

**Comment by hpliner** [comment]
Fixed in 0.2.2!
