### ISSUE TITLE
clear_cds_slots() still tries to use reducedDims slot

### ISSUE THREAD

**Issue by alex-wenzel** [cole-trapnell-lab/monocle3#268]
I have release v0.2.0 and am attempting to subset a CDS object and reset all of its slots with `clear_cds_slots()` The code

```R
cds_sig3 <- cds[cluster3_sig_genes,]
cds_sig3 <- clear_cds_slots(cds_sig3)
```
produced the error/traceback:

![image](https://user-images.githubusercontent.com/32204469/71045515-0cf46200-20ea-11ea-8425-9bc26dbd371d.png)

According to several recent issue threads (such as #259), `reducedDims` is no longer a valid slot name, but `clear_cds_slots()` still tries to reset it [here](https://github.com/cole-trapnell-lab/monocle3/blob/9becd94f60930c2a9b51770e3818c194dd8201eb/R/utils.R#L725). I'd submit a pull request for this but I'm not familiar enough with the code base to know what should go in place of that line, if anything.

**Comment by hpliner** [comment]
Thanks for the report. I just pushed a fix. If you can upgrade to develop using:
`devtools::install_github('cole-trapnell-lab/monocle3', ref="develop")` it should work now!
