### ISSUE TITLE
ahout the monocle3

### ISSUE THREAD

**Issue by zh-Bian** [cole-trapnell-lab/monocle3#269]
I met the same problem when I use teh source code to install the monocle3 for my online studio. It need the batchelor, then I try to install the barchelor by source code, it does not work. It requires the BiocSingular, but I was failed to install the BiocSingular through the Bioc or source code. Could you give me some advice? 
Thanks!
zh-Bian

**Comment by hpliner** [comment]
Thank you for submitting a bug report. Your report has insufficient information for us to address it. Please respond with the information requested in the bug report issue template. At minimum, please include: 

1. The code you ran that generated the error
2. The output of the call - and what was expected
3. The output of traceback()
4. The output of sessionInfo()

We will close this issue - when you answer with this further information, please reopen the issue.

- Monocle3 Dev Team
