### ISSUE TITLE
Monocle install failed

### ISSUE THREAD

**Issue by chenwf** [cole-trapnell-lab/monocle3#270]
**Describe the bug**
When install Monocle3 following "https://cole-trapnell-lab.github.io/monocle3/docs/installation/".
Failed at devtools::install_github("cole-trapnell-lab/monocle3")
**To Reproduce**
The code that produced the bug:
devtools::install_github("cole-trapnell-lab/monocle3")
Downloading GitHub repo cole-trapnell-lab/monocle3@master
Skipping 9 packages not available: Biobase, SingleCellExperiment, batchelor, BiocGenerics, DelayedArray, DelayedMatrixStats, limma, S4Vectors, SummarizedExperiment
Installing 7 packages: Matrix.utils, rsample, spdep, sf, classInt, units, e1071
trying URL 'https://cloud.r-project.org/src/contrib/Matrix.utils_0.9.7.tar.gz'
Content type 'application/x-gzip' length 9450 bytes
==================================================
downloaded 9450 bytes

trying URL 'https://cloud.r-project.org/src/contrib/rsample_0.0.5.tar.gz'
Content type 'application/x-gzip' length 303861 bytes (296 KB)
==================================================
downloaded 296 KB

trying URL 'https://cloud.r-project.org/src/contrib/spdep_1.1-3.tar.gz'
Content type 'application/x-gzip' length 1230873 bytes (1.2 MB)
==================================================
downloaded 1.2 MB

trying URL 'https://cloud.r-project.org/src/contrib/sf_0.8-0.tar.gz'
Content type 'application/x-gzip' length 8607770 bytes (8.2 MB)
==================================================
downloaded 8.2 MB

trying URL 'https://cloud.r-project.org/src/contrib/classInt_0.4-2.tar.gz'
Content type 'application/x-gzip' length 22054 bytes (21 KB)
==================================================
downloaded 21 KB

trying URL 'https://cloud.r-project.org/src/contrib/units_0.6-5.tar.gz'
Content type 'application/x-gzip' length 959970 bytes (937 KB)
==================================================
downloaded 937 KB

trying URL 'https://cloud.r-project.org/src/contrib/e1071_1.7-3.tar.gz'
Content type 'application/x-gzip' length 582517 bytes (568 KB)
==================================================
downloaded 568 KB

* installing *source* package ‘Matrix.utils’ ...
** package ‘Matrix.utils’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (Matrix.utils)
* installing *source* package ‘rsample’ ...
** package ‘rsample’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (rsample)
* installing *source* package ‘units’ ...
** package ‘units’ successfully unpacked and MD5 sums checked
** using staged installation
configure: units: 0.6-4
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ -std=gnu++11 accepts -g... yes
checking how to run the C++ preprocessor... g++ -std=gnu++11 -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdbool.h that conforms to C99... no
checking for _Bool... no
checking for error_at_line... yes
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for XML_ParserCreate in -lexpat... yes
checking udunits2.h usability... no
checking udunits2.h presence... no
checking for udunits2.h... no
checking udunits2/udunits2.h usability... no
checking udunits2/udunits2.h presence... no
checking for udunits2/udunits2.h... no
checking for ut_read_xml in -ludunits2... no
configure: error: in `/tmp/RtmpVrNE0A/R.INSTALL59415c81ba67/units':
configure: error:
--------------------------------------------------------------------------------
  Configuration failed because libudunits2.so was not found. Try installing:
    * deb: libudunits2-dev (Debian, Ubuntu, ...)
    * rpm: udunits2-devel (Fedora, EPEL, ...)
    * brew: udunits (OSX)
  If udunits2 is already installed in a non-standard location, use:
    --configure-args='--with-udunits2-lib=/usr/local/lib'
  if the library was not found, and/or:
    --configure-args='--with-udunits2-include=/usr/include/udunits2'
  if the header was not found, replacing paths with appropriate values.
  You can alternatively set UDUNITS2_INCLUDE and UDUNITS2_LIBS manually.
--------------------------------------------------------------------------------

See `config.log' for more details
ERROR: configuration failed for package ‘units’
* removing ‘/nas/chenwf/biosoft/R-3.6.0/lib/R/library/units’
Error: Failed to install 'monocle3' from GitHub:
  (converted from warning) installation of package ‘units’ had non-zero exit status

**Expected behavior**
Install monocle3 successfully

**sessionInfo():**
sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.4 LTS

Matrix products: default
BLAS:   /nas/chenwf/biosoft/R-3.6.0/lib/R/lib/libRblas.so
LAPACK: /nas/chenwf/biosoft/R-3.6.0/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3        magrittr_1.5      usethis_1.5.1     devtools_2.2.1                                                                                               
 [5] pkgload_1.0.2     R6_2.4.1          rlang_0.4.2       fansi_0.4.0                                                                                                  
 [9] tools_3.6.0       pkgbuild_1.0.6    sessioninfo_1.1.1 cli_2.0.0                                                                                                    
[13] withr_2.1.2       ellipsis_0.3.0    remotes_2.1.0     assertthat_0.2.1                                                                                             
[17] digest_0.6.23     rprojroot_1.3-2   crayon_1.3.4      processx_3.4.1                                                                                               
[21] callr_3.4.0       fs_1.3.1          ps_1.3.0          curl_4.3                                                                                                     
[25] testthat_2.3.1    memoise_1.1.0     glue_1.3.1        compiler_3.6.0                                                                                               
[29] desc_1.2.0        backports_1.1.5   prettyunits_1.0.2

**Comment by Jiam1ng** [comment]
Hi, I have encountered the same problem with installation, do you have any solution?

**Comment by SONGDONGYUAN1994** [comment]
I met the same problem. Do you find the solutions? Thanks!

**Comment by YinCY123** [comment]
me too, does any body solved?

**Comment by BioInfoUCI** [comment]
Same problem here. Has anyone solved this?
Thanks!

**Comment by Wenfei-Sun** [comment]
I have the exact problem, anyone sorted out?
Thanks!

**Comment by Brawni** [comment]
same problem here, anybody found the solution?

**Comment by GV20jsw** [comment]
Same problem here, can anyone that has solved this problem kindly post the solutions here?
