### ISSUE TITLE
cluster_cells giving different clusters each time it is run

### ISSUE THREAD

**Issue by seigfried** [cole-trapnell-lab/monocle3#277]
Hello I am trying to run this command in Monocle3

```
cds1 <- cluster_cells(cds, reduction_method = "UMAP", cluster_method = "leiden", resolution=0.00025)
cds1 <- learn_graph(cds1)
plot_cells(cds1,
                 color_cells_by = "cluster",
                 label_groups_by_cluster=F,
                 label_leaves=T,
                 label_branch_points=F,
                 label_cell_groups = F)
```

So basically I am running everything on the same object. However when I run the same command again I get a different plot/cluster/trajectory

For example:
![1](https://user-images.githubusercontent.com/20457676/72243289-82d6e500-3626-11ea-8470-68efa101dc5c.jpg)
and
![2](https://user-images.githubusercontent.com/20457676/72243313-8ec2a700-3626-11ea-9472-4dcca82869eb.jpg)

How do I ensure reproducibility of clusters? Thanks!

**Comment by RoganGrant** [comment]
This also appears to be an issue in `find_gene_modules`, even when the random seed is set manually and `louvain_iter = 1`

**Comment by orzechmag** [comment]
I am facing exactly the same issue. I observed also differences in results of Monocle when using two different computers - the same code, the same input data, the same settings, different computers (Mac and Ubuntu) = slightly different results of plotting cells in UMAP dimensions. I hope there is a solution to provide reproducibility of the results...

**Comment by amheck** [comment]
I have also run into this problem. Specifically, I noticed it when using find_gene_modules(). It appears something similar was brought up before (see issue #222 ), and may be an issue with Louvain clustering? However, according to the comments of that post, monocle3 v0.2.0 uses Leiden, which should have remedied this problem. Yet, the Help/Documentation window of find_gene_modules() suggests the function still uses Louvain.

My plan for now is to save the output of find_gene_modules() as an RDS file, and reload that for any future downstream analysis. However, this means any upstream analysis is set in stone.

**Comment by orzechmag** [comment]
Indeed, RDS file should be always saved, however all analytical tools should provide reproducibility of the results. The problem still exists and it seems that Louvain method is still applied.

And my primary results are gone forever...

**Comment by namitc** [comment]
I had been facing the same issue. I took a look at the cluster_cells code and found this snippet in the leiden clustering function.   

`if( random_seed == 0L )
    random_seed = NULL`

So, I set it to a value other than 0. Since then, I have been getting reproducible clusters.

**Comment by brgew** [comment]
Hi,
I am aware of at least two functions that can give differing results from run-to-run.
The first is reduce_dimension() when run with the (default) UMAP reduction method. I believe that you can (hopefully) make it deterministic by running it as
  reduce_dimension(cds,umap.fast_sgd = FALSE,cores=1)
The UWOT-UMAP documentation says that one needs to set n_sgd_threads=1  (the default is 0) so you may need to add it to the reduce_dimension call, for example
  reduce_dimension(cds,umap.fast_sgd = FALSE,cores=1,n_sgd_threads=1)
As namitc points out, the cluster_cells() function uses a random number generator, which you can 'seed' with a constant positive value using the random_seed parameter in the call to cluster_cells().
And it may be necessary to use the set.seed() function before running Monocle3.

**Comment by hpliner** [comment]
Looks like this is solved, if not, reopen

**Comment by TatyanaLev** [comment]
I had to also make sure that the number of cpu was the same between repeat runs on the hpc in addition to the same seed. Same seed alone wasn't enough if cpu amount differed.
