### ISSUE TITLE
Analysis of differentially expressed genes between two time points in Monocle

### ISSUE THREAD

**Issue by priyamnarain** [cole-trapnell-lab/monocle3#283]
Hi,

I have two time points for my analysis. Please can you guide me which code/script to use to split merged data of two time points to analyze the clusters and to find differentially expressed genes.

Thanks

**Comment by brgew** [comment]
Hi,

Please send questions to the google group rather than submitting them as issues. You can post to the group here:

https://groups.google.com/forum/#!forum/monocle-3-users
