### ISSUE TITLE
Failed to install monocle3

### ISSUE THREAD

**Issue by fly4all** [cole-trapnell-lab/monocle3#288]
I'm trying to install monocle3 in R, and ran into the following error:

```
Error: Failed to install 'monocle3' from GitHub:
  (converted from warning) package ‘Matrix.utils’ is not available (for R version 3.6.2)
```
I updated R to version 3.6.2 because it had previously told me that the package 'Batchelor' was unavailable for R version 3.5.1

Any help would be appreciated!

**Comment by SONGDONGYUAN1994** [comment]
I also met this problem. `Matrix.utils` has been removed from CRAN.

**Comment by charlotterich** [comment]
I got around this by using an archived version of Matrix.utils

`install.packages('devtools')`

`devtools::install_url('https://cran.r-project.org/src/contrib/Archive/Matrix.utils/Matrix.utils_0.9.7.tar.gz')`

The I was able to install monocle3 using
`devtools::install_github('cole-trapnell-lab/monocle3')`
