### ISSUE TITLE
error while installing leidenbase

### ISSUE THREAD

**Issue by pbpayal** [cole-trapnell-lab/monocle3#290]
> ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0'
> ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
> ld: library not found for -lgfortran
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *** [leidenbase.so] Error 1
> ERROR: compilation failed for package ‘leidenbase’
> * removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/leidenbase’
> Error: Failed to install 'leidenbase' from GitHub:
>   (converted from warning) installation of package ‘/var/folders/wn/y2nrczbn06q6xshmczn_s79h0000gn/T//RtmpA0CMc9/file1676b395bc6fe/leidenbase_0.1.0.tar.gz’ had non-zero exit status

**Comment by pbpayal** [comment]
> `─ Session info ───────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.2 (2019-12-12)
 os       macOS Mojave 10.14.6        
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/New_York            
 date     2020-02-03                  

─ Packages ───────────────────────────────────────────────────────────────────────
 package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.6.0)
 backports     1.1.5   2019-10-02 [1] CRAN (R 3.6.0)
 BiocManager   1.30.10 2019-11-16 [1] CRAN (R 3.6.0)
 callr         3.4.1   2020-01-24 [1] CRAN (R 3.6.0)
 cli           2.0.1   2020-01-08 [1] CRAN (R 3.6.0)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.0)
 curl          4.3     2019-12-02 [1] CRAN (R 3.6.0)
 desc          1.2.0   2018-05-01 [1] CRAN (R 3.6.0)
 devtools    * 2.2.1   2019-09-24 [1] CRAN (R 3.6.0)
 digest        0.6.23  2019-11-23 [1] CRAN (R 3.6.0)
 ellipsis      0.3.0   2019-09-20 [1] CRAN (R 3.6.0)
 fansi         0.4.1   2020-01-08 [1] CRAN (R 3.6.0)
 fs            1.3.1   2019-05-06 [1] CRAN (R 3.6.0)
 glue          1.3.1   2019-03-12 [1] CRAN (R 3.6.0)
 magrittr      1.5     2014-11-22 [1] CRAN (R 3.6.0)
 memoise       1.1.0   2017-04-21 [1] CRAN (R 3.6.0)
 pkgbuild      1.0.6   2019-10-09 [1] CRAN (R 3.6.0)
 pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.6.0)
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 3.6.0)
 processx      3.4.1   2019-07-18 [1] CRAN (R 3.6.0)
 ps            1.3.0   2018-12-21 [1] CRAN (R 3.6.0)
 R6            2.4.1   2019-11-12 [1] CRAN (R 3.6.0)
 Rcpp          1.0.3   2019-11-08 [1] CRAN (R 3.6.0)
 remotes       2.1.0   2019-06-24 [1] CRAN (R 3.6.0)
 rlang         0.4.4   2020-01-28 [1] CRAN (R 3.6.0)
 rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.6.0)
 rstudioapi    0.10    2019-03-19 [1] CRAN (R 3.6.0)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.6.0)
 testthat      2.3.1   2019-12-01 [1] CRAN (R 3.6.0)
 usethis     * 1.5.1   2019-07-04 [1] CRAN (R 3.6.0)
 withr         2.1.2   2018-03-15 [1] CRAN (R 3.6.0)

[1] /Library/Frameworks/R.framework/Versions/3.6/Resources/library`

**Comment by pbpayal** [comment]
which gfortran gives '/Users/../anaconda3/bin/gfortran"

**Comment by pbpayal** [comment]
Update-- got around this by installing a fresh version of gfortran from here - https://github.com/fxcoudert/gfortran-for-macOS/releases. I just installed their dmg file because I have MAC.

Also in my case I had to upgrade to R 3.6 from R 3.5 because other packages like 'hexbin’, ‘deldir' were not available for R 3.5.

Again after installing leidenbase, I got another error about Matrix.utils package while trying to install Monocle3. Someone else had posted this error before and I followed that by 
`devtools::install_url('https://cran.r-project.org/src/contrib/Archive/Matrix.utils/Matrix.utils_0.9.7.tar.gz')` 

Hope this is helpful for other users who get stuck with this particular error.

**Comment by stephanyfoster** [comment]
can you elaborate on how you installed- I receive an error stating
Warning in install.packages :
  package ‘~/Desktop/gfortran-6.1-ElCapitan.dmg’ is not available (for R version 3.6.1)

I have to use ElCapitan version because of my older mac --but it looks like you were able to install using R 3.6.2
