### ISSUE TITLE
Error working with 10x data

### ISSUE THREAD

**Issue by pbpayal** [cole-trapnell-lab/monocle3#291]
It is kind of impossible to work with 10x data on Monocle3. 
After I run load_cellranger_data, do I need to run new_cell_data_set, because when I am doing so it says your data is not a sparse matrix but your tutorial says 10x data is already a sparse matrix, not required to do anything. 
`cds <- load_cellranger_data("/..../outs/")`

`cds_1 <- new_cell_data_set(cds,cell_metadata = pData(cds),
                               gene_metadata = fData(cds))`

> Error: Argument expression_data must be a matrix - either sparse from the Matrix package or dense

Please update your tutorials, especially how to work with outside data like 10x and not the preloaded data.

**Comment by brgew** [comment]
Hi pbpayal,

I see that the Monocle3 web page does not state explicitly the type of object returned by the load_cellranger_data() function. Thank you for the feedback, we strive to improve our resources for users.

I want to point out that the Monocle3 distribution includes detailed help pages for the Monocle3 functions, including the load_cellranger_data() function. You can read these help pages using the commands

  > help( 'load_cellranger_data')

or

  > ?load_cellranger_data

The help page in this case states that this function returns 'a new cell_data_set object'. Wishing to verify this statement, I looked briefly at the load_cellranger_data() function code, using the command

  > load_cellranger_data
  .
  .
  .
    data <- data[, Matrix::colSums(data) > umi_cutoff]
    pd <- pd[colnames(data), , drop = FALSE]
    gbm <- new_cell_data_set(data, cell_metadata = pd, gene_metadata = feature.names)
    return(gbm)
}

So the documentation is correct.

Have you tried continuing with processing the CDS returned by load_cellranger_data() without trying to run new_cell_data_set() on it?

I appreciate your feedback.

Best Wishes,
brgew

**Comment by pbpayal** [comment]
Thank you. 

Let me tell you what I did step by step.

```
library(Matrix)
mat <- readMM(" path/10X/data")
feature.names = read.delim("/path/10X/data/outs/raw_feature_bc_matrix/features.tsv.gz", 
                           header = FALSE,
                           stringsAsFactors = FALSE)
barcode.names = read.delim("/path/10X/data/outs/raw_feature_bc_matrix/barcodes.tsv.gz", 
                           header = FALSE,
                           stringsAsFactors = FALSE)

library(Monocle3)
cds_final <- new_cell_data_set(mat,cell_metadata = barcode.names, gene_metadata = feature.names)
```

> Warning message:
In estimate_size_factors(cds) :
  Your CDS object contains cells with zero reads. This causes size factor calculation to fail. Please remove the zero read cells using cds <- cds[,Matrix::rowSums(exprs(cds)) != 0] and then run cds <- estimate_size_factors(cds)

When I followed exactly what the error told me, nothing improved. But in the above comment you mention Matrix::colSums(data), so I did that instead of Matrix::rowSums(data) as below and then it worked. 

```
cds_test <- cds_final[,Matrix::colSums(exprs(cds_final)) != 0]
cds_ult <- estimate_size_factors(cds_test)
cds_final <- preprocess_cds(cds_ult, num_dim = 30)
```

I don't know if its right, but this seemed to work till now without errors.

**Comment by brgew** [comment]
Hi pbpayal,

I think that you are right. My understanding is that the columns are cells, so removing columns that have zero counts seems correct to me. (I check the documentation, which tells me that the cell_data_set class is derived from the SingleCellExperiment class. The SingleCellExperiment class description includes
```
The SingleCellExperiment class is a light-weight container for single-cell genomics data. It extends the RangedSummarizedExperiment class and follows similar conventions, i.e., rows should represent features (genes, transcripts, genomic regions) and columns should represent cells.
```
We need to correct the error message.

I appreciate your feedback and patience.

Thank you.

Best Wishes,
brgew
