### ISSUE TITLE
Some dependencies not availible

### ISSUE THREAD

**Issue by Connorr0** [cole-trapnell-lab/monocle3#295]
I was reinstalling Monocle3 and discovered that Matrix.utils does not appear to be available anymore. 

```
Package ‘Matrix.utils’ was removed from the CRAN repository.

Formerly available versions can be obtained from the archive.

Archived on 2020-01-28 as check problems were not corrected despite reminders.
```

**Comment by zebasilio** [comment]
I am having the same issue. When trying to install Monocle3 got the following error:
Error: Failed to install 'monocle3' from GitHub:
  (converted from warning) package 'Matrix.utils' is not available (for R version 3.6.2)

**Comment by paul-shannon** [comment]
@Connorr0 @zebasilio 
The latest version of Matrix.utils, 0.9.7, available on the cran archive, installed cleanly for me:
````
    https://cran.r-project.org/src/contrib/Archive/Matrix.utils/Matrix.utils_0.9.7.tar.gz
````

after which ````devtools::install_github('cole-trapnell-lab/monocle3')```` completed - with one extra step required:

   - I am still running R version 3.6.1.
   - ````SummarizedExperiment```` from github is built with R 3.6.2
   - install_github promotes the resulting warning to an error
   - setting this environment variable in your shell *before* starting R leaves the warning as a warning:
````
export R_REMOTES_NO_ERRORS_FROM_WARNINGS="true" 
````

**Comment by cswoboda** [comment]
@paul-shannon Could you elaborate on this method a bit? I'm having issues with both installing the Matrix.utils and using your export command. I'm sorry I'm relatively new to R, but I've placed the export command into both my windows command prompt and get the resulting errors:

```
'export' is not recognized as an internal or external command operable program or batch file.

```
I have a previous version of Matrix.utils installed on my computer already, so I think if I could this method it should work for me. Thanks!

**Comment by cswoboda** [comment]
@paul-shannon @zebasilio @Connorr0 Hey I think I have a solution it just installed! Here's two commands I just put into my R window before the installation command that worked:
```
devtools::install.packages(https://cran.r-project.org/src/contrib/Archive/Matrix.utils/Matrix.utils_0.9.7.tar.gz)
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")
```

**Comment by hpliner** [comment]
Hi all, Matrix.utils is actually still available on Bioconductor, so we've just added it to the list of dependencies to install in the instructions using Bioconductor - this should at least be a temporary fix.

**Comment by hpliner** [comment]
Looks like Matrix.utils is back on CRAN, should be working now

**Comment by kmshort** [comment]
matrix.utils is off of CRAN again and not on bioconductor 3.15. You have to install from archive.

Monocle3 should move on from matrix.utils and find another stable alternative.

**Comment by Sayyam-Shah** [comment]
Hello @kmshort ,

How did you install it from the archive as I am also having trouble installing it with 3.14?

Bioconductor version 3.14 (BiocManager 1.30.18), R 4.1.2 (2021-11-01)
Installing package(s) 'Matrix.utils'
Warning: package ‘Matrix.utils’ is not available for Bioconductor version '3.14'

**Comment by kmshort** [comment]
Hi @Sayyam-Shah 
Just use devtools or remotes to install it, provide the direct web link to the file you want to install.

**Comment by Dragonmasterx87** [comment]
@Sayyam-Shah 

You can install it using `install.packages ` as well

`install.packages("https://cran.r-project.org/src/contrib/Archive/Matrix.utils/Matrix.utils_0.9.8.tar.gz", type = "source", repos = NULL)`

To check install run:
`packageVersion("Matrix.utils")`

Cheers

🐉
