### ISSUE TITLE
Is there a plan for getting this into Bioconductor?

### ISSUE THREAD

**Issue by LTLA** [cole-trapnell-lab/monocle3#300]
Is this in the roadmap? I would like to talk about Monocle in the OSCA book, and I don't want to have to deal with the old `CellDataSet` objects in the current Monocle 2.

I also have some other usability comments/requests, but those are kind of irrelevant if it's not going to (eventually) be a BioC or CRAN package.

**Comment by ctrapnell** [comment]
We are hoping to, but the main priority is to bring Monocle 3 out of beta. We are hopeful that will happen within the next couple of months.
