### ISSUE TITLE
Doc inconsistancy

### ISSUE THREAD

**Issue by liuyigh** [cole-trapnell-lab/monocle3#303]
On this page:
https://cole-trapnell-lab.github.io/monocle3/docs/clustering/

text says `clusters(cds)`, code uses `partitions(cds)`:

 To assign cell types based on clustering, we begin by creating a new column in colData(cds) and initialize it with the values of `clusters(cds)`:
```
colData(cds)$assigned_cell_type <- as.character(partitions(cds))
```

Is this a bug?

**Comment by hpliner** [comment]
Good catch, just updated the website. Thanks
