### ISSUE TITLE
Clarification needed on output of fit_models()

### ISSUE THREAD

**Issue by dtg9** [cole-trapnell-lab/monocle3#307]
I am doing a differential gene expression analysis for two conditions across every cell type in my dataset. I am seeing results that make sense from fit_models(), but it's rather unclear exactly what the output parameters in the coefficient table are. 

Having fit the models and extracted the coefficients table, the parameters I'm most interested in are the q_value and fold change for each gene. Is the "estimate" parameter in the coefficient table the log fold change of the gene? Or is it the "normalized_effect" parameter? And what scale is it on? I would normally assume log2 in this context but it's not in the documentation and the explanation at https://cole-trapnell-lab.github.io/monocle3/docs/differential/ never explicitly says it one way or another.)

I feel that each of the output parameters should be explained more clearly in the fit_models() or coefficient_table() documentation.

**Comment by brgew** [comment]
Hi,

The normalize_effect parameter may be the one you want. It's the log2 fold change for each change, normalized by the intercept.

Thank you for pointing out the imprecision in the documentation.

**Comment by bschilder** [comment]
I agree this should be added to the documentation (took me a while to find this answer).
Could an explanation of each column be added somewhere? (esp. test_val, estimate, and normalized_effect).

Thanks!
