### ISSUE TITLE
Trouble exporting CDS to seurat object 

### ISSUE THREAD

**Issue by skim245** [cole-trapnell-lab/monocle3#308]
I have been trying to export my CDS file to Seurat object using below code 

my.data <- as.Seurat(my.cds, slot = "counts", assay = "RNA", verbose = TRUE)

-and getting below errors -

Pulling expression data
Building Seurat object
Adding feature-level metadata
Adding dispersion information
Setting variable features
Adding DDRTree dimensional reduction
Error in dimnames(x) <- dn : 
  length of 'dimnames' [2] not equal to array extent

- are there anyways to manually extract files and re-create Seurat object? 

Thank you in advance!

**Comment by lsaund11** [comment]
try something like this:

count.mat = assay(my.cds)
meta.df = as.data.frame(colData(my.cds))

my.seurat = CreateSeuratObject(counts = count.mat,
                                 project = "my.project",
                                 assay = "RNA",
                                 meta.data = meta.df)

**Comment by skim245** [comment]
after running the codes, I'm getting below errors 

count.mat = assay(my.cds)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘assay’ for signature ‘"CellDataSet", "missing"’

meta.df = as.data.frame(colData(my.cds))
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘colData’ for signature ‘"CellDataSet"’

**Comment by lsaund11** [comment]
It looks like you're using a cds generated in an older version of monocle. If that's the case, you should be able to extract the count matrix using `Biobase::exprs(my.cds)` and `Biobase::pData(my.cds)` to extract the meta data.
