### ISSUE TITLE
order_cells Error in utils::browseURL(appUrl)

### ISSUE THREAD

**Issue by WellJoea** [cole-trapnell-lab/monocle3#309]
order_cells (cds)
error：

Listening on http://127.0.0.1:6785
Error in utils::browseURL(appUrl) : 
  'browser' must be a non-empty character string

**Comment by brgew** [comment]
Hi,

I need additional information about the conditions that led to this problem; please include the information requested. Also could you tell me please if you are running Monocle3 in another program such as JupyterNotes or Rstudio.

Thank you.

**Comment by WellJoea** [comment]
thank you very much! I found the problem. It is my fault.

**Comment by chris-mcginnis-ucsf** [comment]
I'm getting the same error. I'm running monocle in Rstudio in a conda virtual environment.

**Comment by liuxl18-hku** [comment]
@chris-mcginnis-ucsf ,

I got the same error, I think the reason is because I ran R session (interactively, `interactive()` returns `TRUE`) through ssh from remote server.

By default, `order_cell()` allows u pick root cell interactively while running it when the function detected you are running a interactive R session. The problem is, running interactive R session doesn't mean we have an interactive Internet Browser available (like my case). Therefore, when `order_cell` bring me to the function `select_trajectory_roots` which, I assume, allows me to choose the root cell, the error popped up.

```r
# by default, root_pr_nodes & root_cells are both NULL
if (is.null(root_pr_nodes) & is.null(root_cells)) {
        if (interactive()) {
            root_pr_nodes <- select_trajectory_roots(cds, reduction_method = reduction_method)
            if (length(root_pr_nodes) == 0) {
                stop("No root node was chosen!")
            }
        }
    }
```

I got rid of this error by setting `root_cells` to a bunch of stem cells in my case.

bless~

**Comment by WellJoea** [comment]
if you use the command "utils::browseURL("http://google.com/")", and then get the same error：

  ```
Error in utils::browseURL("http://google.com/") : 
  'browser' must be a non-empty character string
utils::browseURL("http://google.com/", browser = '/usr/bin/firefox')
  ```

If setting the brower path as follows,  the error is disappeared. You can set the option of brower path in R.

```
utils::browseURL("http://google.com/", browser = '/usr/bin/firefox')
```

```
options(browser="firefox")
utils::browseURL("http://google.com/")
```

**Comment by zhenzuo2** [comment]
Hi, I got the same error when` running order_cells(cds)` in the R command line. The Linux system I used does not support interactive visualization. Can I run this function without installing a browser? Thank you.

**Comment by juanprimate** [comment]
> for me worked that, i worked in linux or manjaro



> options(browser="brave")
utils::browseURL("http://google.com/")

**Comment by tbazilegith** [comment]
> Hi,
> 
> I need additional information about the conditions that led to this problem; please include the information requested. Also could you tell me please if you are running Monocle3 in another program such as JupyterNotes or Rstudio.
> 
> Thank you.

I got same error using jupyter notebook :
R[write to console]: 
Listening on http://127.0.0.1:4546

R[write to console]: Error in utils::browseURL(appUrl) : 
  'browser' must be a non-empty character string

I tried this: utils::browseURL("http://google.com/", browser = 'C:\Program Files\Google\Chrome\Application\chrome.exe') didn't work. 
Any ideas?
Thanks!
