### ISSUE TITLE
No trajectory to plot. Has learn_graph() been called yet?

### ISSUE THREAD

**Issue by zimmermk1986** [cole-trapnell-lab/monocle3#310]
Hello,
I am trying to use monocle3 to generate single cell trajectory data from a Seurat v3 object. I load the data in with:
> expression_matrix <- res@assays$RNA@counts
> cell_metadata <- res@meta.data[,1:8]
> gene_metadata <- res@assays$RNA@counts@Dimnames[[1]]
> gene_df <- data.frame(ids = gene_metadata, row.names = gene_metadata)
> cds <- new_cell_data_set(expression_matrix, cell_metadata = cell_metadata, gene_metadata = gene_df)
Warning message:
In new_cell_data_set(expression_matrix, cell_metadata = cell_metadata,  :
  Warning: gene_metadata must contain a column verbatim named 'gene_short_name' for certain functions.

I pre-process the data, reduce dimensions, and plot using my original Seurat clusters built in to the metadata. 
> cds <- preprocess_cds(cds, num_dim = 100)
> plot_pc_variance_explained(cds)
> cds <- reduce_dimension(cds)
No preprocess_method specified, using preprocess_method = 'PCA'

I plot my cells with:
plot_cells(cds, label_groups_by_cluster=FALSE,  color_cells_by = "seurat_clusters")
No trajectory to plot. Has learn_graph() been called yet?

Why am I getting this error? If I continue with the scripts according to the monocle3 website, I continue to get this error.

**Comment by hpliner** [comment]
This is not an error, it's just a message telling you that plot_cells won't be able to plot a trajectory because you haven't called learn_graph yet. You can set `show_trajectory_graph = FALSE` and then you won't get that message.
