### ISSUE TITLE
principal graph is too large. order_cells doesn't support more than 10 thousand centroids.

### ISSUE THREAD

**Issue by panxiaoguang** [cole-trapnell-lab/monocle3#313]
** If this is a question and not a bug report or enhancement request, please post to our google group at https://groups.google.com/forum/#!forum/monocle-3-users**

**Describe the bug**

**To Reproduce**
The code that produced the bug:

**traceback()**
After the error, run traceback() in R and post the output:

**Expected behavior**

**Screenshots**

**sessionInfo():**
Run sessionInfo() in R and post the output

**Additional context**

**Comment by hpliner** [comment]
Thank you for submitting a bug report. Your report has insufficient information for us to address it. Please respond with the information requested in the bug report issue template. At minimum, please include: 

1. The code you ran that generated the error
2. The output of the call - and what was expected
3. The output of traceback()
4. The output of sessionInfo()

We will close this issue - when you answer with this further information, please reopen the issue.

- Monocle3 Dev Team
