### ISSUE TITLE
A question RE p/qvalues output by graph_test function

### ISSUE THREAD

**Issue by simonewebb** [cole-trapnell-lab/monocle3#314]
Hi, 

I am using monocle3 and getting some great results - thanks for your development of this valuable resource.

I have a question - when running the graph_test I get some (v. few) pvalues and qvalues returned as 0. I assume there is a cut-off for small values, which will automatically convert them to 0. Is this correct? If so, could you let me know what this threshold is?

Thank you

Simone

**Comment by brgew** [comment]
Hi,

I looked at the graph_test() function and see no explicit operation that truncates small values to zero, which does not mean that functions called by graph_test() do not truncate values although I think it's unlikely that any do. The likely explanation is that the values are smaller than the value that can be represented by a real value by your processor and software. The R command `.Machine` reports various characteristics of the machine on which you run R. The one called $double.xmin is most likely the one that's relevant here. The R help page for .Machine says that $double.xmin is

> the smallest non-zero normalized floating-point number, a power of the radix, i.e., double.base ^ double.min.exp. Normally 2.225074e-308.

It's also possible that the command you use to view the pvalues and qvalues is truncating them but I think that that is unlikely if the command can represent real values in scientific notation.

Does this sound reasonable? Or are you noticing evidence that values larger than $double.xmin may be truncated?

**Comment by simonewebb** [comment]
Hi, 

Thanks for your response, this has greatly helped clarify matters.

I see values displayed that are very close to my system Machine$double.xmin (of 2.225074e-308), so no evidence that these are further truncated. 

I'm now happy that there is no wider error with my running of graph_test()

Keep well!
