### ISSUE TITLE
Top marker gene function , possible bug

### ISSUE THREAD

**Issue by stefanonard85** [cole-trapnell-lab/monocle3#316]
Hello, 

I am having this error when I run the top markers gene function. I do not know if it is a bag or maybe my mistake . can you check please? I have attached few screenshots with the info.
<img width="591" alt="Capture" src="https://user-images.githubusercontent.com/16965990/78365783-993d6e80-758d-11ea-92f3-240d5483748f.PNG">
<img width="466" alt="Capture2" src="https://user-images.githubusercontent.com/16965990/78366035-ec172600-758d-11ea-867d-4f7b7a3ee52b.PNG">
<img width="450" alt="Capture3" src="https://user-images.githubusercontent.com/16965990/78366040-ede0e980-758d-11ea-9e08-8d540d6e1e89.PNG">

**Comment by hpliner** [comment]
Can you confirm that your rowData and colData both have rownames assigned?

**Comment by henrique-a** [comment]
Hello,

I'm having the same error. I have a `cds@colData@rownames` but I don't have a `rowData` in my cds. What should I do?

I got this cds by using the function 
`load_mm_data(mat_path = "matrix.mtx", 
                    feature_anno_path = "genes.tsv", 
                    cell_anno_path = "barcodes.tsv")`.

**Comment by aypatel0** [comment]
I am in the same situation as @henrique-a. I don't see a rowData in my cds. My colData has rownames assigned. However, I created the cds from a Seurat object using the following steps:

for the expression matrix:
`expression_matrix <- all_integrated@assays$RNA@counts`
for the metadata:
`cells <- all_integrated@meta.data[,c(2:6, 9)]`
for the gene list:
` genes <- all_integrated@assays$RNA@counts@Dimnames[[1]]`
` gene_df <- data.frame(ids = genes, row.names = genes)`

**Comment by brgew** [comment]
Hi @henrique-a @aypatel0,

I am guessing that you are looking for a slot in the cds called 'rowData'. Unintuitively, there is not one. 

In R's S4 object oriented programming model, the slots are considered to be an internal implementation, and are accessed using getter/setter methods. In this case, these methods are called _rowData_, so you access the row metadata with

`rowData(cds)
`

This should return/assign a dataframe with the row data.

Incidentally, the row data slot and accessor functions are defined in the Bioconductor SingleCellExperiment class, which the cell_data_set class inherits.

Please let me know if I misunderstand the issue.

**Comment by aypatel0** [comment]
@brgew when I call those functions, this is what I get. Do you know why I'm getting this error?
![image](https://user-images.githubusercontent.com/66456625/84452240-27774600-ac0a-11ea-9ea6-21684c23788d.png)
![image](https://user-images.githubusercontent.com/66456625/84452419-9fde0700-ac0a-11ea-8581-8d77ae80917e.png)

**Comment by henrique-a** [comment]
> Please let me know if I misunderstand the issue.

Yes @brgew , the main issue is that the function `top_markers` is throwing that error `Error: Can't rename columns that don't exist. x Column `rowname` doesn't exist.` 

We asked about  rowData because @hpliner asked

> Can you confirm that your rowData and colData both have rownames assigned?

Now that we know how to access rowData, the answer is YES. Still, the function is throwing that error.

**Comment by parulvarma** [comment]
@henrique-a 
I am new to monocle3 and also new to the entire computing world. I also ran into this issue of
Error: Can't rename columns that don't exist. x Column rowname doesn't exist.
After reading and researching, I found that all I had to really do was to add a line which helped in labeling the gene column of the feature data.
I started with this:
cds <- load_mm_data(mat_path = "~/Downloads/matrix.mtx", 
                    feature_anno_path = "~/Downloads/features.tsv", 
                    cell_anno_path = "~/Downloads/barcodes.tsv")
and then I added this:
#rename gene symbol column
names(fData(cds)) <- c('id', 'gene_short_name')

and followed the code till marker genes
marker_test_res <- top_markers(cds, group_cells_by="partition", 
                               reference_cells=1000, cores=8)
And it ran smoothly without giving any error. 

I am hoping this will help someone with the same issue.

**Comment by henrique-a** [comment]
@parulvarma it works, thank you very much

**Comment by brgew** [comment]
Hi,
I believe that this is fixed now in the develop branch.
Please reopen this if the problem persists.
