### ISSUE TITLE
"row.names of cell_metadata must be equal to colnames of expression_data"

### ISSUE THREAD

**Issue by Seandelao** [cole-trapnell-lab/monocle3#319]
Hello, 

I am trying to create a cds from an integrated Seurat object but am getting an error that I haven't seen before... 

I try to run the following code: 
exprs_human<- GetAssayData(seur_ob_human, slot="counts", assay = "RNA")
pheno.data_human = seur_ob_human@meta.data
genes_human <- data.frame(gene_short_name = rownames(exprs_human))
rownames(genes_human) <- rownames(exprs_human)
cds_human <- new_cell_data_set(exprs_human,
                               cell_metadata = pheno.data_human,
                               gene_metadata = genes_human)

to which I then get the error: "row.names of cell_metadata must be equal to colnames of expression_data"

Running 
"identical(rownames(pheno.data_human),colnames(exprs_human))" = FALSE, 
but 
setdiff(rownames(pheno.data_human),colnames(exprs_human))
setdiff(colnames(exprs_human),rownames(pheno.data_human))
both return zeros. 

I theoretically know what the error is telling me, I just don't understand where the error could be coming from. I have run the exact same code on other Seurat objects and it has worked fine. Anyone have any ideas?

**Comment by Seandelao** [comment]
@hpliner worked, thank you!

**Comment by Yale73** [comment]
@hpliner I ran the same issue and changed the order as your suggestion, but I got a new error:
`Error in cell_metadat[colnames(exp_mat), ] : subscript out of bounds`

My code is 
```
human_human_big_cds <- new_cell_data_set(exp_mat,
                                         cell_metadata = cell_metadat,
                                         gene_metadata = gene_annot)
```
, and I am sure the `colnames(exp_mat)` is the same as the `rownames(cell_metadat)`.

![image](https://user-images.githubusercontent.com/50378244/143385650-c87e5a54-2237-4d9b-9460-da8bd22c70ff.png)

Can you help me with it?

Thanks,
Yale
