### ISSUE TITLE
Add function to extract cells along a path of the principal graph

### ISSUE THREAD

**Issue by ctrapnell** [cole-trapnell-lab/monocle3#32]
Users should have an easy way to pull out the cells along a lineage of interest. The old monocle3_alpha had a nice function for this: traverseGraphCDS().

**Comment by hpliner** [comment]
@ctrapnell isn't this choose_graph_segments?

**Comment by ctrapnell** [comment]
Yes, and it works great. Just need to deal with #58 now.
