### ISSUE TITLE
Looped trajectories

### ISSUE THREAD

**Issue by namitc** [cole-trapnell-lab/monocle3#327]
Hi,

I'm analyzing a dataset and am seeing a looped trajectory where a node branches off but later merges at another node to form a closed loop. Am I doing something wrong? I didn't do anything different from the tutorial. I'm not sure how to interpret this trajectory.

**Comment by brgew** [comment]
Hi @namitc,
The Monocle3 learn_graph() function can report loops in the trajectory. A loop represents cells that diverge and converge later in time. This may be due to a biological event or to something like random count variations, so it is important to look at the cells' expression values.
