### ISSUE TITLE
How to choose root cells programmatically?

### ISSUE THREAD

**Issue by pbpayal** [cole-trapnell-lab/monocle3#328]
Hi,

How to choose root cells programmatically in a cluster? 
The tutorial is good but very experiment specific. Mine is not a time series experiment. Its an exploratory analysis. 

Also whats the difference between root_pr_nodes and root_cells for the function order_cells?

Thanks,
Payal

**Comment by diazdc** [comment]
I'm not on the development team but perhaps I can try to help you. In the tutorial there's a function that looks like the following:
 
    get_earliest_principal_node <- function(cds, time_bin="130-170"){
      cell_ids <- which(colData(cds)[, "embryo.time.bin"] == time_bin)
  
      closest_vertex <-
      cds@principal_graph_aux[["UMAP"]]$pr_graph_cell_proj_closest_vertex
      closest_vertex <- as.matrix(closest_vertex[colnames(cds), ])
      root_pr_nodes <-
        igraph::V(principal_graph(cds)[["UMAP"]])$name[as.numeric(names
       (which.max(table(closest_vertex[cell_ids,]))))]
  
      root_pr_nodes
    }
    cds <- order_cells(cds, root_pr_nodes=get_earliest_principal_node(cds))

Replace `"embryo.time.bin"` with the column name of your clusters. And then the argument for `time_bin=` will be the cluster name for your root population, or your hypothetical "stem cells".

**Comment by pbpayal** [comment]
Thank you!
That actually worked. Only my pseudotime graph is limited to just one cluster, as I can choose only one node.
`learn_graph(cds, use_partition = FALSE)`

![normox_pseudotime_without_partition](https://user-images.githubusercontent.com/20340380/81604889-a0327a80-939e-11ea-8d9c-b25665d0f462.png)

When I do this,
`learn_graph(cds, use_partition = TRUE)`
I can choose more than one node. For now I am manually clicking on the branch nodes (black circles) for each cluster and then I get segregated pseudotime graph.
![pseudotime_with_partition](https://user-images.githubusercontent.com/20340380/81605298-3ff00880-939f-11ea-9108-ae6f03c19122.png)

Can I also choose nodes programmatically for each cluster?

**Comment by diazdc** [comment]
Ah yes, I ran into that same problem. There's another issue that describes it somewhere around here. What you need to do use a single partition for your graph. Keep `learn_graph(cds, use_partition = FALSE)` and run this code _beforehand_:

    # find all possible partitions
    all_partitions <- unique(cds@clusters$UMAP$partitions)
    all_partitions <- all_partitions[all_partitions != "1"]
    
    # set all partitions to 1
    cds@clusters$UMAP$partitions[cds@clusters$UMAP$partitions %in% all_partitions] <- "1"

Hopefully the tutorial will be updated to describe how partitioning affects the graph, because it causes quite a bit of confusion when your populations are disconnected and you'd like to make trajectory that connects them.

**Comment by pbpayal** [comment]
Thank you very much. I was stuck at this for so long. That makes more sense. The tutorials should definitely update these.

Here I chose just one starting point.
![Normox_pseudotime_1](https://user-images.githubusercontent.com/20340380/81698797-7cba0f00-9434-11ea-942f-8fa7ad731f77.png)

But I can choose more than 1 starting point now. As there are more than 1 cluster that can be progenitor cells.

**Comment by Tushar-87** [comment]
> I'm not on the development team but perhaps I can try to help you. In the tutorial there's a function that looks like the following:
> 
> ```
> get_earliest_principal_node <- function(cds, time_bin="130-170"){
>   cell_ids <- which(colData(cds)[, "embryo.time.bin"] == time_bin)
> 
>   closest_vertex <-
>   cds@principal_graph_aux[["UMAP"]]$pr_graph_cell_proj_closest_vertex
>   closest_vertex <- as.matrix(closest_vertex[colnames(cds), ])
>   root_pr_nodes <-
>     igraph::V(principal_graph(cds)[["UMAP"]])$name[as.numeric(names
>    (which.max(table(closest_vertex[cell_ids,]))))]
> 
>   root_pr_nodes
> }
> cds <- order_cells(cds, root_pr_nodes=get_earliest_principal_node(cds))
> ```
> 
> Replace `"embryo.time.bin"` with the column name of your clusters. And then the argument for `time_bin=` will be the cluster name for your root population, or your hypothetical "stem cells".

Hi,
where can I find column name for cluster information? Further, can I write cluster number (clusters have not been named yet) in the time_bin arguement?

I tried following code, it gave me an error incorrect number of dimensions:
`get_earliest_principal_node <- function(cds3, time_bin = "3"){
    cell_ids <- which(clusters(cds3)[, "UMAP"] == time_bin)
    
    closest_vertex <-
        cds3@principal_graph_aux[["UMAP"]]$pr_graph_cell_proj_closest_vertex
    closest_vertex <- as.matrix(closest_vertex[colnames(cds3), ])
    root_pr_nodes <-
        igraph::V(principal_graph(cds3)[["UMAP"]])$name[as.numeric(names
                                                                  (which.max(table(closest_vertex[cell_ids,]))))]
    
    root_pr_nodes
}`
