### ISSUE TITLE
Impossible to install new monocle monocle with R 3.6.1

### ISSUE THREAD

**Issue by DirtyHarry80** [cole-trapnell-lab/monocle3#331]
Cannot install monocle using R Studio under R 3.6.1.

I am getting the following error:

Error: (converted from warning) package ‘SummarizedExperiment’ was built under R version 3.6.2
Execution halted
ERROR: lazy loading failed for package ‘monocle3’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/monocle3’
Error: Failed to install 'monocle3' from GitHub:
  (converted from warning) installation of package ‘/var/folders/r3/q936zqs53ml5cbnk24zjb85h0000gp/T//Rtmp4TfnZz/file3c5788df322/monocle3_0.2.1.tar.gz’ had non-zero exit status

**Comment by hpliner** [comment]
We've had a couple of reports of this and found that reinstalling SummarizedExperiment `BiocManager::install('SummarizedExperiment')` followed by reinstalling monocle3 `devtools::install_github('cole-trapnell-lab/monocle3')` sometimes resolves this. Can you give that a try?

**Comment by regan-hamel** [comment]
I have the same error and unfortunately was not able to resolve it by reinstalling SummarizedExperiment.

**Comment by DirtyHarry80** [comment]
Did not work for me either, will give up and try another script that can calculate pseudotime.

**Comment by regan-hamel** [comment]
After reinstalling R 3.6.3 I was able to install monocle3

**Comment by DirtyHarry80** [comment]
OK but R 3.6.3 is not required officially for the monocle 3. In an ongoing project it is very disturbing to change the version of R to solve one issue and then encounter hundreds of others...

**Comment by hpliner** [comment]
Can you confirm that you reinstalled monocle3 after reinstalling summarizedExperiment? (order matters). If so, is your Bioconductor install valid? i.e. BiocManager::valid() comes back TRUE?

**Comment by DirtyHarry80** [comment]
Did all that (its TRUE) and then got every-time this after trying to install monocle as last step:
Error: (converted from warning) package ‘SummarizedExperiment’ was built under R version 3.6.2
Execution halted
ERROR: lazy loading failed for package ‘monocle3’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/monocle3’
Error: Failed to install 'monocle3' from GitHub:
  (converted from warning) installation of package ‘/var/folders/r3/q936zqs53ml5cbnk24zjb85h0000gp/T//RtmpRo4wVI/filef6de1ec4533b/monocle3_0.2.1.tar.gz’ had non-zero exit status

**Comment by DirtyHarry80** [comment]
By the way I am running following R version:

platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          6.1                         
year           2019                        
month          07                          
day            05                          
svn rev        76782                       
language       R                           
version.string R version 3.6.1 (2019-07-05)
nickname       Action of the Toes

**Comment by hpliner** [comment]
@DirtyHarry80 Are you able to load SummarizedExperiment separately? i.e. library(SummarizedExperiment)

**Comment by hpliner** [comment]
And can you post your sessionInfo()

**Comment by Yunxiu123** [comment]
I also got this issue. And I think I'm able to load the  SummarizedExperiment.

Here is the information:
> library(SummarizedExperiment)
> devtools::install_github('cole-trapnell-lab/monocle3')
Downloading GitHub repo cole-trapnell-lab/monocle3@master
Skipping 9 packages not available: Biobase, SingleCellExperiment, batchelor, BiocGenerics, DelayedArray, DelayedMatrixStats, limma, S4Vectors, SummarizedExperiment
✓  checking for file ‘/private/var/folders/xq/htw0h9qd4pndpgpdvslvp7_00000gn/T/RtmpIbfMoq/remotes98531cfa4172/cole-trapnell-lab-monocle3-1a02274/DESCRIPTION’ (554ms)
─  preparing ‘monocle3’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts (424ms)
─  checking for empty or unneeded directories
─  building ‘monocle3_0.2.1.tar.gz’
   
* installing *source* package ‘monocle3’ ...
** using staged installation
** libs
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c clustering.cpp -o clustering.o
clang++ -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o monocle3.so RcppExports.o clustering.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/3.6/Resources/library/00LOCK-monocle3/00new/monocle3/libs
** R
** inst
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package ‘SummarizedExperiment’ was built under R version 3.6.2
Execution halted
ERROR: lazy loading failed for package ‘monocle3’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/monocle3’
Error: Failed to install 'monocle3' from GitHub:
  (converted from warning) installation of package ‘/var/folders/xq/htw0h9qd4pndpgpdvslvp7_00000gn/T//RtmpIbfMoq/file9853527d57a2/monocle3_0.2.1.tar.gz’ had non-zero exit status

**Comment by hpliner** [comment]
Can you try setting this environment variable and then see if the remainder of the installation is successful? `Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")`

**Comment by DirtyHarry80** [comment]
Hi, I can load the "summarized" library but I get following warning messages at the end:

Warning messages:
1: package ‘SummarizedExperiment’ was built under R version 3.6.2 
2: package ‘S4Vectors’ was built under R version 3.6.3 
3: package ‘IRanges’ was built under R version 3.6.2 
4: package ‘GenomeInfoDb’ was built under R version 3.6.3 
5: package ‘DelayedArray’ was built under R version 3.6.3 
6: package ‘BiocParallel’ was built under R version 3.6.2 

session info:

R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods  
[9] base     

other attached packages:
 [1] SummarizedExperiment_1.16.1 DelayedArray_0.12.3        
 [3] BiocParallel_1.20.1         matrixStats_0.56.0         
 [5] Biobase_2.46.0              GenomicRanges_1.38.0       
 [7] GenomeInfoDb_1.22.1         IRanges_2.20.2             
 [9] S4Vectors_0.24.4            BiocGenerics_0.32.0        

loaded via a namespace (and not attached):
 [1] lattice_0.20-41        bitops_1.0-6           grid_3.6.1            
 [4] zlibbioc_1.32.0        XVector_0.26.0         Matrix_1.2-18         
 [7] tools_3.6.1            RCurl_1.98-1.2         compiler_3.6.1        
[10] GenomeInfoDbData_1.2.2

**Comment by hpliner** [comment]
Ok, so it looks like you have bioconductor 3.10 installed which is matched to later versions of R 3.6 (3.9 would be matched with 3.6.1). A couple of options... Downgrade your bioconductor to 3.9, upgrade your R to 3.6.3 (of 4 for that matter), or (easiest) set the environmental variable as shown above so that the Bioconductor warnings don't cause installation to error

**Comment by Yunxiu123** [comment]
> `Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")`

Thanks a lot. It works out.hahahah.....

**Comment by ishrat98** [comment]
I reinstalled summarizedExperiment 
still the same error-Error: Failed to install 'monocle3' from GitHub:
  (converted from warning) installation of package ‘C:/Users/AppData/Local/Temp/RtmpC6Bh4u/file155c411337b5/monocle3_0.2.3.0.tar.gz’ had non-zero exit status

**Comment by ncedi12** [comment]
Please assist, I'm having trouble downloading Monocle3.. I use the following code to install
devtools::install_github('cole-trapnell-lab/leidenbase')
devtools::install_github('cole-trapnell-lab/monocle3')


And this is the error I get
ERROR: dependency ‘leidenbase’ is not available for package ‘monocle3’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/monocle3’
Warning messages:
1: In i.p(...) :
  installation of package ‘/var/folders/z_/4dkjn12140n0hywjwxf06gdc0000gn/T//Rtmpfp76wX/file81d56855167d/leidenbase_0.1.3.tar.gz’ had non-zero exit status
2: In i.p(...) : installation of package ‘terra’ had non-zero exit status
3: In i.p(...) :
  installation of package ‘/var/folders/z_/4dkjn12140n0hywjwxf06gdc0000gn/T//Rtmpfp76wX/file81d54e3869ec/monocle3_1.0.0.tar.gz’ had non-zero exit status



It is becoming impossible..
Assistance please

**Comment by ncedi12** [comment]
I'm on a Mac
