### ISSUE TITLE
Randomness of function find_gene_modules

### ISSUE THREAD

**Issue by boasong** [cole-trapnell-lab/monocle3#333]
The find_gene_modules function will get different results every time it runs, even if we set the random_seed parameter or set the number of seeds through set. Seed().
We are confused about it. 
Thank you very much.

**Comment by brgew** [comment]
Hi,
This is fixed in the Monocle3 develop branch. You can install it using the command

  devtools::install_github('cole-trapnell-lab/monocle3', ref="develop")
