### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by juan-quintana2020** [cole-trapnell-lab/monocle3#338]
Hi, 

I have been trying to install Monocle3 since yesterday and it keeps giving me the following errors for Leidenbase and monocle3:

configure: error: gdal-config not found or not executable.
ERROR: configuration failed for package ‘sf’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/sf’
Error: Failed to install 'sf' from GitHub:
  (converted from warning) installation of package ‘/var/folders/7n/nplwr83d51n5zw20jq8ckjzm0000gn/T//RtmpByH0Wh/file49d70e73773/sf_0.9-3.tar.gz’ had non-zero exit status

make: gfortran: No such file or directory
make: *** [cigraph/src/AMD/Source/amd.o] Error 1
ERROR: compilation failed for package ‘leidenbase’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/leidenbase’
Error: Failed to install 'monocle3' from GitHub:
  Failed to install 'leidenbase' from GitHub:
  (converted from warning) installation of package ‘/var/folders/7n/nplwr83d51n5zw20jq8ckjzm0000gn/T//RtmpByH0Wh/file49d5b1cf697/leidenbase_0.1.0.tar.gz’ had non-zero exit status

I tried installing sf as recommended on the website, and got the following error:
configure: error: gdal-config not found or not executable.
ERROR: configuration failed for package ‘sf’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/sf’
Error: Failed to install 'sf' from GitHub:
  (converted from warning) installation of package ‘/var/folders/7n/nplwr83d51n5zw20jq8ckjzm0000gn/T//RtmpByH0Wh/file49d70e73773/sf_0.9-3.tar.gz’ had non-zero exit status

**Comment by hpliner** [comment]
Have you installed gdal according to the sf website? https://r-spatial.github.io/sf/ for example on macs, it can be installed using homebrew with 
```
brew install pkg-config
brew install gdal
```

**Comment by parsboy66** [comment]
hi i got error in installation 
Error: (converted from warning) package ‘Matrix’ was built under R version 3.6.2
Execution halted
ERROR: lazy loading failed for package ‘speedglm’


could you please help me what is this error and how could i solve it? thanx

**Comment by hpliner** [comment]
@parsboy66 Try installing speedglm and Matrix separately, with `BiocManager::install(c('speedglm', 'Matrix'))`

**Comment by hpliner** [comment]
If these errors persist, please reopen

**Comment by liliay** [comment]
Hi there, 

I have the exact same problem @juan-quintana2020 did you resolve it ? If you did, how did you manage to ? 
Thanks in advance for your help !

Best, 
Lilia
