### ISSUE TITLE
Please help me.. i can't load my single cell seq. data to monocle3.

### ISSUE THREAD

**Issue by kimdukki** [cole-trapnell-lab/monocle3#339]
When i was tried to Monocle3, I failed at first phase. 

I did 10x single cell seqeunicng. 
And I tried to do monocle3 for pseudotime-analysis. 
When i was loaded my cell ranger files to monocle 3, i failed to load. 

At first,
 
> cds <- load_cellranger_data("F:/filtered_feature_bc_matrix")
Error in load_cellranger_data("F:/filtered_feature_bc_matrix") : 
  Could not find the pipestance output directory: 'F:/filtered_feature_bc_matrix/outs'. Please double-check if the directory exists.

so i made folder, the name is "outs"

> cds <- load_cellranger_data("F:/filtered_feature_bc_matrix")
Error in load_cellranger_data("F:/filtered_feature_bc_matrix") : 
  Could not find directory: F:/filtered_feature_bc_matrix/outs/filtered_gene_bc_matrices

so i made folder, the name is "filtered_gene_bc_matrices

> cds <- load_cellranger_data("F:/filtered_feature_bc_matrix")
Error in get_genome_in_matrix_path(matrix_dir, genome) : 
  Multiple genomes found; please specify one. 
 Genomes present: barcodes.tsv.gz, features.tsv.gz, matrix.mtx.gz

And this time I can't improve more. 

Please help me, what can i do next for loading cell ranger data to monocle3

**Comment by hpliner** [comment]
If you don't have access to the original Cell Ranger output (with their file structure), I recommend using load_mm_data from the develop version of monocle3 (install using `devtools::install_github('cole-trapnell-lab/monocle3', ref='develop')` ). You can see the usage by running `?load_mm_data`. You will need to unzip your barcodes and features files first though

**Comment by jjyotikataria** [comment]
@hpliner @kimdukki @Loyale @ctrapnell @kou 

Shall I completely rely on the develop branch for my analysis? Is it ready to be deployed?
