### ISSUE TITLE
User input pseudotime

### ISSUE THREAD

**Issue by Winnie09** [cole-trapnell-lab/monocle3#340]
Hi,

Thank you for developing monocle3! I am applying it to do differential expression analysis, for example to find genes that change as a function of pseudotime and regression analysis.
May I know whether I can input my own pseudotime ordering of cells to monocle3? I noticed that the pipeline in the tutorial uses the trajectory output of monocle3 directly, so I am wondering whether it is possible to pass in the trajectory output of other pseudotime tools? Thanks a lot!

**Comment by brgew** [comment]
Hi,

Monocle3 does not support officially the use of pseudotime information from an external source. However, you can add a column of values that represent cell order to pData(cds) of the CDS, and use that in the regression analysis. For example, if you have a vector of integers that represent the cell order called `my_cell_order`, use the command

  
`pData(cds)$my_cell_order <- my_cell_order
`
