### ISSUE TITLE
combine_cds gives error

### ISSUE THREAD

**Issue by f0t1h** [cole-trapnell-lab/monocle3#342]
I get following error when I use combine_cds function as

```
cds <- combine_cds(c(cds1,cds3))
```

```
Error: Matrices must have same number of columns in rbind2(argl[[i]], r)
```

I am on a Windows machine with latest R and RStudio. I got the same error on both release and develop version. I get the same error on many different datasets including when I subset and combine the same dataset.

Thank you.

**Comment by hpliner** [comment]
Can you try running `cds <- combine_cds(list(cds1, cds3))` ? combine_cds needs to be passed a list

**Comment by f0t1h** [comment]
Thank you.
