### ISSUE TITLE
Customising plot_cells

### ISSUE THREAD

**Issue by jdarmitage** [cole-trapnell-lab/monocle3#345]
Hi,

Thank you for this extremely useful package. I'm trying to visualize gene expression in my dataset using the plot_cells function however I'm finding the visualization of this expression to be sub-optimal:

![plot_cells example](https://imgur.com/PW4vXp9.png)

I find that a lot of these points overlap on each other to the point where specific expression patterns are quite difficult to see. While changing the alpha to <1 does help with the overlap, I'd like to completely hide the cells that don't express any levels of the gene. Is this possible?

Alternatively, is there a way to layer the points such that the highest-expressing cells are positioned on top of others? I know Seurat v3 has some functionality to do this with these expression plots.

Thanks for your help.

**Comment by brgew** [comment]
Hi,
I modified plot_cells() to plot the cells in order from lowest to highest expression level, which I hope addresses your concern. The modifed version is in the Monocle3 develop branch on github. You can install this using the R command

`devtools::install_github('cole-trapnell-lab/monocle3',ref='develop')`

Please let me know if this does not adequately address the problem.

I am grateful for your feedback.

**Comment by jdarmitage** [comment]
Hi,

The develop mode now overlays the points correctly so the highest expressing cells are above the others. Thanks for the fix!
