### ISSUE TITLE
Subset clusters for pseudotime analysis

### ISSUE THREAD

**Issue by pbpayal** [cole-trapnell-lab/monocle3#350]
Hi,

Is it possible to subset clusters and then draw pseudotime trajectory? 
I tried subsetting my dataset to focus on just the clusters I want to represent, but I get the follwing error.
`cds_subset <- choose_cells(cds_cluster)`
`cds_subcluster_graph <- learn_graph(cds_subset, use_partition = FALSE, close_loop = TRUE)`
  `|==============================================================================================| 100%`

`Error in Z[, subset_cds_col_names] : subscript out of bounds`

What does this mean?

**Comment by brgew** [comment]
Hi,
I think that the function 

cds_subset<-choose_graph_segments(cds)

may work for this purpose. Please let me know if it does not.

**Comment by hpliner** [comment]
Hi @pbpayal, After you subset cells, you should rerun dimensionality reduction to generate a new trajectory. In the next version, choose_cells will clear the graph data because it is no longer valid after the data is subset.
