### ISSUE TITLE
How to address multiple paths

### ISSUE THREAD

**Issue by fbrundu** [cole-trapnell-lab/monocle3#364]
Hi,
I have a set of cells annotated with cell type labels.
From the literature, I know already which is the path they should follow.

In particular, in the plot below, there should be two different paths of differentiation, starting from node 1:
- The first is the one already identified, from node 1 to the centre of the projection and then to the red cluster, or to the orange, or to the dark blue one.
- The second should go from node 1 to the violet cluster, then to the brown cluster, finally to the orange cluster

I am thinking that there may be differences in sampling of each region of the cell space, that create gaps that monocle3 is not able to bridge. Is this a correct interpretation?
Is there a way to instruct monocle3 to increase the number of paths?

Thanks

<img width="749" alt="image" src="https://user-images.githubusercontent.com/697622/83657333-b642ed80-a58e-11ea-9116-362d4ac7de54.png">

**Comment by brgew** [comment]
Hi,
Unfortunately I don't have an answer to this question. It appears certainly that the cell density in the UMAP space along the second expected path is low, which may prevent Monocle3 from closing the path. Your guess that those cells are under-represented seems reasonable. Is there a biological reason to expect fewer such cells? I suppose the the dimensional reduction may be a factor too. Have you tried subsetting the data? I regret that I cannot offer a useful answer.d

**Comment by fbrundu** [comment]
Hi @brgew, thanks for your reply.
I am not sure at the moment why such cells might be under-represented, however, it's already useful to me to know that it might be the underlying cause - thanks. I'll leave this issue open in case there's a way to troubleshoot this (for example, drawing a density map on top of the trajectory) but feel free to close it if it's not relevant.

**Comment by brgew** [comment]
Hi @fbrundu,
I wonder if you posted your question to https://groups.google.com/d/forum/monocle-3-users?
We prefer that questions go to the google group and bugs go here.
