### ISSUE TITLE
MONOCLE 3 minSpanningTree(cds)

### ISSUE THREAD

**Issue by ddw193** [cole-trapnell-lab/monocle3#365]
Wondering how to retrieve the minimum spanning tree in MONOCLE 3 as similar methods existed in earlier versions (MONOCLE and MONOCLE 2).

Looking to retrieve the minimum spanning tree to do some calculations relative to existing cells and explore different ways of visualizing it with other data generated by MONOCLE 3 (e.g., Moran's I clusters)

For example, minSpanningTree @ https://rdrr.io/bioc/monocle/man/minSpanningTree.html

**Comment by hpliner** [comment]
Hello,
Monocle3 no longer uses a minimum spanning tree, but instead a principal graph. You can access the principal graph using principal_graph(cds)[['UMAP']]
