### ISSUE TITLE
graph_test low or no expression

### ISSUE THREAD

**Issue by danhtruong** [cole-trapnell-lab/monocle3#366]
Hello,

I used the graph_test and it was successful at finding genes that were dependent on the trajectory. However, there were very low expressing genes (less than 50 cells etc) that made the cut still (q<0.05). Therefore, when I generated gene modules, there were of course modules of these genes (low or no expression in most cells). 

Are there parameters that I could play around with? Is there a way to remove gene modules that are found in a low number of cells?

**Comment by brgew** [comment]
Hi,

I see no parameters that filter genes in the way that you want. However, you can find the names of genes that have at least mncells each with at least mnexprs counts using the R commands

```
# minimum counts per cell by gene
mnexprs<-10
# minimum cells with minimum counts by gene
mncells<-20
mnexprs_cell_by_gene <- apply(counts(cds), 1, function(v){v >= mnexprs})
mncells_by_gene <- apply(t(mnexprs_cell_by_gene), 1, function(v) {sum(v) >= mncells})
genes_with_mncells <- names(mncells_by_gene[mncells_by_gene])
```
Does this do what you need?

**Comment by danhtruong** [comment]
Hi,

Thanks for the response. Not exactly but it was something I looked into as well. After some time going through the data, I think I am closer to understanding what happened. My data contains a few lineages with unique gene modules for the lineages. 

So when I subset the lineages, modules that do not exist in those lineages will show up as very lowly expressed. Even if I subset the lineages prior to running the principle test, it will pick up some genes as noise too. These noisy genes will also be grouped into a single gene module, which I guess you can manually remove with some justification. 

In any case, I appreciate the work but I am using a different method to cluster my genes at the moment.

Also another thing, I was trying to create individual UMAPs of modules but I noticed that if I input my gene module dataframe with a single module, then the function won't run. If I put my whole module dataframe in, of course it works out, but the plots are facet wrap and I didn't know how to separate them. I decided to make a new aggregated CDS with the modules as genes and looped through to make individual UMAPs. Perhaps there was an easier way to do that I overlooked.

**Comment by brgew** [comment]
Hi @danhtruong,
I don't understand what you want to do. I would be grateful for a code example.
Thank you.
