### ISSUE TITLE
get_earliest_principal_node multiple roots

### ISSUE THREAD

**Issue by LuciaJim** [cole-trapnell-lab/monocle3#374]
Hello! I would like to know if the `get_earliest_principal_node` function can automatically identify multiple roots within one partition.
https://cole-trapnell-lab.github.io/monocle3/docs/trajectories/
Thanks!

**Comment by brgew** [comment]
Hi,
The `get_earliest_principal_node()` function returns one root, given that `which.max()` returns one index.

**Comment by rachadele** [comment]
to return a vector of multiple roots and pass to `order_cells`:

```
get_earliest_principal_node <- function(cds, cell_phenotype="broad_cell_type", root_types){
  root_pr_nodes <- lapply(root_types, function(root_type) {
        cell_ids <- which(pData(cds)[, cell_phenotype] == root_type)
        closest_vertex <-
        cds@principal_graph_aux[["UMAP"]]$pr_graph_cell_proj_closest_vertex
        closest_vertex <- as.matrix(closest_vertex[colnames(cds), ])
        root_pr_nodes <-
        igraph::V(principal_graph(cds)[["UMAP"]])$name[as.numeric(names
        (which.max(table(closest_vertex[cell_ids,]))))]
        return(root_pr_nodes)
        })
   return(unlist(root_pr_nodes))
}

cds <- order_cells(cds, root_pr_nodes=get_earliest_principal_node(cds, cell_phenotype="seurat_clusters", root_types=c("1","4")))
```

the order of root types passed to `get_earliest_principal_node` will be maintained in your graph; e.g. clusters 1 and 4 will be roots 1 and 2, respectively.

**Comment by yulchen810** [comment]
Hi,
I used `  # a helper function to identify the root principal points:
  get_earliest_principal_node <- function(cds, time_bin="130-170"){
    cell_ids <- which(colData(cds)[, "embryo.time.bin"] == time_bin)
    
    closest_vertex <-
      cds@principal_graph_aux[["UMAP"]]$pr_graph_cell_proj_closest_vertex
    closest_vertex <- as.matrix(closest_vertex[colnames(cds), ])
    root_pr_nodes <-
      igraph::V(principal_graph(cds)[["UMAP"]])$name[as.numeric(names
                                                                (which.max(table(closest_vertex[cell_ids,]))))]
    
    root_pr_nodes
  }
  cds <- order_cells(cds, root_pr_nodes=get_earliest_principal_node(cds))
` to automatically order the trajectory, but it returns an error.
Error in h(simpleError(msg, call)) :
在为函数“which”选择方法时计算参数“x”时出错：subscript contains invalid names

May you please have a look? Thank you !
