### ISSUE TITLE
Different plots for same data set and code every time 

### ISSUE THREAD

**Issue by alymatz** [cole-trapnell-lab/monocle3#377]
Hello, 
At first my monocle was giving reproducible results, however, upon starting new R sessions, it became apparent the trajectories were changing every time. The changes are a significant, going from 2 to 6 branches along a trajectory. I noticed that for at least two of the trajectories (one with 5 and the other with 2 branches) the gene expression profiles are reversed, both otherwise similar. Is this a known occurrence and should I simply proceed without worry, or is this a problem? I am not well versed in R, but I can assure the code is not changing between sessions. 
Thank you for your consideration!

**Comment by brgew** [comment]
Hi,

If you re-run `cluster_cells()` without setting the `random_seed` parameter to the same value each time, the results of downstream processing will change to some degree. Additionally, some of the `reduce_dimension()` parameters such as `cores` and `umap.fast_sgd` can affect the reproducibility although the` reduce_dimension()` default values should give reproducible results.
Please try running `cluster_cells(cds,random_seed=12345)`, or something similar, and let me know if you notice still variations in the results.

**Comment by alymatz** [comment]
Hi brgew, 
Thank you so much for responding. I was able to fix the problem by setting the seed in the very beginning of the code before even opening monocle. I now am able to generate the same trajectory every time. 
Thank you again for your time! 
Sincerely,
Alymatz

**Comment by brgew** [comment]
I am closing this issue.

**Comment by drroya** [comment]
Hello,

I am facing the same problem with monocle. Although I stetted the seed in the beginning of code but every single time that I run the codes, I get a new trajectory plot with different number and position of states!!!

Can anyone help?
