### ISSUE TITLE
org.Hm.eg.db not available

### ISSUE THREAD

**Issue by wfma** [cole-trapnell-lab/monocle3#380]
** If this is a question and not a bug report or enhancement request, please post to our google group at https://groups.google.com/forum/#!forum/monocle-3-users**

**Describe the bug**
In the monocle3 [tutorial](https://cole-trapnell-lab.github.io/monocle3/docs/clustering/#find-markers) under garnett, it said to install org.Hm.eg.db from bioconductor using the code:

`BiocManager::install(c("org.Mm.eg.db", "org.Hm.eg.db"))
`
I cant find anything call 'org.Hm.eg.db'. Was this supposed to be 'org.Hs.eg.db' instead?

**Comment by hpliner** [comment]
Hello, yes, that's a typo, it should be org.Hs.eg.db. We will update!

**Comment by wfma** [comment]
awesome!
