### ISSUE TITLE
import a Seurat3 object to Monocle3

### ISSUE THREAD

**Issue by stefanonard85** [cole-trapnell-lab/monocle3#381]
** If this is a question and not a bug report or enhancement request, please post to our google group at https://groups.google.com/forum/#!forum/monocle-3-users**

**Describe the bug**

**To Reproduce**
The code that produced the bug:

**traceback()**
After the error, run traceback() in R and post the output:

**Expected behavior**

**Screenshots**

**sessionInfo():**
Run sessionInfo() in R and post the output

**Additional context**

**Comment by stefanonard85** [comment]
Hello , 

is there a function or a  way to transform a Seurat 3 object into Monocle3 object? This is not a bug but a problem that the community has having because because Monocle2 is deprecated and the function to import a Seurat object does not recognize a Seurat 3 object. Any solution will be highly appreciated

**Comment by ashuchawla** [comment]
Following

**Comment by tanasa** [comment]
if you'd like to take a look into : http://htmlpreview.github.io/?https://github.com/satijalab/seurat-wrappers/blob/master/docs/monocle3.html

**Comment by hpliner** [comment]
seurat-wrappers as referenced above should solve this issue
