### ISSUE TITLE
Are cycles allowed in the principal graph?

### ISSUE THREAD

**Issue by vishakagopalan** [cole-trapnell-lab/monocle3#388]
I was processing some publicly available scRNA-seq data through Monocle3. The data consisted of two cell types.

I tried plotting the principal_graph that consisted of only principal nodes, and saw that the graph contained cycles. I'm aware that the goal of monocle3 is to fit an acyclic graph where the cells are leaf nodes. But either way, is it okay for me to get a principal graph (with cells removed) that contains cycles? Or did I make an error in running the code

Here is the output ---

```
    cds_obj <- new_cell_data_set( expr_mat, cell_metadata=meta_data_df, 
                              gene_metadata = gene_meta_data)
    cds_obj <- preprocess_cds(cds_obj, num_dim = 10, use_genes=var_features, 
                             scaling=F, norm_method="none", method="PCA" )
    cds_obj <- reduce_dimension(cds_obj)
    cds_obj = cluster_cells(cds_obj, resolution=1e-4 )
    cds_obj <- learn_graph( cds_obj, use_partition=F )
    closest_vertex_mat <- cds_obj@principal_graph_aux[["UMAP"]]$pr_graph_cell_proj_closest_vertex %>% as.matrix
    root_node <- paste("Y",closest_vertex_mat[medoid_cell,],sep="_")
    cds_obj <- order_cells( cds_obj, root_pr_nodes=root_node)
    pr_node_graph <- principal_graph(cds_obj)[["UMAP"]]

plot.igraph(pr_node_graph,vertex.size=4,label.cex=3)
```
![image](https://user-images.githubusercontent.com/54443552/86629287-321ec400-bf99-11ea-88f5-5577e700921a.png)

**Comment by brgew** [comment]
Hi,
Yes, cycles are permitted.
