### ISSUE TITLE
Trajectory tutorial UMAP and my UMAP are different.

### ISSUE THREAD

**Issue by Mike-Kostock** [cole-trapnell-lab/monocle3#389]
I know that UMAP appears differently when packages compatible with monocle3 are different.

![image](https://user-images.githubusercontent.com/37606933/87493794-88ba8b00-c688-11ea-9885-3e8a0df55de8.png)

[sessionInfo.txt](https://github.com/cole-trapnell-lab/monocle3/files/4922414/sessionInfo.txt)

I would like to amend the package if you let me know what dependent package causes this problem.

Thanks you

Mike Kostok

**Comment by brgew** [comment]
Hi,
Could you explain your processing steps and what you see and what you expect?
Thank you.

**Comment by brgew** [comment]
I close this because there was no response.
