### ISSUE TITLE
Memory usage of trajectory analysis

### ISSUE THREAD

**Issue by zeus19900814** [cole-trapnell-lab/monocle3#391]
Hi,

I'm following the tutorial of trajectory analysis https://cole-trapnell-lab.github.io/monocle3/docs/trajectories/ and it works really great!

One thing I'm wondering is the memory usage of this workflow. Is there a relation between memory usage and some metrics, like number of cells, number of features, reduced dimension, etc?

Thank you!
John

**Comment by brgew** [comment]
Hi,
Yes. The memory usage depends on the size of the count matrix, the number of non-zero elements in the count matrix, the number of dimensions retained, and, I suspect, other aspects of the data.
