### ISSUE TITLE
Issues with leidenbase installation on macOS, r4.02

### ISSUE THREAD

**Issue by mimisikai** [cole-trapnell-lab/monocle3#393]
I have been trying to install monocle3 by installing all dependencies from scratch after reinstalling r4.02 then failed to install leidenbase. Error as below. Tried everything that I can do but not figure out this problem. 

In file included from cigraph/src/CHOLMOD/Supernodal/cholmod_super_numeric.c:63:
In file included from cigraph/src/igraph_blas_internal.h:33:
cigraph/src/config.h:131:9: warning: 'PACKAGE_VERSION' macro redefined [-Wmacro-redefined]
#define PACKAGE_VERSION "1.1.0"
        ^
<command line>:7:9: note: previous definition is here
#define PACKAGE_VERSION "0.8.2"
        ^
In file included from cigraph/src/CHOLMOD/Supernodal/cholmod_super_numeric.c:80:
cigraph/src/CHOLMOD/Supernodal/t_cholmod_super_numeric.c:510:17: error: implicit declaration of function 'dsyrk_' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                BLAS_dsyrk ("L", "N",
                ^
cigraph/src/CHOLMOD/Include/cholmod_blas.h:331:2: note: expanded from macro 'BLAS_dsyrk'
        BLAS_DSYRK (uplo, trans, &N, &K, alpha, A, &LDA, beta, C, &LDC) ; \
        ^
cigraph/src/CHOLMOD/Include/cholmod_blas.h:132:20: note: expanded from macro 'BLAS_DSYRK'
#define BLAS_DSYRK igraphdsyrk_
                   ^
cigraph/src/igraph_lapack_internal.h:86:29: note: expanded from macro 'igraphdsyrk_'
    #define igraphdsyrk_    dsyrk_
                            ^
In file included from cigraph/src/CHOLMOD/Supernodal/cholmod_super_numeric.c:80:
cigraph/src/CHOLMOD/Supernodal/t_cholmod_super_numeric.c:713:13: error: implicit declaration of function 'dpotrf_' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            LAPACK_dpotrf ("L",
            ^
cigraph/src/CHOLMOD/Include/cholmod_blas.h:365:2: note: expanded from macro 'LAPACK_dpotrf'
        LAPACK_DPOTRF (uplo, &N, A, &LDA, &INFO) ; \
        ^
cigraph/src/CHOLMOD/Include/cholmod_blas.h:135:23: note: expanded from macro 'LAPACK_DPOTRF'
#define LAPACK_DPOTRF igraphdpotrf_
                      ^
cigraph/src/igraph_lapack_internal.h:120:29: note: expanded from macro 'igraphdpotrf_'
    #define igraphdpotrf_   dpotrf_
                            ^
cigraph/src/CHOLMOD/Supernodal/t_cholmod_super_numeric.c:713:13: note: did you mean 'zpotrf_'?
cigraph/src/CHOLMOD/Include/cholmod_blas.h:365:2: note: expanded from macro 'LAPACK_dpotrf'
        LAPACK_DPOTRF (uplo, &N, A, &LDA, &INFO) ; \
        ^
cigraph/src/CHOLMOD/Include/cholmod_blas.h:135:23: note: expanded from macro 'LAPACK_DPOTRF'
#define LAPACK_DPOTRF igraphdpotrf_
                      ^
cigraph/src/igraph_lapack_internal.h:120:29: note: expanded from macro 'igraphdpotrf_'
    #define igraphdpotrf_   dpotrf_
                            ^
cigraph/src/CHOLMOD/Include/cholmod_blas.h:370:6: note: 'zpotrf_' declared here
void LAPACK_ZPOTRF (char *uplo, BLAS_INT *n, double *A, BLAS_INT *lda,
     ^
cigraph/src/CHOLMOD/Include/cholmod_blas.h:144:23: note: expanded from macro 'LAPACK_ZPOTRF'
#define LAPACK_ZPOTRF zpotrf_
                      ^
In file included from cigraph/src/CHOLMOD/Supernodal/cholmod_super_numeric.c:80:
cigraph/src/CHOLMOD/Supernodal/t_cholmod_super_numeric.c:842:17: error: implicit declaration of function 'dtrsm_' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                BLAS_dtrsm ("R", "L", "C", "N",
                ^
cigraph/src/CHOLMOD/Include/cholmod_blas.h:257:2: note: expanded from macro 'BLAS_dtrsm'
        BLAS_DTRSM (side, uplo, transa, diag, &M, &N, alpha, A, &LDA, B, &LDB);\
        ^
cigraph/src/CHOLMOD/Include/cholmod_blas.h:130:20: note: expanded from macro 'BLAS_DTRSM'
#define BLAS_DTRSM igraphdtrsm_
                   ^
cigraph/src/igraph_blas_internal.h:50:29: note: expanded from macro 'igraphdtrsm_'
    #define igraphdtrsm_    dtrsm_
                            ^
cigraph/src/CHOLMOD/Supernodal/t_cholmod_super_numeric.c:842:17: note: did you mean 'ztrsm_'?
cigraph/src/CHOLMOD/Include/cholmod_blas.h:257:2: note: expanded from macro 'BLAS_dtrsm'
        BLAS_DTRSM (side, uplo, transa, diag, &M, &N, alpha, A, &LDA, B, &LDB);\
        ^
cigraph/src/CHOLMOD/Include/cholmod_blas.h:130:20: note: expanded from macro 'BLAS_DTRSM'
#define BLAS_DTRSM igraphdtrsm_
                   ^
cigraph/src/igraph_blas_internal.h:50:29: note: expanded from macro 'igraphdtrsm_'
    #define igraphdtrsm_    dtrsm_
                            ^
cigraph/src/CHOLMOD/Include/cholmod_blas.h:261:6: note: 'ztrsm_' declared here
void BLAS_ZTRSM (char *side, char *uplo, char *transa, char *diag, BLAS_INT *m,
     ^
cigraph/src/CHOLMOD/Include/cholmod_blas.h:139:20: note: expanded from macro 'BLAS_ZTRSM'
#define BLAS_ZTRSM ztrsm_
                   ^
In file included from cigraph/src/CHOLMOD/Supernodal/cholmod_super_numeric.c:80:
cigraph/src/CHOLMOD/Supernodal/t_cholmod_super_numeric.c:141:40: warning: unused variable 'tstart' [-Wunused-variable]
    double one [2], zero [2], fjk [2], tstart ;
                                       ^
2 warnings and 3 errors generated.
make: *** [cigraph/src/CHOLMOD/Supernodal/cholmod_super_numeric.o] Error 1
ERROR: compilation failed for package ‘leidenbase’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/leidenbase’
Error: Failed to install 'monocle3' from GitHub:
  Failed to install 'leidenbase' from GitHub:
  (converted from warning) installation of package ‘/var/folders/wm/xqv0tx8j4xg1361s21lyzx2h0000gn/T//RtmphIwigy/file3807dd35285/leidenbase_0.1.1.tar.gz’ had non-zero exit status

**Comment by mimisikai** [comment]
Need help

**Comment by val23n** [comment]
I am also having this problem resulting in the exact same error message (see below). The computer I'm using is a macOS Catalina, Version 10.15.6. I'm new to GitHub so please let me know if you need more information! Thanks!

2 warnings and 3 errors generated.
make: *** [cigraph/src/CHOLMOD/Supernodal/cholmod_super_numeric.o] Error 1
ERROR: compilation failed for package ‘leidenbase’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/leidenbase’
Error: Failed to install 'leidenbase' from GitHub:
  (converted from warning) installation of package ‘/var/folders/v3/tdmhdpxd65n0j81wk859jdsw0000gq/T//Rtmph6G87V/file13db743faeb27/leidenbase_0.1.1.tar.gz’ had non-zero exit status

**Comment by jeffsun905** [comment]
I got the same error for MacBook Pro with Catalina and R.4.0.2. Any help is appreciated!

In file included from cigraph/src/CHOLMOD/Supernodal/cholmod_super_numeric.c:63:
In file included from cigraph/src/igraph_blas_internal.h:33:
cigraph/src/config.h:131:9: warning: 'PACKAGE_VERSION' macro redefined [-Wmacro-redefined]
#define PACKAGE_VERSION "1.1.0"
        ^
<command line>:7:9: note: previous definition is here
#define PACKAGE_VERSION "0.8.2"
        ^
In file included from cigraph/src/CHOLMOD/Supernodal/cholmod_super_numeric.c:80:
cigraph/src/CHOLMOD/Supernodal/t_cholmod_super_numeric.c:510:17: error: implicit declaration of function 'dsyrk_' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                BLAS_dsyrk ("L", "N",
                ^
cigraph/src/CHOLMOD/Include/cholmod_blas.h:331:2: note: expanded from macro 'BLAS_dsyrk'
        BLAS_DSYRK (uplo, trans, &N, &K, alpha, A, &LDA, beta, C, &LDC) ; \
        ^
cigraph/src/CHOLMOD/Include/cholmod_blas.h:132:20: note: expanded from macro 'BLAS_DSYRK'
#define BLAS_DSYRK igraphdsyrk_
                   ^
cigraph/src/igraph_lapack_internal.h:86:29: note: expanded from macro 'igraphdsyrk_'
    #define igraphdsyrk_    dsyrk_
                            ^
In file included from cigraph/src/CHOLMOD/Supernodal/cholmod_super_numeric.c:80:
cigraph/src/CHOLMOD/Supernodal/t_cholmod_super_numeric.c:713:13: error: implicit declaration of function 'dpotrf_' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            LAPACK_dpotrf ("L",
            ^
cigraph/src/CHOLMOD/Include/cholmod_blas.h:365:2: note: expanded from macro 'LAPACK_dpotrf'
        LAPACK_DPOTRF (uplo, &N, A, &LDA, &INFO) ; \
        ^
cigraph/src/CHOLMOD/Include/cholmod_blas.h:135:23: note: expanded from macro 'LAPACK_DPOTRF'
#define LAPACK_DPOTRF igraphdpotrf_
                      ^
cigraph/src/igraph_lapack_internal.h:120:29: note: expanded from macro 'igraphdpotrf_'
    #define igraphdpotrf_   dpotrf_
                            ^
cigraph/src/CHOLMOD/Supernodal/t_cholmod_super_numeric.c:713:13: note: did you mean 'zpotrf_'?
cigraph/src/CHOLMOD/Include/cholmod_blas.h:365:2: note: expanded from macro 'LAPACK_dpotrf'
        LAPACK_DPOTRF (uplo, &N, A, &LDA, &INFO) ; \
        ^
cigraph/src/CHOLMOD/Include/cholmod_blas.h:135:23: note: expanded from macro 'LAPACK_DPOTRF'
#define LAPACK_DPOTRF igraphdpotrf_
                      ^
cigraph/src/igraph_lapack_internal.h:120:29: note: expanded from macro 'igraphdpotrf_'
    #define igraphdpotrf_   dpotrf_
                            ^
cigraph/src/CHOLMOD/Include/cholmod_blas.h:370:6: note: 'zpotrf_' declared here
void LAPACK_ZPOTRF (char *uplo, BLAS_INT *n, double *A, BLAS_INT *lda,
     ^
cigraph/src/CHOLMOD/Include/cholmod_blas.h:144:23: note: expanded from macro 'LAPACK_ZPOTRF'
#define LAPACK_ZPOTRF zpotrf_
                      ^
In file included from cigraph/src/CHOLMOD/Supernodal/cholmod_super_numeric.c:80:
cigraph/src/CHOLMOD/Supernodal/t_cholmod_super_numeric.c:842:17: error: implicit declaration of function 'dtrsm_' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                BLAS_dtrsm ("R", "L", "C", "N",
                ^
cigraph/src/CHOLMOD/Include/cholmod_blas.h:257:2: note: expanded from macro 'BLAS_dtrsm'
        BLAS_DTRSM (side, uplo, transa, diag, &M, &N, alpha, A, &LDA, B, &LDB);\
        ^
cigraph/src/CHOLMOD/Include/cholmod_blas.h:130:20: note: expanded from macro 'BLAS_DTRSM'
#define BLAS_DTRSM igraphdtrsm_
                   ^
cigraph/src/igraph_blas_internal.h:50:29: note: expanded from macro 'igraphdtrsm_'
    #define igraphdtrsm_    dtrsm_
                            ^
cigraph/src/CHOLMOD/Supernodal/t_cholmod_super_numeric.c:842:17: note: did you mean 'ztrsm_'?
cigraph/src/CHOLMOD/Include/cholmod_blas.h:257:2: note: expanded from macro 'BLAS_dtrsm'
        BLAS_DTRSM (side, uplo, transa, diag, &M, &N, alpha, A, &LDA, B, &LDB);\
        ^
cigraph/src/CHOLMOD/Include/cholmod_blas.h:130:20: note: expanded from macro 'BLAS_DTRSM'
#define BLAS_DTRSM igraphdtrsm_
                   ^
cigraph/src/igraph_blas_internal.h:50:29: note: expanded from macro 'igraphdtrsm_'
    #define igraphdtrsm_    dtrsm_
                            ^
cigraph/src/CHOLMOD/Include/cholmod_blas.h:261:6: note: 'ztrsm_' declared here
void BLAS_ZTRSM (char *side, char *uplo, char *transa, char *diag, BLAS_INT *m,
     ^
cigraph/src/CHOLMOD/Include/cholmod_blas.h:139:20: note: expanded from macro 'BLAS_ZTRSM'
#define BLAS_ZTRSM ztrsm_
                   ^
In file included from cigraph/src/CHOLMOD/Supernodal/cholmod_super_numeric.c:80:
cigraph/src/CHOLMOD/Supernodal/t_cholmod_super_numeric.c:141:40: warning: unused variable 'tstart' [-Wunused-variable]
    double one [2], zero [2], fjk [2], tstart ;
                                       ^
2 warnings and 3 errors generated.
make: *** [cigraph/src/CHOLMOD/Supernodal/cholmod_super_numeric.o] Error 1
ERROR: compilation failed for package ‘leidenbase’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/leidenbase’
Error: Failed to install 'leidenbase' from GitHub:
  (converted from warning) installation of package ‘/var/folders/ym/pqx8y0t15tb9jwbk0m32_g6dtktzn3/T//RtmppeJiSH/filea5944b9c1e9/leidenbase_0.1.1.tar.gz’ had non-zero exit status

**Comment by ninal88** [comment]
Has anyone solved this? I have the same exact issue on R 4.0.2 and macOS Catalina 10.15.5

**Comment by brgew** [comment]
Hi,
Does this problem persist?

**Comment by brgew** [comment]
No response.
