### ISSUE TITLE
 Error in value[[3L]](cond) : Error in model formula for plot_genes_in_pseudotime()

### ISSUE THREAD

**Issue by alexdanechi** [cole-trapnell-lab/monocle3#394]
Hi, 

I am trying to plot_genes_in_pseudotime() but keep getting this Error in value[[3L]](cond) : Error in model formula.

This is the code I am using: 

CTB_genes <- c("ISL1", "MMP2", "TEAD3", "TEAD4")
CTB_lineage_cds <- cds[rowData(cds)$gene_short_name %in% CTB_genes,
                       colData(cds)$cell.type %in% c("CTB")]

plot_genes_in_pseudotime(CTB_lineage_cds,
                         color_cells_by="assigned_cell_type",
                         min_expr=0.5)

Read out for CTB_lineage_cds is:

class: cell_data_set 
dim: 4 0 
metadata(2): cds_version citations
assays(1): counts
rownames(4): ENSG00000016082 ENSG00000007866 ENSG00000197905 ENSG00000087245
rowData names(2): id gene_short_name
colnames: NULL
colData names(3): barcode Size_Factor assigned_cell_type
reducedDimNames(2): PCA UMAP
spikeNames(0):
altExpNames(0):

Then I get Error in value[[3L]](cond) : Error in model formula when running plot_genes_in_pseudotime()

**Comment by alexdanechi** [comment]
Pls help

**Comment by brgew** [comment]
Hi,
I believe that the error is in the fit_models() function. The most recent Monocle3 on github has additional tests and diagnostic messages in the fit_models(), which may help to understand the cause of the error. (It may be that some of the pseudotime values are undefined).

**Comment by EAC-T** [comment]
I'm getting the same error. 
I did this for the fit model: CD3_fits <- fit_models(Tcellsmono_4, model_formula_str = "~cluster")
Then 
genes <- c("Gata3", "S100a4", "Foxp3","S100a6")
lineage_cds <- Tcellsmono_4[rowData(Tcellsmono_4)$gene_short_name %in% genes,colData(Tcellsmono_4)$cluster %in% c("3")]
plot_genes_in_pseudotime(lineage_cds, color_cells_by="cluster", min_expr=0.5)

It's not working, not sure what I'm doing wrong1
@alexdanechi  this find a work around that?

Thank you

**Comment by brgew** [comment]
Hi,
Do you have an example data set that I can use for testing? And please include the your processing steps.

**Comment by EAC-T** [comment]
Hi @brgew , I do have, do you mean you want me to send you my data in an R object?

**Comment by brgew** [comment]
Hi @EAC-T,
An R object is convenient for me. It appears that you can attach a file to an issue report
https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests
Thank you!

**Comment by brgew** [comment]
No response.
