### ISSUE TITLE
Trajectory analysis with a higher dimensional UMAP

### ISSUE THREAD

**Issue by Connorr0** [cole-trapnell-lab/monocle3#395]
I have noticed that increasing the dimensionality for UMAP can lead to some interesting results. Obviously UMAP is constrained by the fact that the embedding space is two dimensional and our data is extremely complex. I noticed that learn_graph seems to only work with clustering performed in UMAP. I figure this is probably to address the complaint that clusters that were distant across UMAP are connected over the trajectory. I would be fine with this being the case so long as the cells are close in the PC space.

Is there some way I can trick learn graph into using PCs instead of UMAP coordinates? I was also considering running learn_graph on a higher dimensional UMAP and then projecting that learned trajectory into the 3-dimensional UMAP.

Thanks!

**Comment by brgew** [comment]
Hi,
My recollection/understanding is that distances in UMAP space tend to correlate better with distances in the original space in comparison to other algorithms.
You can modify the code for your own purposes.

**Comment by brgew** [comment]
May I close this issue?

**Comment by Connorr0** [comment]
Yes, sorry I forgot to respond
