### ISSUE TITLE
Save nearest neighbor graph within Monocle3 cds object

### ISSUE THREAD

**Issue by joselmc** [cole-trapnell-lab/monocle3#398]
** If this is a question and not a bug report or enhancement request, please post to our google group at https://groups.google.com/forum/#!forum/monocle-3-users**

**Describe the bug**

**To Reproduce**
The code that produced the bug:

**traceback()**
After the error, run traceback() in R and post the output:

**Expected behavior**

**Screenshots**

**sessionInfo():**
Run sessionInfo() in R and post the output

**Additional context**

**Comment by brgew** [comment]
Hi Jose,

In what function are the nearest neighbors calculated?

**Comment by brgew** [comment]
No response.
