### ISSUE TITLE
Unable to install monocle3

### ISSUE THREAD

**Issue by liron27** [cole-trapnell-lab/monocle3#403]
Hi, 
I tried to install monocole3 and get the following message:

"package 'monocle3' is not available (for R version 4.0.2) "

traceback()
2: stop(packageNotFoundError(package, lib.loc, sys.call()))
1: library(monocle3)

Any help would be appreciated. Thanks!

**Comment by hpliner** [comment]
Please follow the installation instructions provided on the website. https://cole-trapnell-lab.github.io/monocle3/docs/installation/
