### ISSUE TITLE
differential expression/progression on the trajectory at specific time points

### ISSUE THREAD

**Issue by tanasa** [cole-trapnell-lab/monocle3#404]
Dear all, 

although it is not a bug report, if I may please post the question also here (i can not find the answer in the the documentation, and i am pressed by time) : 

i would like to understand better please how i could extract the genes that are differentially expressed at SPECIFIC TIME POINTS (on a trajectory) in SPECIFIC CLUSTERS/PARTITIONS ; for example considering the example in  : 

https://cole-trapnell-lab.github.io/monocle3/docs/differential/

i have done : 

```
###############################################

colData(cds)$clusters = clusters(cds)
colData(cds)$partitions = partitions(cds)
colData(cds)$pseudotime = pseudotime(cds)

###############################################

partition1_cds <- cds[,  colData(cds)$partitions == 1]

cds_subset = partition1_cds 

###############################################

subset_pr_test_res <- graph_test(cds_subset, neighbor_graph="principal_graph", cores=4)

pr_deg_ids <- row.names(subset(subset_pr_test_res, q_value < 0.05))

###############################################

```

the question being : how can i find the DE expressed genes along a trajectory associated with partition1,  at each time bin : 

```
unique(colData(cds_subset)$embryo.time.bin)
 [1] 330-390 170-210 210-270 > 650   270-330 390-450 450-510 510-580 130-170
[10] 580-650
```

many thanks, 

bogdan

**Comment by brgew** [comment]
Please post questions to https://groups.google.com/d/forum/monocle-3-users.
