### ISSUE TITLE
How to find differentially expressed genes (markers) of selected cells/groups?

### ISSUE THREAD

**Issue by rahulnutron** [cole-trapnell-lab/monocle3#407]
Thank you for such a great tool.

I was trying to compare group of selected cells to obtain differentially expressed genes (DEGs) between the groups.  However, I can't find an equivalent of WhichCells of Seurat in Monocle 3. I need to select cells based on expression of some marker genes.

Also is there any way to compare selected groups of cells (e.g., obtained from WhichCells like function) with the top_markers to obtain the DEGs between them?

Thanks in advance for any help,

Rahul

**Comment by AmelieRaz** [comment]
Hello-

I would also like to know if there is a tool, equivalent to WhichCells in Seurat, in which cell names can selected on the basis of a minimum expression value of a gene of interest. (I would use this as input for differentiation expression comparison with SCDE, but would also be interested if there's a better built-in way to do this with Monocle!)

Thank you,
Amelie

**Comment by brgew** [comment]
Hi,

In order to find the names of cells with a minimum read count for a gene, you can use R's subsetting, for example,

`colnames(counts(cds)["WBGene00000001",counts(cds)["WBGene00000001",]>500,drop=FALSE])`

Please post questions to https://groups.google.com/d/forum/monocle-3-users.
