### ISSUE TITLE
Occurred error for loading monocle trajectory pdf into Adobe illustrator CC 2019

### ISSUE THREAD

**Issue by honghh2018** [cole-trapnell-lab/monocle3#410]
Hi @ctrapnell ,
   I got a issue for the pdf loaded into Adobe illustrator CC2019 using monocle3 to draw trajectory picture saving with ggsave.
   The pdf file can not be load when using Adobe illustrator CC2019 to process it.
    Once i load the pdf file exported from monocle3 using ggsave function to save, the stop responed should be triggerred
    So how can i fix this issue?
    Best,
    hanhuihong

**Comment by brgew** [comment]
Hi,

This sounds like a problem with the ggplot2 package. You might try installing the most recent ggplot2 version and trying again.
