### ISSUE TITLE
subsetting and keeping all slots

### ISSUE THREAD

**Issue by BCYasser** [cole-trapnell-lab/monocle3#413]
Hi

Is there anyway I can subset without resetting the slots?

I don't want to re-preprocess and reduce dimension again because I want to keep the overlapping embeddings

I have tried

```
TcellsC=Tcells_M[,Tcells_M@colData$orig.ident=="Control"]
```
this first line resets the slots

```
TcellsC=subset(Tcells_M, subset=(Tcells_M@colData$orig.ident=="Control"))
```
this second line subsets the genes rather than the cells which is weird (my list of genes was truncated not my list of cells)

given that I have 6 samples of the same cells with 6 different condition I want them to be submitted to the preprocessing step together

**Comment by brgew** [comment]
Hi,

I don't understand what happens to the slots. You say that the information in `Tcells_M@colData` is removed? Or information about the cells with orig.ident=='Control' is missing in TcellsC?

**Comment by brgew** [comment]
No response.
