### ISSUE TITLE
are p-values provided for the predictions?

### ISSUE THREAD

**Issue by tanpuekai** [cole-trapnell-lab/monocle3#414]
as we know, bioinformatic predictions (such as lineage predictions) without a proper assessment of the errors (either in the form of p-values, FDR, FPR, or confidence intervals, etc.) are basically no different from that by fortune-tellers: if you test more you are bound get what you wanted; but there is no scientific basis for it at all.

may we know how this package assesses the error ranges of its predictions?

**Comment by brgew** [comment]
Hi,

Is there a specific function that lacks p-values?

**Comment by brgew** [comment]
No response.
