### ISSUE TITLE
What to do with chosen graph segment?

### ISSUE THREAD

**Issue by lamdan2** [cole-trapnell-lab/monocle3#415]
I chose a graph segment using "choose_graph_segment". Next, I would like to plot expression of selected genes along that segment. But I can't for example plot_genes_in_pseudotime - "No pseudotime calculated. Must call order_cells first." Shouldn't pseudotime information inherited from the parent object?

Is there any way of plotting gene expression along a selected trajectory? Or even just extracting the pseudotime and expression data from the object for custom plotting? Or anything else useful that can be done with these segments?

**Comment by brgew** [comment]
Hi,

You can run choose_graph_segments(...,clear_cds=FALSE). Does this solve the problem?

**Comment by lamdan2** [comment]
> Hi,
> 
> You can run choose_graph_segments(...,clear_cds=FALSE). Does this solve the problem?

yes, thank you!!
