### ISSUE TITLE
Questions: 

### ISSUE THREAD

**Issue by sylestiel** [cole-trapnell-lab/monocle3#420]
Hi Hannah,
Please advice on how to generate a list of root cells. I tried to look up promoter sums in C loupe Browser based on specific genes and then exported the barcodes of cells expressing them.

I got the error that reads as follows:
All provided root_cells must be present in the cell data set.

What should i do to address this problem?

Thanks!

**Comment by hpliner** [comment]
The root cells provided must match the row.names of the colData in your cds object.  Can you please check that the root cells provided are present? You can do this using `"cell_name" %in% row.names(colData(cds))` This should be TRUE
