### ISSUE TITLE
Can't install monocle3 on windows 10

### ISSUE THREAD

**Issue by AbdulkaderA** [cole-trapnell-lab/monocle3#421]
**Describe the bug**
I am trying to install monocle3 on R by following all steps but I have this error: 

Error: Failed to install 'monocle3' from GitHub:
  (converted from warning) installation of package ‘C:/Users/ak/AppData/Local/Temp/RtmpaMKuIm/fileac4143764d/monocle3_0.2.3.0.tar.gz’ had non-zero exit status

I installed the pachage sf but still having the same problem.

**traceback()**
10: stop(remote_install_error(remotes[[i]], e))
9: value[[3L]](cond)
8: tryCatchOne(expr, names, parentenv, handlers[[1L]])
7: tryCatchList(expr, classes, parentenv, handlers)
6: tryCatch(res[[i]] <- install_remote(remotes[[i]], ...), error = function(e) {
       stop(remote_install_error(remotes[[i]], e))
   })
5: install_remotes(remotes, auth_token = auth_token, host = host, 
       dependencies = dependencies, upgrade = upgrade, force = force, 
       quiet = quiet, build = build, build_opts = build_opts, build_manual = build_manual, 
       build_vignettes = build_vignettes, repos = repos, type = type, 
       ...)
4: force(code)
3: withr::with_path(rtools_path(), code)
2: pkgbuild::with_build_tools({
       ellipsis::check_dots_used(action = getOption("devtools.ellipsis_action", 
           rlang::warn))
       {
           remotes <- lapply(repo, github_remote, ref = ref, subdir = subdir, 
               auth_token = auth_token, host = host)
           install_remotes(remotes, auth_token = auth_token, host = host, 
               dependencies = dependencies, upgrade = upgrade, force = force, 
               quiet = quiet, build = build, build_opts = build_opts, 
               build_manual = build_manual, build_vignettes = build_vignettes, 
               repos = repos, type = type, ...)
       }
   }, required = FALSE)
1: devtools::install_github("cole-trapnell-lab/monocle3")

**sessionInfo():**
R version 4.0.1 (2020-06-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=English_Belgium.1252  LC_CTYPE=English_Belgium.1252    LC_MONETARY=English_Belgium.1252
[4] LC_NUMERIC=C                     LC_TIME=English_Belgium.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] rstudioapi_0.11   magrittr_1.5      usethis_1.6.1     devtools_2.3.1    pkgload_1.1.0    
 [6] R6_2.4.1          rlang_0.4.7       fansi_0.4.1       tools_4.0.1       pkgbuild_1.1.0   
[11] xfun_0.17         sessioninfo_1.1.1 tinytex_0.25      cli_2.0.2         withr_2.2.0      
[16] ellipsis_0.3.1    remotes_2.2.0     assertthat_0.2.1  digest_0.6.25     rprojroot_1.3-2  
[21] crayon_1.3.4      processx_3.4.4    callr_3.4.4       fs_1.5.0          ps_1.3.4         
[26] curl_4.3          testthat_2.3.2    memoise_1.1.0     glue_1.4.2        compiler_4.0.1   
[31] desc_1.2.0        backports_1.1.9   prettyunits_1.1.1

Many thanks in advance

**Comment by brgew** [comment]
Hi,
Is there any additional information that may suggest the reason why Monocle3 fails to install?

**Comment by Leonruniing** [comment]
Hi, I am having exactly the same issue. Do you figure it out? Any solution?
thanks

**Comment by Leonruniing** [comment]
I solved this issue by just updating to the new released R4.0.3. Everything works fine now.

**Comment by zhaoxi10** [comment]
I have same issue, even updating to R4.0.3, still got the same error. Windows 10 system

**Comment by brgew** [comment]
Hi,

Do you get any detailed error message that might suggest why the install failed?

**Comment by zhaoxi10** [comment]
Thank you for responding to me. I ended up manually installing those specific packages that couldn’t be installed ( something like zero exist).

Best,
Xiaohong

On Feb 24, 2021, at 19:30, brgew <notifications@github.com> wrote:

﻿

Hi,

Do you get any detailed error message that might suggest why the install failed?
