### ISSUE TITLE
error when install monocle3

### ISSUE THREAD

**Issue by ZHIDIHUAYUAN** [cole-trapnell-lab/monocle3#427]
Hi,
when I run the command: devtools::install_github('cole-trapnell-lab/monocle3')
I got the following:
In file included from gdal.cpp:1:0:
./gdal.h:3:1: error: ‘OGRSpatialReference’ does not name a type
 OGRSpatialReference *handle_axis_order(OGRSpatialReference *sr);
 ^
./gdal.h:4:1: error: ‘Rcpp’ does not name a type
 Rcpp::List create_crs(const OGRSpatialReference *ref, bool set_input);
 ^
make: *** [gdal.o] Error 1
ERROR: compilation failed for package ‘sf’

I had installed:
GDAL 2.0.1; PROJ 4.8.0; GEOS 3.4.2

I don't know what I should do.

**Comment by brgew** [comment]
Hi,
Can you try installing 'sf' in R using the command 'install.packages('sf')'? I googled on the error message and found a link to
https://github.com/r-spatial/sf/issues/1140. Perhaps this helps?

**Comment by brgew** [comment]
No response.
