### ISSUE TITLE
Clarification on batch effect correction

### ISSUE THREAD

**Issue by Connorr0** [cole-trapnell-lab/monocle3#428]
I was wondering if Monocle 3 uses the batch effect corrected data for differential expression and visualizations or just the UMAP creation?

**Comment by Connorr0** [comment]
I assume it would only be for the UMAP, but I wanted to check.

**Comment by hpliner** [comment]
Hi @Connorr0, Just the UMAP and related visualization, not the differential expression. You can include batch as a covariate when running DE if you'd like to correct there.
Hannah
