### ISSUE TITLE
leidenbase installation error (different one)- macOS 10.15.6 R 4.0.2

### ISSUE THREAD

**Issue by haircell** [cole-trapnell-lab/monocle3#432]
Hi,

I'm looking to install monocle3. I upgraded to a new macbook pro 3 months ago with newly installed R and have not been able to get monocle3 installed again. All of the listed dependencies are installed. When I run `devtools::install_github('cole-trapnell-lab/leidenbase')`, I get the following:
```
Downloading GitHub repo cole-trapnell-lab/leidenbase@HEAD
✓  checking for file ‘/private/var/folders/g0/v1bzrcmn6kx6zpnx83d6_yv80000gp/T/RtmpEIztoE/remotes3fb22617eff2/cole-trapnell-lab-leidenbase-8c52ebc/DESCRIPTION’ ...
─  preparing ‘leidenbase’: (378ms)
✓  checking DESCRIPTION meta-information
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories (569ms)
─  building ‘leidenbase_0.1.2.tar.gz’
   
* installing *source* package ‘leidenbase’ ...
** using staged installation
checking for gcc... /usr/local/opt/llvm/bin/clang -fopenmp
checking whether the C compiler works... no
configure: error: in `/private/var/folders/g0/v1bzrcmn6kx6zpnx83d6_yv80000gp/T/RtmpnKAypo/R.INSTALL11add4efb7848/leidenbase':
configure: error: C compiler cannot create executables
See `config.log' for more details
ERROR: configuration failed for package ‘leidenbase’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/leidenbase’
Error: Failed to install 'leidenbase' from GitHub:
  (converted from warning) installation of package ‘/var/folders/g0/v1bzrcmn6kx6zpnx83d6_yv80000gp/T//RtmpEIztoE/file3fb26d8a0c67/leidenbase_0.1.2.tar.gz’ had non-zero exit status
```

I'm on macOS Catalina 10.15.6 and R version 4.0.2 (2020-06-22). 

Any guidance would be much appreciated. Thanks!

**Comment by carbycrab** [comment]
I am having the same problem as @haircell . Here are my compiler versions.
`GNU Fortran (GCC) 10.2.0`
`Xcode 12.2
Build version 12B5025f`

`>sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.5
Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib
locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8`

I have also attacted my `install.out` and `Makeconf` file. 

Thanks so much for the help!


[install.out.zip](https://github.com/cole-trapnell-lab/monocle3/files/5379286/install.out.zip)

[Makeconf.zip](https://github.com/cole-trapnell-lab/monocle3/files/5379288/Makeconf.zip)

**Comment by GBeattie** [comment]
I've also got this issue, I feel it's possibly related to the Bioconductor version 3.10 requirement, which needs R 3.6. Would be great to find a workaround!

**Comment by wzcaltech** [comment]
same here, can't install 'monocle3' either...
> devtools::install_github('cole-trapnell-lab/monocle3')
Downloading GitHub repo cole-trapnell-lab/monocle3@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                                 
2: CRAN packages only                  
3: None                                
4: digest     (0.6.25 -> 0.6.26) [CRAN]
5: warp       (0.1.0  -> 0.2.0 ) [CRAN]
6: labeling   (0.3    -> 0.4.2 ) [CRAN]
7: furrr      (0.2.0  -> 0.2.1 ) [CRAN]
8: data.table (1.13.0 -> 1.13.2) [CRAN]

Enter one or more numbers, or an empty line to skip updates:1
digest     (0.6.25 -> 0.6.26) [CRAN]
warp       (0.1.0  -> 0.2.0 ) [CRAN]
labeling   (0.3    -> 0.4.2 ) [CRAN]
furrr      (0.2.0  -> 0.2.1 ) [CRAN]
data.table (1.13.0 -> 1.13.2) [CRAN]
Skipping 9 packages not available: SummarizedExperiment, S4Vectors, limma, DelayedMatrixStats, DelayedArray, BiocGenerics, batchelor, SingleCellExperiment, Biobase
Installing 8 packages: digest, warp, labeling, furrr, data.table, limma, DelayedMatrixStats, batchelor
Error: Failed to install 'monocle3' from GitHub:
  (converted from warning) packages ‘limma’, ‘DelayedMatrixStats’, ‘batchelor’ are not available (for R version 4.0.2)

please help!!!

**Comment by wzcaltech** [comment]
I manually installed  ‘limma’, ‘DelayedMatrixStats’, and ‘batchelor’ from Bioconductor and now it works!

**Comment by GBeattie** [comment]
> I manually installed ‘limma’, ‘DelayedMatrixStats’, and ‘batchelor’ from Bioconductor and now it works!

Tried this and problem not fixed.

**Comment by brgew** [comment]
Hi haircell,
The error message is clear that the C compiler does not work. The message says that it found the C compiler in /usr/local/opt/llvm/bin/clang, which differs from where I find clang on my system: 

```
type clang
clang is /usr/bin/clang
```

I installed Apple's Xcode package and the command line utilities for it. This, in addition to a gfortran compiler from  https://github.com/fxcoudert/gfortran-for-macOS/releases, works for me.

**Comment by GBeattie** [comment]
Hey @brgew 

Unfortunately I am still getting the error despite passing the compiler checks. I'm on Catalina 10.15.7, R 4.0.2, with the most recent Xcode w/ command line utilities and gfortran installed.

```
> devtools::install_github('cole-trapnell-lab/leidenbase')
Downloading GitHub repo cole-trapnell-lab/leidenbase@HEAD
✓  checking for file ‘/private/var/folders/3w/c5z_hyws6gvgprcvdpk_7x7c0000gn/T/RtmprFvhKH/remotes3e3e1a5386f5/cole-trapnell-lab-leidenbase-8c52ebc/DESCRIPTION’ ...
─  preparing ‘leidenbase’: (1.9s)
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories (1.7s)
─  building ‘leidenbase_0.1.2.tar.gz’
   
* installing *source* package ‘leidenbase’ ...
** using staged installation
checking for gcc... clang -mmacosx-version-min=10.13
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang -mmacosx-version-min=10.13 accepts -g... yes
checking for clang -mmacosx-version-min=10.13 option to accept ISO C89... none needed
checking whether we are using the GNU C++ compiler... yes
checking whether clang++ -mmacosx-version-min=10.13 -std=gnu++11 accepts -g... yes
configure: error: no C++ compiler found or it cannot create executables
ERROR: configuration failed for package ‘leidenbase’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/leidenbase’
Error: Failed to install 'leidenbase' from GitHub:
  (converted from warning) installation of package ‘/var/folders/3w/c5z_hyws6gvgprcvdpk_7x7c0000gn/T//RtmprFvhKH/file3e3e61c14c53/leidenbase_0.1.2.tar.gz’ had non-zero exit status
```

**Comment by brgew** [comment]
Hi @GBeattie,

Can you try running clang from the command line in a terminal, for example

$ clang --version

Running this command, I get the response

```
Apple clang version 12.0.0 (clang-1200.0.32.28)
Target: x86_64-apple-darwin20.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

```

**Comment by GBeattie** [comment]
@brgew Thank you for looking into this, see below!

```
$ clang --version
Apple clang version 12.0.0 (clang-1200.0.32.2)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by brgew** [comment]
Hi @GBeattie,

Your C++ compiler doesn't work, according to the error message although the C compiler passes its test. 

You can try getting more information about the C++ compiler. It looks like the configure script finds clang++ when it looks for a C++ compiler so the problem appears to be that clang++ doesn't compile successfully a test program. You might try making a file tst.cc with the lines

```
#include <iostream>

int main() {
    std::cout << "Hello World!";
    return 0;
}

```
and compiling it with

`clang++ -o tst tst.cc`

and see if it runs when you type 'tst'.

**Comment by GBeattie** [comment]
@brgew Tested my clang++ as you described, no issue in this scenario.

```
$ ./tst
Hello World!
```

**Comment by GBeattie** [comment]
@brgew, I've managed to fix the issue.

For anyone else who has the same issue, I followed these steps:
https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/

In addition I required the following commands (in terminal):
```
sudo xcode-select --reset
sudo xcode-select -s /Library/Developer/CommandLineTools
```

**Comment by brgew** [comment]
Is this issue resolved?
