### ISSUE TITLE
using monocle3 on several clusters

### ISSUE THREAD

**Issue by ZHIDIHUAYUAN** [cole-trapnell-lab/monocle3#434]
Hi,
I used Seurat to cluster my scRNA data. The result is shown below：
<img width="358" alt="image" src="https://user-images.githubusercontent.com/66869156/96612522-6cd21f80-1330-11eb-88e4-844da59cd9af.png">
Now, I want to use Monocle3 on cluster 0, 2, and 12. Based on some background knowledge, we guess that there is a trajectory between these clusters. I just extract these clusters and running Monocle3 on these clusters.
And my code is:
`part2<-subset(object.integrated, subset = seurat_clusters %in% c('0','2','12')) `
`cds2 <- as.cell_data_set(part2) `
`cds2 <- cluster_cells(cds2)`
`cds2 <- learn_graph(cds2)`
I don't know if there is a problem with my code. Can you give me some suggestions？
Thanks.

**Comment by hpliner** [comment]
You need to run preprocess_cds and reduce_dimension if you'd like to run learn_graph on just the selected cells. If you run into errors, please reopen
