### ISSUE TITLE
When I cluster my samples using Monocle3 it gives me that they are all one cluster

### ISSUE THREAD

**Issue by ucbtsh6** [cole-trapnell-lab/monocle3#441]
I preprocessed my data it is scRNA-seq for 64 sample at 3 different time points as they all run on the same batch and from yeast sample then I ignored the batch normalization
then I did dimension reduction as folloring

**cds <- preprocess_cds(cds, num_dim = 50)**
#Warning in (function (A, nv = 5, nu = nv, maxit = 1000, work = nv + 7, reorth = TRUE,  :
  You're computing too large a percentage of total singular values, use a standard svd instead.
**> cds <- reduce_dimension(cds)**
#No preprocess_method specified, using preprocess_method = 'PCA'
**> cds <- cluster_cells(cds)**
** cds <- learn_graph(cds)**
but it gives me only 1 partition (cluster) I dont know why

 
![image](https://user-images.githubusercontent.com/57362373/97712563-830d7780-1ab6-11eb-883f-947bcfbfcc24.png)

**Comment by hpliner** [comment]
You're working with very few cells here so I'm guessing the algorithm is simply not finding sufficient clustering to split the cells. You can modify the resolution of the clustering by changing the "resolution" parameter in cluster_cells

**Comment by ucbtsh6** [comment]
Hello,
Can you please help me how to change the "resolution" parameter in cluster_cells and what do you suggest it to be?

On 2 Nov 2020, at 10:43, Hannah A Pliner <notifications@github.com<mailto:notifications@github.com>> wrote:



You're working with very few cells here so I'm guessing the algorithm is simply not finding sufficient clustering to split the cells. You can modify the resolution of the clustering by changing the "resolution" parameter in cluster_cells
