### ISSUE TITLE
How I do get the state Id/ Branch ID for each cell in Monocle 3?

### ISSUE THREAD

**Issue by ayeshasdina** [cole-trapnell-lab/monocle3#442]
Hi All,

I am very new in using Monocle 3.
I need to know the state of each cell after ordering the cells. I meant - which branch does a cell belong to?
After going through Monocle 2, my understanding is the OrderCells() can update the cell_data_set with State and Pseudotime.
But in Monocle 3 I could not find anything like this. However, in Monocle 3 there is a separate function to extract pseudotime but not the state.

Could anyone explain what could be a solution?

Thanks in Advance.

**Comment by brgew** [comment]
Please post questions to https://groups.google.com/d/forum/monocle-3-users.

**Comment by ravipatel4** [comment]
Hi @ayeshasdina, did you find the answer? I am also interested in extracting the State/Branch id for each cell. Thanks.

**Comment by ayeshasdina** [comment]
No, I didn't get the answer yet.
