### ISSUE TITLE
Monocle3 not giving correct class name for input_cds (perhaps not installed correctly?)

### ISSUE THREAD

**Issue by quinamatics** [cole-trapnell-lab/monocle3#447]
Hi, I'm getting the attached error while running monocle3 on my input_cds to generate gene activity scores for some cell data

When I print out input_cds, I'm getting class: cell_data_set, which is incorrect, as pointed out in #38. However, I'm completely following the documentation (copy and pasting commands), installing the correct monocle3 and cicero3 for monocle3 versions and this error still persists. It's very confusing so I would like some pointers as to what is wrong. By the way, when I run library(monocle3) and library(cicero) there are no logs.

The exact commands I run are:
```
if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager") BiocManager::install(version = "3.11")

BiocManager::install(c('BiocGenerics', 'DelayedArray', 'DelayedMatrixStats', 'limma', 'S4Vectors', 'SingleCellExperiment', 'SummarizedExperiment', 'batchelor', 'Matrix.utils'))

install.packages("devtools") devtools::install_github('cole-trapnell-lab/leidenbase') devtools::install_github('cole-trapnell-lab/monocle3')

if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager") BiocManager::install(c("Gviz", "GenomicRanges", "rtracklayer"))

install.packages("devtools") devtools::install_github("cole-trapnell-lab/cicero-release", ref = "monocle3", force = TRUE)

And after loading my dataset (with commands straight from the cicero3 docs), I run this to get input_cds

`input_cds <- suppressWarnings(new_cell_data_set(indata,
cell_metadata = cellinfo,
gene_metadata = peakinfo))

input_cds <- monocle3::detect_genes(input_cds)

#Ensure there are no peaks included with zero reads
input_cds <- input_cds[Matrix::rowSums(exprs(input_cds)) != 0,] `

```
This is when I see that input_cds has the wrong class name, but I followed the exact commands to install monocle3? Also, library(monocle3) outputs nothing and I don't see all check marks after running the installation command, as shown in the second screenshot.

<img width="1163" alt="Screen Shot 2020-11-13 at 1 43 41 PM" src="https://user-images.githubusercontent.com/28470823/99109070-41042b80-25b6-11eb-9d95-ae47a187764b.png">

<img width="1124" alt="Screen Shot 2020-11-13 at 1 42 07 PM" src="https://user-images.githubusercontent.com/28470823/99108936-0ef2c980-25b6-11eb-9262-38b87a38a367.png">

**Comment by hpliner** [comment]
Addressed in Cicero github
