### ISSUE TITLE
residual_model_formula_str in preprocess_cds (align_cds?)

### ISSUE THREAD

**Issue by swbioinf** [cole-trapnell-lab/monocle3#448]
Is the residual_model_formula_str parameter of preprocess_cds getting ignored?

If I attempt to subtract continuous cell column 'TotalCountLog' via specifying residual_model_formula_str in the preprocess_cds call, it doesnt seem to do anything. As far as I can tell in the code for preprocess_cds it isn't used?

I'm guessing this funtionality is now in align_cds() - If so, could the parameter be removed from preprocess_cds?

Thanks!
  

**To Reproduce**

In this example cds1 and cds2 UMAPs are identical - cds3 behaves as expected.

```
# No  residual model formula string
cds1 <- preprocess_cds(cds)
cds1 <- reduce_dimension(cds1, reduction_method="UMAP", preprocess_method = "PCA")

# residual model formula string  - As per preprocessed_cds
cds2 = preprocess_cds(cds, residual_model_formula_str= "~TotalCountLog")
cds2 <- reduce_dimension(cds2, reduction_method="UMAP", preprocess_method = "PCA")  
reducedDims(cds2) # Shows PCA UMAP

# Use align_cds
cds3 <- preprocess_cds(cds)
cds3 <- align_cds(cds3, residual_model_formula_str= "~TotalCountLog") 
cds3 <- reduce_dimension(cds3, reduction_method="UMAP", preprocess_method = "Aligned")
```

**sessionInfo():**

monocle3_0.2.3.0

**Comment by brgew** [comment]
Hi,
This is fixed in Monocle3 version 1.0.
