### ISSUE TITLE
Problem with fit_models

### ISSUE THREAD

**Issue by pabloatria18** [cole-trapnell-lab/monocle3#451]
Hello
I am trying to run:
> gene_fits <- fit_models(cds_subset, model_formula_str = "~cluster")

And I get this error:
Error: Problem with `mutate()` input `status`.
x object 'model' not found
ℹ Input `status` is `purrr::map(...)`.
Run `rlang::last_error()` to see where the error occurred.

It seems is an error related to the dplyr package, but I am not able to solve it. 

Thank you

**Comment by jws777** [comment]
Hi @pabloatria18 - did you fix this problem please? I have the same issue and wondered if you solved it as you closed the topic. Thanks!
