### ISSUE TITLE
preprocess cds error

### ISSUE THREAD

**Issue by zhaoxi10** [cole-trapnell-lab/monocle3#454]
After I load the cds and run 
> cds <- preprocess_cds(cds, num_dim = 100)
I got the error below
**Error in validObject(.Object) : 
  invalid class “DelayedMatrix” object: superclass "DataTable_OR_NULL" not defined in the environment of the object's class**

**traceback()**
11: stop(msg, ": ", errors, domain = NA)
10: validObject(.Object)
9: initialize(value, ...)
8: initialize(value, ...)
7: new(...)
6: new2(Class, seed = seed)
5: new_DelayedArray(seed)
4: DelayedArray::DelayedArray(x)
3: DelayedArray::DelayedArray(x)
2: sparse_prcomp_irlba(Matrix::t(FM), n = min(num_dim, min(dim(FM)) - 
       1), center = scaling, scale. = scaling)
1: preprocess_cds(cds, num_dim = 100)

**sessionInfo():**

R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

**Comment by lyuguol** [comment]
> After I load the cds and run
> 
> > cds <- preprocess_cds(cds, num_dim = 100)
> > I got the error below
> > **Error in validObject(.Object) :
> > invalid class “DelayedMatrix” object: superclass "DataTable_OR_NULL" not defined in the environment of the object's class**
> 
> **traceback()**
> 11: stop(msg, ": ", errors, domain = NA)
> 10: validObject(.Object)
> 9: initialize(value, ...)
> 8: initialize(value, ...)
> 7: new(...)
> 6: new2(Class, seed = seed)
> 5: new_DelayedArray(seed)
> 4: DelayedArray::DelayedArray(x)
> 3: DelayedArray::DelayedArray(x)
> 2: sparse_prcomp_irlba(Matrix::t(FM), n = min(num_dim, min(dim(FM)) -
> 1), center = scaling, scale. = scaling)
> 1: preprocess_cds(cds, num_dim = 100)
> 
> **sessionInfo():**
> 
> R version 4.0.3 (2020-10-10)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 18363)

Hello Xi,

Did you manage to solve the problem? I encountered the same one.

Could you please show me how to fix it?

Many thanks!

Best,

Guoliang

**Comment by zhaoxi10** [comment]
Hi Guoliang,

I think it is one of the package are not compatible with Monocle3, but I don’t remember which  package. I updated all the packages loaded with Monocle3 and problem was fixed.

Hope this helps,
Xiaohong

On Dec 21, 2020, at 09:51, lyuguol <notifications@github.com> wrote:

﻿

After I load the cds and run

cds <- preprocess_cds(cds, num_dim = 100)
I got the error below
Error in validObject(.Object) :
invalid class “DelayedMatrix” object: superclass "DataTable_OR_NULL" not defined in the environment of the object's class

traceback()
11: stop(msg, ": ", errors, domain = NA)
10: validObject(.Object)
9: initialize(value, ...)
8: initialize(value, ...)
7: new(...)
6: new2(Class, seed = seed)
5: new_DelayedArray(seed)
4: DelayedArray::DelayedArray(x)
3: DelayedArray::DelayedArray(x)
2: sparse_prcomp_irlba(Matrix::t(FM), n = min(num_dim, min(dim(FM)) -
1), center = scaling, scale. = scaling)
1: preprocess_cds(cds, num_dim = 100)

sessionInfo():

R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Hello Xi,

Did you manage to solve the problem? I encountered the same one.

Could you please show me how to fix it?

Many thanks!

Best,

Guoliang

**Comment by lyuguol** [comment]
Hello Xiaohong,

Many thanks for the reply!

I will try to update them then.

All the best,

Guoliang



zhaoxi10 <notifications@github.com> 于2020年12月22日周二 下午5:03写道：

> Hi Guoliang,
>
> I think it is one of the package are not compatible with Monocle3, but I
> don’t remember which package. I updated all the packages loaded with
> Monocle3 and problem was fixed.
>
> Hope this helps,
> Xiaohong
>
