### ISSUE TITLE
Integrating seurat v3 object into monocle3 

### ISSUE THREAD

**Issue by afcmalone** [cole-trapnell-lab/monocle3#457]
Is it now possible to import a seurat v3 object into monocle3 as a cds object now?
I know this has been in development and wondered if this functionality is now available.
If so, is the resulting cds object fully functional?

yours,
Andrew

**traceback()**
After the error, run traceback() in R and post the output:

**Expected behavior**

**Screenshots**

**sessionInfo():**
Run sessionInfo() in R and post the output

**Additional context**

**Comment by brgew** [comment]
Hi,

The Satija Lab developed a function that converts Seurat objects to Monocle objects. See

https://rdrr.io/github/satijalab/seurat-wrappers/man/as.cell_data_set.html
