### ISSUE TITLE
resolution setting for "find_gene_modules"

### ISSUE THREAD

**Issue by Leonrunning** [cole-trapnell-lab/monocle3#462]
Hi,

Thanks for developing such a useful tool. I got most things worked out with Monocle3. The issue I met is about the resolution setting for the function of "find_gene_modules". I found two different ways to do it on your vignettes, one is "resolution=c(0,10^seq(-6,-1)", the other is "resolution=1e-3". While the latter one is reasonable and easy to understand, the former one does not make sense to me. Would you please explain the meaning for "c(0,10^seq(-6,-1)"?  Two values?

thanks

**Comment by Leonrunning** [comment]
One following issue is different numbers of modules were generated with a same resolution but performed at different times.  I used "resolution=1e-3".  Any idea about how does that happen? Any ideas would be highly appreciated.
Thanks

**Comment by brgew** [comment]
Hi,

The former expression gives a series of resolutions for evaluation. Entering the expression at the R command line gives

```
 c(0,10^seq(-6,-1))
[1] 0e+00 1e-06 1e-05 1e-04 1e-03 1e-02 1e-01
```

**Comment by Leonrunning** [comment]
All right. Thanks
