### ISSUE TITLE
Monocle3 installation error

### ISSUE THREAD

**Issue by LenonaFan** [cole-trapnell-lab/monocle3#486]
I'm trying to install monocle3 on R 4.0.4 but it is not working and showing me this error after I use the code
devtools::install_github('cole-trapnell-lab/leidenbase'):
ld: library not found for -lquadmath
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [leidenbase.so] Error 1
ERROR: compilation failed for package ‘leidenbase’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/leidenbase’
Error: Failed to install 'monocle3' from GitHub:
  Failed to install 'leidenbase' from GitHub:
  (converted from warning) installation of package ‘/var/folders/j5/w1grb3_n0_b2vb2s0hwkrgwr0000gn/T//Rtmp7HOEii/file34768ca4b80/leidenbase_0.1.2.tar.gz’ had non-zero exit status

so how can I solve this?

**Comment by brgew** [comment]
Hi,

The leidenbase repository has instructions for reporting install errors

https://github.com/cole-trapnell-lab/leidenbase/blob/master/doc/issue_report_install.md

Please submit an issue on that github repository.

Thank you.
