### ISSUE TITLE
Error when running cluster_cells() function

### ISSUE THREAD

**Issue by eudoraleer** [cole-trapnell-lab/monocle3#491]
Hi,

I have problem running cluster_cells() function in CentOS 8:

**current_cicero <- cluster_cells(cds = current_cicero, reduction_method = "UMAP")

/usr/include/c++/8/bits/stl_vector.h:932: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = double; _Alloc = std::allocator<double>; std::vector<_Tp, _Alloc>::reference = double&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.

Aborted (core dumped)**

Please assist me with this problem, thank you.

**Comment by bharris12** [comment]
I've been having issues with that too, it seems to be some issue with the leiden clustering package, I was able to "solve it" by changing the clustering method to louvain using `cluster_method = 'louvain'` in the `cluster_cells` function

**Comment by eudoraleer** [comment]
> I've been having issues with that too, it seems to be some issue with the leiden clustering package, I was able to "solve it" by changing the clustering method to louvain using `cluster_method = 'louvain'` in the `cluster_cells` function

Thank you!! I have also managed to solve it, but my way was to delete all my gcc versions and fresh install an latest version of gcc 10.

**Comment by brgew** [comment]
Hi,
 
This problem should be solved in leidenbase release 0.1.3 thanks to the efforts of Vincent Traag.
