### ISSUE TITLE
How can I save a cds file?

### ISSUE THREAD

**Issue by sylash92** [cole-trapnell-lab/monocle3#531]
I might have a completely wrong idea about a cell_data_set object,
but I cannot find any function where I can save cds object after all the analysis.
It seems like I have to re-do all of the learn_graph and cluster_cells every time after reloading the single cell data as cds.
I might be to accustomed to saving every analysis data as rds when I'm using Seurat, but it seems weird there isn't a single function to save cds and load cds from previous analysis.

**Comment by astrid12345** [comment]
Hi sylash92, 

you can use readRDS() and saveRDS() functions. They work perfectly for cds objects as well.
