### ISSUE TITLE
Add section to website showing how to plot genes in pseudotime along a selected path

### ISSUE THREAD

**Issue by ctrapnell** [cole-trapnell-lab/monocle3#58]
When we resolve #32, we will need a section in the manual showing the user clicking on a path to retrieve a subset of cells, then passing them to plot_genes_in_pseudotime to look at dynamics of specific markers.

**Comment by aishwaryagogate** [comment]
I have the gif ready for choosing the root node

**Comment by hpliner** [comment]
Done
