### ISSUE TITLE
plot_cells_3d raises error when coloring by pseudotime

### ISSUE THREAD

**Issue by ctrapnell** [cole-trapnell-lab/monocle3#59]
In the worm embryo example:

cds_3d = reduce_dimension(cds, max_components = 3)
cds_3d = cluster_cells(cds_3d)
cds_3d = learn_graph(cds_3d)
cds_3d = order_cells(cds_3d, root_pr_nodes=get_earliest_principal_node(cds))

cds_3d_plot_obj = plot_cells_3d(cds_3d, color_cells_by="pseudotime")

raises an error:
Error in scales::col_numeric(pal, rng, na.color = na.color) : 
  Wasn't able to determine range of domain
In addition: Warning message:
In RColorBrewer::brewer.pal(N, "Set2") :
  minimal value for n is 3, returning requested palette with 3 different levels

**Comment by jietian-327** [comment]
Anything new here?
