### ISSUE TITLE
plot_cells_3d can't color by colData(cds)

### ISSUE THREAD

**Issue by ctrapnell** [cole-trapnell-lab/monocle3#60]
In the worm embryo data:

cds_3d = reduce_dimension(cds, max_components = 3)
cds_3d = cluster_cells(cds_3d)
cds_3d = learn_graph(cds_3d)
cds_3d = order_cells(cds_3d, root_pr_nodes=get_earliest_principal_node(cds))

cds_3d_plot_obj = plot_cells_3d(cds_3d, color_cells_by="cell.type")

Only plots the principal graph. Cells don't render

**Comment by hubaoyi00** [comment]
Run this:
cds_3d@colData@listData$cell.type <- as.character(cds_3d@colData@listData$cell.type)
This will fix the problem.

**Comment by dimurali93** [comment]
I am having this same problem. Could you let me know how to solve this issue.
