### ISSUE TITLE
Can't install monocle3 in 4.2.0 R version

### ISSUE THREAD

**Issue by FrenchDi** [cole-trapnell-lab/monocle3#603]
Hello I'm student in intership trying to learn how to use R.
I have a problem for monocle3.
I have no error message for install Monocle 3 with the intalling instruction. 
I use this link : https://cole-trapnell-lab.github.io/monocle3/docs/installation/

But when in testing installation with : library(monocle3), i have this error message " none 'monocle3' package is finding"

So I try install.packages('monocle3') but i have an other message who said that monocle3 is not availabe for this R version. But in the installation's link , we need  R version 4.1.0 or higher. 
I try this  BiocManager::install("cole-trapnell-lab/monocle3") too but it doesn't work.

I don't know what to do and how solve this problem. 
Thanx for your attention and yopur help.

**Comment by fizwit** [comment]
I have verified that Monocle3 1.0.0 can be installed with R-4.2.0.  Look at the output from .libPaths(). Do you have a personal R library? Maybe try installing with the additional lib argument.

```
devtools::install_github('cole-trapnell-lab/monocle3', lib="/path/to/your/personal/R-libraries")
```

**Comment by FrenchDi** [comment]
> 

thank for your answer, i finnally sucess to install monocle3.
