### ISSUE TITLE
thin black outline not showing up when performing plot_cells as shown in tutorial

### ISSUE THREAD

**Issue by megclark3** [cole-trapnell-lab/monocle3#605]
Hi,

when plotting cells using the following function (or one like this):
plot_cells(cds, color_cells_by="cao_cell_type")

I am returned with a UMAP and cells plotted without any sort of outline (how the plots typically look)
<img width="951" alt="Screen Shot 2022-07-06 at 2 57 57 PM" src="https://user-images.githubusercontent.com/62194869/177623019-ab64e370-164c-4bbd-b11b-5cc46b18ce79.png">

However, in the monocle3 tutorial, when they run the same code, a UMAP like this is what appears, and it has a thin black outline around all cell populations. There seem to be no differences in the code being run, so is this an adjustment that is not a part of monocle3 that the tutorial displays? or is there a bug?
<img width="1125" alt="Screen Shot 2022-07-06 at 2 58 52 PM" src="https://user-images.githubusercontent.com/62194869/177623176-b1615b84-f04a-4d66-9739-3328b5a88cca.png">

Thanks
Meg

**Comment by megclark3** [comment]
was just a version problem!

**Comment by megclark3** [comment]
But if anyone knows how to manage this outline / what the function is related to this for plotting genes, I can't find it in the plot_cells extended documentation so not sure if it's accompanied/due to another package monocle is dependent on

**Comment by selenavana** [comment]
Hi! this is a very late reply, but did you ever figure out about the black outline? I am also not sure how to manage it and it shows up when I export as a PDF only, not as PNG. very interesting--I'd really like to get rid of it, haha.

![image](https://user-images.githubusercontent.com/98565796/232940995-68a3195f-76df-4d79-a309-5cc9bc151e38.png)

**Comment by megclark3** [comment]
The only way i've found to get rid of or add the outline is loading a
different version of monocle. Older versions = no outline (I think I load
version 1.0.0?), new versions = all seem to have outline for me

On Tue, Apr 18, 2023 at 9:12 PM selenavana ***@***.***> wrote:

> Hi! this is a very late reply, but did you ever figure out about the black
> outline? I am also not sure how to manage it and it shows up when I export
> as a PDF only, not as PNG. very interesting--I'd really like to get rid of
> it, haha.
>
> [image: image]
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>


-- 
Megan Clark
VMD PhD Candidate
Henao-Mejia Lab
University of Pennsylvania

***@***.***
609-668-7338

**Comment by selenavana** [comment]
> 

Thanks v much for your reply to my very late comment

I actually managed to figure it out by setting cell_size = 0, cell_stroke = 0.75 (or however big you want your individual dots to be)

I think that cell_size and cell_stroke got swapped, somehow, because setting cell_size = 0 gets rid of the black outline. The problem is that cell_stroke is defaulted to be 1/2 of cell_size or whatever, so setting cell_size = 0 without changing cell_stroke gives you a blank plot. 

I hope this helps someone in the future. My new and improved plot! 
![image](https://user-images.githubusercontent.com/98565796/236978472-267b8d7f-e104-4ec9-85d3-e3528e420ae3.png)

**Comment by nihaoWX** [comment]
Thank you so much for sharing! I've been struggling with the black borders that `plot_cell` adds to cells in images for a long time. I asked chatgpt multiple times how to remove them, and the answer was always to set `cell_stroke` to 0, but that didn't work. Below, I've successfully removed the black borders using your method.

  p1<-plot_cells(cds,color_cells_by = "partition",cell_size = 0,cell_stroke = 0.75) +
    scale_color_manual(values = colors_set3)
  p2<-plot_cells(cds,color_cells_by = "auto_majority_voting",cell_size = 0,cell_stroke = 0.75) +
    scale_color_manual(values = colors_set32)

**Comment by nihaoWX** [comment]
<img width="2000" height="1500" alt="Image" src="https://github.com/user-attachments/assets/3f036c02-5fbd-46d0-a8ff-955d08905580" />

<img width="3000" height="1500" alt="Image" src="https://github.com/user-attachments/assets/6d80dbba-6b0c-4a44-b39c-cbb2612691ec" />
