### ISSUE TITLE
Transfer_cell_labels error

### ISSUE THREAD

**Issue by mreg05** [cole-trapnell-lab/monocle3#615]
I am following the vignette for projecting a query data set onto a reference data set https://cole-trapnell-lab.github.io/monocle3/docs/projection/ as I have done successfully previously. However, with my current data sets I get the error:
>  Error in transfer_cell_labels(cds_qry, reduction_method = "UMAP", ref_coldata = colData(cds_ref),  : 
 transfer_cell_labels: matrix and colData rownames do not match

I believe this means
checksum_matrix_rownames <- cds_nn_index[['checksum_rownames']]  !=  checksum_coldata_rownames <- digest::digest(rownames(ref_coldata))

but when I use 
>   cds_nn_index <- get_cds_nn_index(cds=cds_qry, reduction_method="UMAP", nn_control_tmp[['method']], verbose=TRUE)
>   checksum_matrix_rownames <- cds_nn_index[['checksum_rownames']]
and
>   checksum_coldata_rownames <- digest::digest(rownames(colData(cds_ref)))

outside of the transfer_cell_labels function for my query (cds_qry) and reference (cds_ref) data sets the checksum values do match.
I appreciate any guidance on resolving the issue!

**Comment by brgew** [comment]
Hi,

Can you try adding diagnostic messages to the transfer_cell_labels() function?

I would try writing the checksum values that are compared in the 'if' statement. See whether they match the values you calculate on the command line. Sometimes I find it helpful to write longer objects to either a globally accessible object or to a file; that is, it may help here to examine the row names in each case.

Brent

**Comment by mreg05** [comment]
Thanks for your help, Brent! A reinstallation of Monocle3 fixed the issue
Mary
