### ISSUE TITLE
learn_graph() requires igraph_1.3.0. Update dependencies?

### ISSUE THREAD

**Issue by Erlmeierlu** [cole-trapnell-lab/monocle3#638]
The prune_tree() function uses the following code:
`mst_traversal <- igraph::graph.dfs(stree_ori,
                                     root = root_cell,
                                     mode = "all",
                                     unreachable=FALSE,
                                     father=TRUE)`

However, until igraph_1.2.7 igraph::graph.dfs() uses "neimode" instead of "mode" as argument. Using igraph_1.2.7 produces the error message: 
"Error in igraph::graph.dfs(stree_ori, root = root_cell, mode = "all",  :    unused argument (mode = "all")"

**Comment by brgew** [comment]
Hi,

This will be fixed soon in the master branch. I appreciate the help.

Thank you,
Brent

**Comment by brgew** [comment]
Hi,

I updated the igraph and leidenbase version requirements in the DESCRIPTION file of the Monocle3 master branch.

I appreciate your feedback.

Thank you.
Brent
