### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by sys0507** [cole-trapnell-lab/monocle3#645]
Enter one or more numbers, or an empty line to skip updates: 3
-- R CMD build -----------------------------------------------------------------------------------------------------------------
v  checking for file 'C:\Users\leemi\AppData\Local\Temp\RtmpYr5rEc\remotes778c75fd4dbf\cole-trapnell-lab-monocle3-b545460/DESCRIPTION' ... 
-  preparing 'monocle3': (420ms)
v  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts (429ms)
-  checking for empty or unneeded directories
   Omitted 'LazyData' from DESCRIPTION
-  building 'monocle3_1.3.1.tar.gz'
   
Installing package into ‘C:/Users/leemi/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
Calls: source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'renv/activate.R': No such file or directory
Execution halted
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/leemi/AppData/Local/Temp/RtmpYr5rEc/file778c45c5522f/monocle3_1.3.1.tar.gz’ had non-zero exit status

**Comment by brgew** [comment]
Hi,

I haven't seen that problem before so I ran Google searches with the error and message that you report. They may help you uncover the problem.

1) Error in file(filename, "r", encoding = encoding) :
cannot open the connection

URL: https://stackoverflow.com/questions/54421354/error-in-filefilename-r-encoding-encoding-cannot-open-the-connection

2) cannot open file 'renv/activate.R': No such file or directory
URL: https://github.com/rstudio/renv/issues/981

Do either of this help?

Thank you,
Brent
