### ISSUE TITLE
installation problem with or without RStudio

### ISSUE THREAD

**Issue by DelphIONe** [cole-trapnell-lab/monocle3#651]
The output of this command below is "double free or corruption (out)". I updated my gfortran version but it didn't resolved my problem.
Can you help me please ?
The result is the same if I try devtools::install_github('cole-trapnell-lab/monocle3')

> devtools::install_github('cole-trapnell-lab/monocle3', ref="develop")
Downloading GitHub repo cole-trapnell-lab/monocle3@develop
── R CMD build ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/tmp/RtmpKiLEup/remotes33be82ae45788/cole-trapnell-lab-monocle3-b2e9b6b/DESCRIPTION’ ...
─  preparing ‘monocle3’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Omitted ‘LazyData’ from DESCRIPTION
─  building ‘monocle3_1.3.1.tar.gz’
   
Installation du package dans ‘/usr/local/lib/R/site-library’
(car ‘lib’ n'est pas spécifié)
* installing *source* package ‘monocle3’ ...
** using staged installation
** libs
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I'/usr/local/lib/R/site-library/Rcpp/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-a3XuZ5/r-base-4.2.2.20221110=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I'/usr/local/lib/R/site-library/Rcpp/include'    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-a3XuZ5/r-base-4.2.2.20221110=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c clustering.cpp -o clustering.o
g++ -std=gnu++11 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o monocle3.so RcppExports.o clustering.o -L/usr/lib/R/lib -lR
installing to /usr/local/lib/R/site-library/00LOCK-monocle3/00new/monocle3/libs
** R
** inst
** byte-compile and prepare package for lazy loading
double free or corruption (out)
Aborted (core dumped)
ERROR: lazy loading failed for package ‘monocle3’
* removing ‘/usr/local/lib/R/site-library/monocle3’
Message d'avis :
Dans i.p(...) :
  l'installation du package ‘/tmp/RtmpKiLEup/file33be8756b3a17/monocle3_1.3.1.tar.gz’ a eu un statut de sortie non nul

**Comment by brgew** [comment]
Hi,

I doubt that I can identify the problem but it may help if you post the following information


- computer operating system
- C++ compiler name and version
- gfortran version
- Rcpp version


Thank you,
Brent
