### ISSUE TITLE
R version 4.2.3 installing problem (package ‘speedglm’)

### ISSUE THREAD

**Issue by Hansenkor** [cole-trapnell-lab/monocle3#652]
Hi, can you help me how to install the monocle3 package in R version 4.2.3? 
Does anybody have solve the problem of this ? The error message continuously tells me that package speedglm is not 
available for this version of R.  I tried to get in Github speedglm page, but there is problem. 
Is there any other route to install the monocle3 ?

Here is the error message I got. 
It will be really thankful to help me to treat this problem.

**ERROR: dependency 'speedglm' is not available for package 'monocle3'**
* removing 'C:/Users/xx/AppData/Local/R/win-library/4.2/monocle3'
Warning messages:
1: package ‘speedglm’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
2: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\xx\AppData\Local\R\win-library\4.2\00LOCK\limma\libs\x64\limma.dll to C:\Users\xx\AppData\Local\R\win-library\4.2\limma\libs\x64\limma.dll: Permission denied

**Comment by Fablepongiste** [comment]
Speedglm has actually been removed from CRAN

_Package ‘speedglm’ was removed from the CRAN repository.
Removed on 2023-04-01 for policy violation_

So it is not linked to this version of R you would have same on previous ones 
Only way I found was to clone the project on github and install it manually

speedglm package owner answered me that it should be fixed soon.

**Comment by Hansenkor** [comment]
> Speedglm has actually been removed from CRAN
> 
> _Package ‘speedglm’ was removed from the CRAN repository. Removed on 2023-04-01 for policy violation_
> 
> So it is not linked to this version of R you would have same on previous ones Only way I found was to clone the project on github and install it manually
> 
> speedglm package owner answered me that it should be fixed soon.

thanks for your apply @Fablepongiste .

**Comment by PiXeLAllan** [comment]
devtools::install_version('speedglm', '0.3-4', repos = 'https://packagemanager.rstudio.com/cran/2023-03-31')

You can also install the last version available before it was removed using a CRAN snapshot like above.  If you use Microsoft's CRAN there'll be a similar repos you can use.

**Comment by Hansenkor** [comment]
thank you for your apply ^^

**Comment by brgew** [comment]
speedglm version 0.3-5 is available from CRAN.
