### ISSUE TITLE
Repository for monocle alpha is not available

### ISSUE THREAD

**Issue by BlackSlipper** [cole-trapnell-lab/monocle3#654]
Hi, i am trying to reproduce a paper from 2020, and it uses monocle alpha

i couldn't find the  monocle alpha release in this github. and also i think that is the reason why 
i failed to run the command on "http://cole-trapnell-lab.github.io/monocle-release/monocle3/"
this command:
"devtools::install_github("cole-trapnell-lab/monocle-release", ref="monocle3_alpha")" on my R.

it give me this error:
Error: Failed to install 'monocle' from GitHub:
  error reading from connection

is there a way to get the monocle3_alpha release?

thank you in advance.

**Comment by samfux84** [comment]
Same problem for the main version:

> library("devtools")
Loading required package: usethis
> devtools::install_github('cole-trapnell-lab/monocle3')
Downloading GitHub repo cole-trapnell-lab/monocle3@HEAD
Error: Failed to install 'monocle3' from GitHub:
  error reading from connection
>

**Comment by brgew** [comment]
Hi,

The Monocle alpha branch is on the Monocle Github web site rather than the Monocle3 site. Look at

https://github.com/cole-trapnell-lab/monocle-release

Thank you,
Brent
