### ISSUE TITLE
Error in value[[3L]](cond) :    No pseudotime calculated. Must call order_cells first.

### ISSUE THREAD

**Issue by sophieastrof** [cole-trapnell-lab/monocle3#659]
Hi!
I am following the Monocle3 tutorial using RStudio. All steps work until the following section:
#Let's pick one such path, the AFD cells:
AFD_genes <- c("gcy-8", "dac-1", "oig-8")
AFD_lineage_cds <- cds[rowData(cds)$gene_short_name %in% AFD_genes,
                       colData(cds)$cell.type %in% c("AFD")]

The above two steps work, but then I get an error running plot_genes_in_pseudotime:

#The function plot_genes_in_pseudotime() takes a small set of genes and shows you their dynamics as a function of pseudotime:
plot_genes_in_pseudotime(AFD_lineage_cds,
                         color_cells_by="embryo.time.bin",
                         min_expr=0.5)

The error:
 Error in value[[3L]](cond) : 
  No pseudotime calculated. Must call order_cells first.

Thanks!

**Comment by sophieastrof** [comment]
Actually, I figured it out. You guys are missing a line of code in your tutorial
**the first two lines**
AFD_genes <- c("gcy-8", "dac-1", "oig-8")
AFD_lineage_cds <- cds[rowData(cds)$gene_short_name %in% AFD_genes,
                       colData(cds)$cell.type %in% c("AFD")]

**showed be followed by** 
AFD_lineage_cds<-order_cells(AFD_lineage_cds, root_pr_nodes = "Y_1")

**before** 
plot_genes_in_pseudotime(AFD_lineage_cds,
                         color_cells_by="embryo.time.bin",
                         min_expr=0.5)

Could you please tell me what **root_pr_nodes = "Y_1"** mean?

Thank you,
Sophie

**Comment by brgew** [comment]
Hi,

Thank you for pointing out the omission in the documentation.

The `root_pr_nodes = 'Y_1'` gives the principal node that you chose to be the root.

You can find the earliest principal node using the function code

```
get_earliest_principal_node <- function(cds, time_bin="130-170"){
  cell_ids <- which(colData(cds)[, "embryo.time.bin"] == time_bin)

  closest_vertex <-
  cds@principal_graph_aux[["UMAP"]]$pr_graph_cell_proj_closest_vertex
  closest_vertex <- as.matrix(closest_vertex[colnames(cds), ])
  root_pr_nodes <-
  igraph::V(principal_graph(cds)[["UMAP"]])$name[as.numeric(names
  (which.max(table(closest_vertex[cell_ids,]))))]

  root_pr_nodes
}
```

which is given in the Monocle3 documentation section called _Constructing single-cell trajectories_. Additionally, you can view the principal nodes using `plot_cells(..., label_principal_points = TRUE)`

Does this answer your questions?

Thank you,
Brent
