### ISSUE TITLE
Error in dn[[2L]] : subscript out of bounds

### ISSUE THREAD

**Issue by ttt-404** [cole-trapnell-lab/monocle3#660]
Hello, I met a problem like this,  plot_cells worked when using the same code with your test data, but I don't know why it failed with my data.

`> plot_cells(cds, label_groups_by_cluster=FALSE,  color_cells_by = "sample")
Error in dn[[2L]] : subscript out of bounds`

The code I used:

`data4 <- GetAssayData(object=mali_net.integrated, slot="counts")
 pd <- as.data.frame(mali_net.integrated@meta.data)
 fData <- data.frame(gene_short_name=row.names(data4),row.names=row.names(data4)) 

cds <- new_cell_data_set(data4,
                         cell_metadata =pd,
                         gene_metadata = fData)`

![image](https://user-images.githubusercontent.com/49528777/235837161-dc669f06-306a-4f52-a829-589a0f570232.png)

Do you have any idea to sovle it? Thanks so much!

**Comment by brgew** [comment]
Hi,

Is there a column in colData(cds) called 'sample'?

Can you post the output from the command

`str(cds)`

Thank you,
Brent
