### ISSUE TITLE
find marker genes expressed by each cluster no longer working

### ISSUE THREAD

**Issue by organicbrownrice** [cole-trapnell-lab/monocle3#668]
When running the function:

#find marker genes expressed by each cluster

marker_test_res <- top_markers(cds, group_cells_by="partition", 
                               reference_cells=1000)

R results in an error:

Error: (converted from warning) 'as(<lgCMatrix>, "dgCMatrix")' is deprecated.
Use 'as(., "dMatrix")' instead.
See help("Deprecated") and help("Matrix-deprecated").

As doing to Google searches, it appeared that something in this function is no longer supported. Let me know if you need anything further.

Would a current workaround be to work in an older version of R?

**Comment by brgew** [comment]
Hi,

This issue should be fixed in the current Monocle3 version on the master branch.

Thank you,
Brent
