### ISSUE TITLE
Error of plot_cells function to show trajectory graph using monocle3 v1.2.9

### ISSUE THREAD

**Issue by jinming-cheng** [cole-trapnell-lab/monocle3#675]
Dear monocle3 developers ,

I was trying to use `plot_cells` in *monocle3*  version 1.2.9 to show trajectory graph, but there was an error related to `dplyr::select()` showing "<text>:1:7: unexpected symbol". This error is gone if `show_trajectory_graph = FALSE`.

The same code worked well in April 2023, and I saw the error when I was trying  to run the code again recently. The code was run in R 4.2.1 on Linux.

Could you please kindly help me with this issue? Thank you very much!

<img width="623" alt="monocle3_plot_cells_error" src="https://github.com/cole-trapnell-lab/monocle3/assets/45994802/3a003276-2ba0-4df1-8957-ed1e3eac9779">

**Comment by brgew** [comment]
Hi,

I compared the code in the current `plot_cells() `function to the code of last year and I see no suspicious change. Can you make a small cds that causes this problem and send it to me?

I appreciate your feedback and assistance.

Thank you.

Best Wishes,
Brent

**Comment by jinming-cheng** [comment]
Hi Brent,

Thank you for trying the comparison of the code!

I have figured out this issue. It is not caused by `plot_cells()` but caused by `dplyr`. Updating the `dplyr` package will solve this issue.

Thanks again!

Best,
Jinming
