### ISSUE TITLE
Monocle3 is not installing because I cannot update Leidenbase, Igraph and Terra

### ISSUE THREAD

**Issue by mrinmay59** [cole-trapnell-lab/monocle3#678]
I am using R version 4.1.3

I used the following command to install monocle3

BiocManager::install(version = "3.14")
BiocManager::install(c('BiocGenerics', 'DelayedArray', 'DelayedMatrixStats',
                       'limma', 'lme4', 'S4Vectors', 'SingleCellExperiment',
                       'SummarizedExperiment', 'batchelor', 'HDF5Array',
                       'terra', 'ggrastr'))

library(devtools)
devtools::install_github('cole-trapnell-lab/monocle3')

During the process I got the following message
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                                 
2: CRAN packages only                  
3: None                                
4: igraph     (1.4.2  -> 1.5.1 ) [CRAN]
5: terra      (1.7-23 -> 1.7-39) [CRAN]
6: leidenbase (0.1.18 -> 0.1.25) [CRAN]

I tried updating all. igraph, leidenbase and terra are not updating 
I tried updating them separately but they are not updating even when I tried this

I keep getting this message

Warning messages:
1: In i.p(...) : installation of package ‘igraph’ had non-zero exit status
2: In i.p(...) : installation of package ‘terra’ had non-zero exit status
3: In i.p(...) :
  installation of package ‘leidenbase’ had non-zero exit status
4: In i.p(...) :
  installation of package ‘C:/Users/DELL/AppData/Local/Temp/RtmpcTOL1M/file227035102d03/monocle3_1.3.4.tar.gz’ had non-zero exit status

**Comment by szhorvat** [comment]
Your R version is outdated, and CRAN no longer offers pre-compiled packages for it. Use R 4.2 or 4.3 in order to get a binary version of igraph, terra, leidenbase.

**Comment by mrinmay59** [comment]
Hi szhorvat. I updated to r 4.3 and it worked. Thank you. I hope that at this 
https://cole-trapnell-lab.github.io/monocle3/docs/installation/
they had clearly mentioned this.
According to this page the requirement is only 4.1
Thank You once again
