### ISSUE TITLE
Show how to load and cluster single-cell ATAC-seq data

### ISSUE THREAD

**Issue by ctrapnell** [cole-trapnell-lab/monocle3#70]

**Comment by smanne07** [comment]
Hi,


Can you provide us info/instructions on loading and clustering scATACseq data using Monocle3?

Best regards
Sasi

**Comment by hpliner** [comment]
Now documented here: https://cole-trapnell-lab.github.io/monocle3/docs/cicero/ (points to explanation on the Cicero website!)
