### ISSUE TITLE
Update publications page

### ISSUE THREAD

**Issue by hpliner** [cole-trapnell-lab/monocle3#77]

**Comment by hpliner** [comment]
Swap out the bioRxiv version for the nature methods version, plus add the mouse sci-rna-seq paper (Cao, Spielmann et al. Nature (2019))

**Comment by andysheh** [comment]
Do you have a preferred graph that you'd like to be the thumbnail?

**Comment by andysheh** [comment]
Publications have been updated and pushed to gh-pages
