### ISSUE TITLE
Website manual should be split up across multiple pages

### ISSUE THREAD

**Issue by ctrapnell** [cole-trapnell-lab/monocle3#87]
@jspacker thinks the manual should not be organized into a single long page. Splitting up the page into three or four smaller pages would make it more readable. We'd want to keep the table of contents control as is so users can always quickly navigate to the whatever section they want. We should have next section/previous section buttons at the bottom of each major page.

**Comment by andysheh** [comment]
First draft pushed to gh-pages-separated-docs branch. Let me know if there's anything that you would like changed.

**Comment by hpliner** [comment]
@andysheh Can you check that the links on the front page work with the new layout? (Actually can you check all of the links?)

And I'd pull from gh-pages because there have been some changes
