### ISSUE TITLE
visualizing trajectory lines when selecting nodes in learn_graph

### ISSUE THREAD

**Issue by lsaund11** [cole-trapnell-lab/monocle3#89]
It's hard to see the trajectory lines when selecting roots in learn_graph. Possible fixes are (1) add an alpha to the cells, (2) plot lines on top of cells (preferred)

**Comment by hpliner** [comment]
@lsaund11 Was this in 2-D or 3-D?

**Comment by lsaund11** [comment]
@hpliner I just tried it in 2D.
